#######################################################
# 
# CustomerBillingKind.py
# Python implementation of the Class CustomerBillingKind
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:24
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class CustomerBillingKind(Enum):
    """Kind of customer billing.
    """
    # Consolidated bill from energy service supplier (ESS).
    consolidatedEss = auto()
    # Consolidated bill from utility distribution company (UDC).
    consolidatedUdc = auto()
    # Separate bills from ESS and UDC.
    separateEssUdc = auto()
    other = auto()