#######################################################
# 
# PowerQualityPricing.py
# Python implementation of the Class PowerQualityPricing
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:10
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Voltage import Voltage
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Domain.CostPerEnergyUnit import CostPerEnergyUnit
from TC57CIM.IEC61968.Common.Document import Document

@dataclass
class PowerQualityPricing(Document):
    """Pricing can be based on power quality.
    """
    # Emergency high voltage limit.
    emergencyHighVoltLimit: Voltage  = None
 
    # Emergency low voltage limit.
    emergencyLowVoltLimit: Voltage  = None
 
    # Normal high voltage limit.
    normalHighVoltLimit: Voltage  = None
 
    # Normal low voltage limit.
    normalLowVoltLimit: Voltage  = None
 
    # Threshold minimum power factor for this PricingStructure, specified in
    # instances where a special charge is levied if the actual power factor for a
    # Service falls below the value specified here.
    powerFactorMin: Float  = None
 
    # Value of uninterrupted service (Cost per energy).
    valueUninterruptedServiceEnergy: CostPerEnergyUnit  = None
 
    # Value of uninterrupted service (Cost per active power).
    valueUninterruptedServiceP: Float  = None
 
    # Voltage imbalance violation cost (Cost per unit Voltage).
    voltImbalanceViolCost: Float  = None
 
    # Voltage limit violation cost (Cost per unit Voltage).
    voltLimitViolCost: Float  = None
     