#######################################################
# 
# StandardIndustryCode.py
# Python implementation of the Class StandardIndustryCode
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:54
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61968.Common.Document import Document

@dataclass
class StandardIndustryCode(Document):
    """The Standard Industrial Classification (SIC) are the codes that identify the
    type of products/service an industry is involved in, and used for statutory
    reporting purposes. For example, in the USA these codes are located by the
    federal government, and then published in a book entitled "The Standard
    Industrial Classification Manual". The codes are arranged in a hierarchical
    structure.
      Note that Residential Service Agreements are not classified according to the
    SIC codes.
    """
    # Standard alphanumeric code assigned to a particular product/service within an
    # industry.
    code: str  = None
     