#######################################################
# 
# WorkBillingInfo.py
# Python implementation of the Class WorkBillingInfo
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:41:25
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC61970.Base.Domain.Money import Money
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpInvoiceLineItem import ErpInvoiceLineItem
from TC57CIM.IEC61968.Common.Document import Document
from TC57CIM.IEC61968.Work.Work import Work

@dataclass
class WorkBillingInfo(Document):
    """Billing information for work performed for the customer. The history of Work
    Billing Info, Invoices, and Payments is to be maintained in associated
    ActivityRecords.
    """
    # Date and time bill was issued to client.
    issueDateTime: DateTime  = None
 
    # Date and time by which payment for bill is expected from client.
    dueDateTime: DateTime  = None
 
    # Date payment was received from client.
    receivedDateTime: DateTime  = None
 
    # Amount of bill.
    workPrice: Money  = None
 
    # Estimated cost for work. 
    costEstimate: Money  = None
 
    # Amount of price on deposit.
    deposit: Money  = None
 
    # Discount from standard price.
    discount: Float  = None
 
    ErpInvoiceLineItems: List[ErpInvoiceLineItem] = []
 
    Works: List[Work] = []
     