#######################################################
# 
# AllocationResult.py
# Python implementation of the Class AllocationResult
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:47:49
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC62325.MarketOperations.MarketQualitySystem.AllocationResultValues import AllocationResultValues

@dataclass
class AllocationResult:
    """Models Market clearing results.  Indicates market horizon, interval based. Used
    by a market quality system for billing and settlement purposes
    """
    intervalStartTime: DateTime  = None
 
    updateUser: String  = None
 
    updateTimeStamp: DateTime  = None
 
    allocationResultValuess: List[AllocationResultValues] = []
     