#######################################################
# 
# ExpectedEnergy.py
# Python implementation of the Class ExpectedEnergy
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:03
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC62325.MarketOperations.MarketQualitySystem.ExpectedEnergyValues import ExpectedEnergyValues

@dataclass
class ExpectedEnergy:
    """Model Expected Energy  from Market Clearing, interval based
    """
    intervalStartTime: DateTime  = None
 
    updateUser: String  = None
 
    updateTimeStamp: DateTime  = None
 
    ExpectedEnergyValuess: List[ExpectedEnergyValues] = []
     