#######################################################
# 
# FiveMinAuxiliaryData.py
# Python implementation of the Class FiveMinAuxiliaryData
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:16
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC62325.MarketOperations.MarketQualitySystem.AuxiliaryValues import AuxiliaryValues

@dataclass
class FiveMinAuxiliaryData:
    """Models 5-Minutes Auxillary Data
    """
    intervalStartTime: DateTime  = None
 
    updateUser: str  = None
 
    updateTimeStamp: DateTime  = None
 
    auxiliaryValuess: List[AuxiliaryValues] = []
     