#######################################################
# 
# TradingHubPrice.py
# Python implementation of the Class TradingHubPrice
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:51:06
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC62325.MarketOperations.MktDomain.MarketType import MarketType
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC62325.MarketOperations.MarketQualitySystem.TradingHubValues import TradingHubValues

@dataclass
class TradingHubPrice:
    """Models prices at Trading Hubs, interval based
    """
    intervalStartTime: DateTime  = None
 
    marketType: MarketType  = None
 
    updateUser: String  = None
 
    updateTimeStamp: DateTime  = None
 
    tradingHubValuess: List[TradingHubValues] = []
     