#######################################################
# 
# AlarmDisplayType.py
# Python implementation of the Class AlarmDisplayType
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:37:51
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class AlarmDisplayType(Enum):
    Disappear = auto()
    Appear = auto()
    Fleeting = auto()