#######################################################
# 
# DispatchAcceptStatus.py
# Python implementation of the Class DispatchAcceptStatus
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:35
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class DispatchAcceptStatus(Enum):
    NON_RESPONSE = auto()
    OK = auto()
    CANNOT = auto()
    ACCEPT = auto()
    DECLINE = auto()
    PARTIAL = auto()