#######################################################
# 
# MarketScheduleServices.py
# Python implementation of the Class MarketScheduleServices
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:52
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class MarketScheduleServices(Enum):
    retrieveDefaultBidCurves = auto()
    retrieveMarketAwards = auto()
    retrieveMPMResults = auto()
    retrieveSchedulePrices = auto()
    retrieveStartUpShutDownInstructions = auto()