#######################################################
# 
# MarketStatementDocType.py
# Python implementation of the Class MarketStatementDocType
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:46
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class MarketStatementDocType(Enum):
    """market statement document type
    """
    CREDIT = auto()
    MARKET_INITIAL = auto()
    MARKET_RECALC = auto()