#######################################################
# 
# OASISReportType.py
# Python implementation of the Class OASISReportType
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:58
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class OASISReportType(Enum):
    AS_DA_RESULT = auto()
    AS_OP_RSRV = auto()
    AS_REQ = auto()
    AS_RTM_RESULT = auto()
    BIDS_PUBLIC = auto()
    CMMT_RA_MLC = auto()
    CMMT_RMR = auto()
    CRR_CLEARING = auto()
    CRR_INVENTORY = auto()
    ENE_EA = auto()
    ENE_HASP = auto()
    ENE_IFM = auto()
    ENE_MPM = auto()
    ENE_RTM = auto()
    ENE_RUC = auto()
    LOSS_DA_HASP = auto()
    LOSS_RTM = auto()
    PRC_AS = auto()
    PRC_FUEL = auto()
    PRC_HRLY_LMP = auto()
    PRC_INTVL_LMP = auto()
    PRC_CNSTR = auto()
    SLD_FCST = auto()
    SLD_FCST_PEAK = auto()
    SLD_MKTS = auto()
    TRNS_ATC = auto()
    TRNS_OUTAGE = auto()
    TRNS_USAGE = auto()