#######################################################
# 
# OASISErrCode.py
# Python implementation of the Class OASISErrCode
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:05
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class OASISErrCode(Enum):
    1000 = auto()
    1001 = auto()
    1002 = auto()
    1003 = auto()
    1004 = auto()
    1005 = auto()
    1006 = auto()
    1007 = auto()
    1008 = auto()
    1009 = auto()
    1010 = auto()