#######################################################
# 
# SegmentCurveType.py
# Python implementation of the Class SegmentCurveType
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:49
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class SegmentCurveType(Enum):
    COST = auto()
    CONSULTATIVE = auto()