#######################################################
# 
# SystemType.py
# Python implementation of the Class SystemType
# Generated by Enterprise Architect
# Created on:      21-May-2025 11:00:06
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class SystemType(Enum):
    OASIS = auto()