#######################################################
# 
# TradeProductType.py
# Python implementation of the Class TradeProductType
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:51:06
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class TradeProductType(Enum):
    # Physical Energy Tra
    PHY = auto()
    # Energy Trades at Aggregated Pricing Nodes
    APN = auto()
    # Regulation Up Trade
    RUT = auto()
    # Regulation Down Trade
    RDT = auto()
    # Spinning Reserve Trade
    SRT = auto()
    # Non-Spinning Reserve Trade
    NRT = auto()
    # Capacity type trade
    CAP = auto()