#######################################################
# 
# ConnectDisconnectFunction.py
# Python implementation of the Class ConnectDisconnectFunction
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:13
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61970.Base.Domain.Integer import Integer
from TC57CIM.IEC61968.LoadControl.RemoteConnectDisconnectInfo import RemoteConnectDisconnectInfo
from TC57CIM.IEC61970.Base.Wires.Switch import Switch
from TC57CIM.IEC61968.Metering.EndDeviceFunction import EndDeviceFunction

@dataclass
class ConnectDisconnectFunction(EndDeviceFunction):
    """A function that will disconnect and reconnect the customer's load under defined
    conditions.
    """
    # If set true and if disconnection can be operated locally, the operation happens
    # automatically. Otherwise it happens manually.
    isLocalAutoDisconOp: Boolean  = None
 
    # If set true and if reconnection can be operated locally, then the operation
    # happens automatically. Otherwise, it happens manually.
    isLocalAutoReconOp: Boolean  = None
 
    # If set true and if disconnection can be operated remotely, then the operation
    # happens automatically. If set false and if disconnection can be operated
    # remotely, then the operation happens manually.
    isRemoteAutoDisconOp: Boolean  = None
 
    # If set true and if reconnection can be operated remotely, then the operation
    # happens automatically. If set false and if reconnection can be operated
    # remotely, then the operation happens manually.
    isRemoteAutoReconOp: Boolean  = None
 
    # If set true, the switch may disconnect the service at the end of a specified
    # time delay after the disconnect signal has been given. If set false, the switch
    # may disconnect the service immediately after the disconnect signal has been
    # given. This is typically the case for over current circuit-breakers which are
    # classified as either instantaneous or slow acting.
    isDelayedDiscon: Boolean  = None
 
    # Running cumulative count of connect or disconnect events, for the lifetime of
    # this function or until the value is cleared.
    eventCount: Integer  = None
 
    # True if this function is in the connected state.
    isConnected: Boolean  = None
 
    # Information on remote connect disconnect switch.
    rcdInfo: RemoteConnectDisconnectInfo  = None
 
    Switchs: List[Switch] = []
     