#######################################################
# 
# CompositeSwitch.py
# Python implementation of the Class CompositeSwitch
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:08
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Wires.Switch import Switch
from TC57CIM.IEC61970.Base.Core.Equipment import Equipment

@dataclass
class CompositeSwitch(Equipment):
    """A model of a set of individual Switches normally enclosed within the same
    cabinet and possibly with interlocks that restrict the combination of switch
    positions. These are typically found in medium voltage distribution networks.
      A CompositeSwitch could represent a Ring-Main-Unit (RMU), or pad-mounted
    switchgear, with primitive internal devices such as an internal bus-bar plus 3
    or 4 internal switches each of which may individually be open or closed. A
    CompositeSwitch and a set of contained Switches can also be used to represent a
    multi-position switch e.g. a switch that can connect a circuit to Ground, Open
    or Busbar.
    """
    # An alphanumeric code that can be used as a reference to extra information such
    # as the description of the interlocking scheme if any.
    compositeSwitchType: String  = None
 
    # Switches contained in this Composite switch.
    switchs: List[Switch] = []
     