#######################################################
# 
# CoolantType.py
# Python implementation of the Class CoolantType
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:26
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class CoolantType(Enum):
    """Method of cooling a machine.
    """
    # Air.
    air = auto()
    # Hydrogen gas.
    hydrogenGas = auto()
    # Water.
    water = auto()