#######################################################
# 
# EarthFaultCompensator.py
# Python implementation of the Class EarthFaultCompensator
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:47
# Original author: namstutz
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Resistance import Resistance
from TC57CIM.IEC61970.Base.Core.ConductingEquipment import ConductingEquipment

@dataclass
class EarthFaultCompensator(ConductingEquipment):
    """A conducting equipment used to represent a connection to ground which is
    typically used to compensate earth faults..   An earth fault compensator device
    modeled with a single terminal implies a second terminal solidly connected to
    ground.  If two terminals are modeled, the ground is not assumed and normal
    connection rules apply.
    """
    # Nominal resistance of device.
    r: Resistance  = None
     