#######################################################
# 
# FrequencyConverter.py
# Python implementation of the Class FrequencyConverter
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:18
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Frequency import Frequency
from TC57CIM.IEC61970.Base.Domain.ActivePower import ActivePower
from TC57CIM.IEC61970.Base.Domain.Voltage import Voltage
from TC57CIM.IEC61970.Base.Wires.RegulatingCondEq import RegulatingCondEq

@dataclass
class FrequencyConverter(RegulatingCondEq):
    """A device to convert from one frequency to another (e.g., frequency F1 to F2)
    comprises a pair of FrequencyConverter instances. One converts from F1 to DC,
    the other converts the DC to F2.
    """
    # Frequency on the AC side.
    frequency: Frequency  = None
 
    # The maximum active power on the DC side at which the frequence converter should
    # operate.
    maxP: ActivePower  = None
 
    # The maximum voltage on the DC side at which the frequency converter should
    # operate.
    maxU: Voltage  = None
 
    # The minimum active power on the DC side at which the frequence converter should
    # operate.
    minP: ActivePower  = None
 
    # The minimum voltage on the DC side at which the frequency converter should
    # operate.
    minU: Voltage  = None
     