#######################################################
# 
# GroundDisconnector.py
# Python implementation of the Class GroundDisconnector
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:19
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Wires.Switch import Switch

@dataclass
class GroundDisconnector(Switch):
    """A manually operated or motor operated mechanical switching device used for
    isolating a circuit or equipment from ground.
    """
    pass
