#######################################################
# 
# PerLengthSequenceImpedance.py
# Python implementation of the Class PerLengthSequenceImpedance
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:02
# Original author: Tom
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.SusceptancePerLength import SusceptancePerLength
from TC57CIM.IEC61970.Base.Domain.ConductancePerLength import ConductancePerLength
from TC57CIM.IEC61970.Base.Domain.ResistancePerLength import ResistancePerLength
from TC57CIM.IEC61970.Base.Domain.ReactancePerLength import ReactancePerLength
from TC57CIM.IEC61970.Base.Wires.PerLengthImpedance import PerLengthImpedance

@dataclass
class PerLengthSequenceImpedance(PerLengthImpedance):
    """Sequence impedance and admittance parameters per unit length, for transposed
    lines of 1, 2, or 3 phases. For 1-phase lines, define x=x0=xself. For 2-phase
    lines, define x=xs-xm and x0=xs+xm.
    """
    # Zero sequence shunt (charging) susceptance, per unit of length.
    b0ch: SusceptancePerLength  = None
 
    # Positive sequence shunt (charging) susceptance, per unit of length.
    bch: SusceptancePerLength  = None
 
    # Zero sequence shunt (charging) conductance, per unit of length.
    g0ch: ConductancePerLength  = None
 
    # Positive sequence shunt (charging) conductance, per unit of length.
    gch: ConductancePerLength  = None
 
    # Positive sequence series resistance, per unit of length.
    r: ResistancePerLength  = None
 
    # Zero sequence series resistance, per unit of length.
    r0: ResistancePerLength  = None
 
    # Positive sequence series reactance, per unit of length.
    x: ReactancePerLength  = None
 
    # Zero sequence series reactance, per unit of length.
    x0: ReactancePerLength  = None
     