#######################################################
# 
# PhaseTapChangerTable.py
# Python implementation of the Class PhaseTapChangerTable
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:10
# Original author: SELAOST1
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Wires.PhaseTapChangerTabular import PhaseTapChangerTabular
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

@dataclass
class PhaseTapChangerTable(IdentifiedObject):
    """Describes a tabular curve for how the phase angle difference and impedance
    varies with the tap step.
    """
    # The phase tap changers to which this phase tap table applies.
    phaseTapChangerTabulars: List[PhaseTapChangerTabular] = []
     