#######################################################
# 
# PhaseShuntConnectionKind.py
# Python implementation of the Class PhaseShuntConnectionKind
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:05
# Original author: kdemaree
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class PhaseShuntConnectionKind(Enum):
    """The configuration of phase connections for a single terminal device such as a
    load or capactitor.
    """
    # Delta connection.
    D = auto()
    # Wye connection.
    Y = auto()
    # Wye, with neutral brought out for grounding.
    Yn = auto()
    # Independent winding, for single-phase connections.
    I = auto()