#######################################################
# 
# Plant.py
# Python implementation of the Class Plant
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:12
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Core.EquipmentContainer import EquipmentContainer

@dataclass
class Plant(EquipmentContainer):
    """A Plant is a collection of equipment for purposes of generation.
    """
    pass
