#######################################################
# 
# RatioTapChanger.py
# Python implementation of the Class RatioTapChanger
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:22
# Original author: kdd
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.PerCent import PerCent
from TC57CIM.IEC61970.Base.Wires.TransformerControlMode import TransformerControlMode
from TC57CIM.IEC61970.Base.Wires.RatioTapChangerTable import RatioTapChangerTable
from TC57CIM.IEC61970.Base.Wires.TapChanger import TapChanger

@dataclass
class RatioTapChanger(TapChanger):
    """A tap changer that changes the voltage ratio impacting the voltage magnitude
    but not the phase angle across the transformer.
    """
    # Tap step increment, in per cent of nominal voltage, per step position.
    stepVoltageIncrement: PerCent  = None
 
    # Specifies the regulation control mode (voltage or reactive) of the
    # RatioTapChanger.
    tculControlMode: TransformerControlMode  = None
 
    # The tap ratio table for this ratio  tap changer.
    RatioTapChangerTable: Optional[RatioTapChangerTable] = None
     