#######################################################
# 
# RegulatingCondEq.py
# Python implementation of the Class RegulatingCondEq
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:26
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61970.Base.Wires.RegulatingControl import RegulatingControl
from TC57CIM.IEC61970.Base.Core.ConductingEquipment import ConductingEquipment

@dataclass
class RegulatingCondEq(ConductingEquipment):
    """A type of conducting equipment that can regulate a quantity (i.e. voltage or
    flow) at a specific point in the network.
    """
    # Specifies the regulation status of the equipment.  True is regulating, false is
    # not regulating.
    controlEnabled: Boolean  = None
 
    # The regulating control scheme in which this equipment participates.
    RegulatingControl: Optional[RegulatingControl] = None
     