#######################################################
# 
# TapChanger.py
# Python implementation of the Class TapChanger
# Generated by Enterprise Architect
# Created on:      21-May-2025 11:00:07
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61970.Base.Domain.Integer import Integer
from TC57CIM.IEC61970.Base.Domain.Seconds import Seconds
from TC57CIM.IEC61970.Base.Domain.Voltage import Voltage
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Wires.TapChangerControl import TapChangerControl
from TC57CIM.IEC61970.Base.Core.PowerSystemResource import PowerSystemResource

@dataclass
class TapChanger(PowerSystemResource):
    """Mechanism for changing transformer winding tap positions.
    """
    # Specifies the regulation status of the equipment.  True is regulating, false is
    # not regulating.
    controlEnabled: bool  = None
 
    # Highest possible tap step position, advance from neutral.
    # The attribute shall be greater than lowStep.
    highStep: int  = None
 
    # For an LTC, the delay for initial tap changer operation (first step change)
    initialDelay: Seconds  = None
 
    # Lowest possible tap step position, retard from neutral
    lowStep: int  = None
 
    # Specifies whether or not a TapChanger has load tap changing capabilities.
    ltcFlag: bool  = None
 
    # The neutral tap step position for this winding.
    # The attribute shall be equal or greater than lowStep and equal or less than
    # highStep.
    neutralStep: int  = None
 
    # Voltage at which the winding operates at the neutral tap setting.
    neutralU: Voltage  = None
 
    # The tap step position used in "normal" network operation for this winding. For
    # a "Fixed" tap changer indicates the current physical tap setting.
    # The attribute shall be equal or greater than lowStep and equal or less than
    # highStep.
    normalStep: int  = None
 
    # For an LTC, the delay for subsequent tap changer operation (second and later
    # step changes)
    subsequentDelay: Seconds  = None
 
    # Tap changer position.
    # Starting step for a steady state solution. Non integer values are allowed to
    # support continuous tap variables. The reasons for continuous value are to
    # support study cases where no discrete tap changers has yet been designed, a
    # solutions where a narrow voltage band force the tap step to oscillate or
    # accommodate for a continuous solution as input.
    # The attribute shall be equal or greater than lowStep and equal or less than
    # highStep.
    step: float  = None
 
    # The regulating control scheme in which this tap changer participates.
    tapChangerControl: Optional[TapChangerControl] = None
     