#######################################################
# 
# RemoteInputSignal.py
# Python implementation of the Class RemoteInputSignal
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:28
# Original author: ppbr003
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardInterconnections.RemoteSignalKind import RemoteSignalKind
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.PFVArControllerType1Dynamics.PFVArControllerType1Dynamics import PFVArControllerType1Dynamics
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.UnderexcitationLimiterDynamics.UnderexcitationLimiterDynamics import UnderexcitationLimiterDynamics
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.VoltageCompensatorDynamics.VoltageCompensatorDynamics import VoltageCompensatorDynamics
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.PowerSystemStabilizerDynamics.PowerSystemStabilizerDynamics import PowerSystemStabilizerDynamics
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.DiscontinuousExcitationControlDynamics.DiscontinuousExcitationControlDynamics import DiscontinuousExcitationControlDynamics
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.WindDynamics.WindTurbineType3or4Dynamics import WindTurbineType3or4Dynamics
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.WindDynamics.WindPlantDynamics import WindPlantDynamics
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.Core.IdentifiedObject import IdentifiedObject
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.Core.Terminal import Terminal

@dataclass
class RemoteInputSignal(IdentifiedObject):
    """Supports connection to a terminal associated with a remote bus from which an
    input signal of a specific type is coming.
    """
    # Type of input signal.
    remoteSignalType: RemoteSignalKind  = None
 
    # Power Factor or VAr controller Type I model using this remote input signal.
    PFVArControllerType1Dynamics: Optional[PFVArControllerType1Dynamics] = None
 
    # Underexcitation limiter model using this remote input signal.
    UnderexcitationLimiterDynamics: Optional[UnderexcitationLimiterDynamics] = None
 
    # Voltage compensator model using this remote input signal.
    VoltageCompensatorDynamics: Optional[VoltageCompensatorDynamics] = None
 
    # Power system stabilizer model using this remote input signal.
    PowerSystemStabilizerDynamics: Optional[PowerSystemStabilizerDynamics] = None
 
    # Discontinuous excitation control model using this remote input signal.
    DiscontinuousExcitationControlDynamics: Optional[DiscontinuousExcitationControlDynamics] = None
 
    # Remote input signal used by these wind turbine Type 3 or 4 models.
    WindTurbineType3or4Dynamics: Optional[WindTurbineType3or4Dynamics] = None
 
    # The remote signal with which this power plant is associated.
    WindPlantDynamics: Optional[WindPlantDynamics] = None
 
    # Remote terminal with which this input signal is associated.
    Terminal: Optional[Terminal] = None
     