#######################################################
# 
# PFVArType2IEEEPFController.py
# Python implementation of the Class PFVArType2IEEEPFController
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:16
# Original author: pcha006
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.PU import PU
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61970.Dynamics.StandardModels.PFVArControllerType2Dynamics.PFVArControllerType2Dynamics import PFVArControllerType2Dynamics

@dataclass
class PFVArType2IEEEPFController(PFVArControllerType2Dynamics):
    """The class represents IEEE PF Controller Type 2 which is a summing point type
    controller and makes up the outside loop of a two-loop system. This controller
    is implemented as a slow PI type controller. The voltage regulator forms the
    inner loop and is implemented as a fast controller.
    
      Reference: IEEE Standard 421.5-2005 Section 11.4.
    """
    # Power factor reference (<i>P</i><i><sub>FREF</sub></i>).
    pfref: PU  = None
 
    # Voltage regulator reference (<i>V</i><i><sub>REF</sub></i>).
    vref: PU  = None
 
    # Maximum output of the pf controller (<i>V</i><i><sub>CLMT</sub></i>).  Typical
    # Value = 0.1.
    vclmt: PU  = None
 
    # Proportional gain of the pf controller (<i>K</i><i><sub>P</sub></i>).  Typical
    # Value = 1.
    kp: PU  = None
 
    # Integral gain of the pf controller (<i>K</i><i><sub>I</sub></i>).  Typical
    # Value = 1.
    ki: PU  = None
 
    # Generator sensing voltage (<i>V</i><i><sub>S</sub></i>).
    vs: float  = None
 
    # Overexcitation or under excitation flag (<i>EXLON</i>)
    # true = 1 (not in the overexcitation or underexcitation state, integral action
    # is active)
    # false = 0 (in the overexcitation or underexcitation state, so integral action
    # is disabled to allow the limiter to play its role).
    exlon: bool  = None
     