#######################################################
# 
# Location.py
# Python implementation of the Class Location
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:41
# Original author: Jean-Luc
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.GeographicalLocationProfile.Core.PowerSystemResource import PowerSystemResource
from ENTSOE.CommonGridModelExchangeStandard.GeographicalLocationProfile.Common.PositionPoint import PositionPoint
from ENTSOE.CommonGridModelExchangeStandard.GeographicalLocationProfile.Core.IdentifiedObject import IdentifiedObject
from ENTSOE.CommonGridModelExchangeStandard.GeographicalLocationProfile.Common.CoordinateSystem import CoordinateSystem

@dataclass
class Location(IdentifiedObject):
    """The place, scene, or point of something where someone or something has been, is,
    and/or will be at a given moment in time. It can be defined with one or more
    postition points (coordinates) in a given coordinate system.
    """
    # All power system resources at this location.
    powerSystemResource: Optional[PowerSystemResource] = None
 
    # Sequence of position points describing this location, expressed in coordinate
    # system 'Location.CoordinateSystem'.
    positionPoints: List[PositionPoint] = []
 
    # Coordinate system used to describe position points of this location.
    coordinateSystem: Optional[CoordinateSystem] = None
     