#######################################################
# 
# PackageDependenciesCIMVersion.py
# Python implementation of the Class PackageDependenciesCIMVersion
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:00
# Original author: kdd
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Date import Date
from TC57CIM.IEC61970.Base.Domain.String import String

@dataclass
class PackageDependenciesCIMVersion:
    """The version of dependencies description among top level subpackages of the
    combined CIM model.  This is not the same as the combined packages version.
    """
    # Date of last change to the main package dependencies in format YYYY-MM-DD.
    # This is updated when the version attribute is updated.
    date: Date =  Date.2011-05-07
 
    # The version of the main subpackages of the combined CIM model.  The format is
    # simply an integer.  The version (and date) initial values should be updated any
    # time the dependencies in the model change and require an actual change to the
    # diagrams within this package.
    version: String =  String.6
     