#######################################################
# 
# ErpBOM.py
# Python implementation of the Class ErpBOM
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:46
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpDocument import ErpDocument

@dataclass
class ErpBOM(ErpDocument):
    """Information that generally describes the Bill of Material Structure and its
    contents for a utility.
    
      This is used by ERP systems to transfer Bill of Material information between
    two business applications.
    """
    pass
