#######################################################
# 
# ErpDocument.py
# Python implementation of the Class ErpDocument
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:47
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.Common.Document import Document

@dataclass
class ErpDocument(Document):
    """Shadow class for Document, to isolate subclassing from this package. If any
    subclass gets normative and needs inheritance, it will inherit directly from
    Document.
    """
    pass
