#######################################################
# 
# ErpIssueInventory.py
# Python implementation of the Class ErpIssueInventory
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:48
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.Common.Status import Status
from TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpIdentifiedObject import ErpIdentifiedObject
from TC57CIM.IEC61968.InfIEC61968.InfWork.TypeMaterial import TypeMaterial
from TC57CIM.IEC61968.InfIEC61968.InfAssets.GenericAssetModelOrMaterial import GenericAssetModelOrMaterial

@dataclass
class ErpIssueInventory(ErpIdentifiedObject):
    """Can be used to request an application to process an issue or request
    information about an issue.
    """
    status: Status  = None
 
    typeMaterial: Optional[TypeMaterial] = None
 
    genericAssetModelOrMaterial: Optional[GenericAssetModelOrMaterial] = None
     