#######################################################
# 
# ErpInvoiceKind.py
# Python implementation of the Class ErpInvoiceKind
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:47
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class ErpInvoiceKind(Enum):
    """Kind of ERP invoice.
    """
    sale = auto()
    purchase = auto()