#######################################################
# 
# ErpInvoiceLineItemKind.py
# Python implementation of the Class ErpInvoiceLineItemKind
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:47
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class ErpInvoiceLineItemKind(Enum):
    """Kind of invoice line item.
    """
    initial = auto()
    recalculation = auto()
    other = auto()