#######################################################
# 
# ErpLedBudLineItem.py
# Python implementation of the Class ErpLedBudLineItem
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:58
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.Common.Status import Status
from TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpLedgerBudget import ErpLedgerBudget
from TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpIdentifiedObject import ErpIdentifiedObject

@dataclass
class ErpLedBudLineItem(ErpIdentifiedObject):
    """Individual entry of a given Ledger Budget, typically containing information
    such as amount, accounting date, accounting period, and is associated with the
    applicable general ledger account.
    """
    status: Status  = None
 
    erpLedgerBudget: Optional[ErpLedgerBudget] = None
     