#######################################################
# 
# ErpPayable.py
# Python implementation of the Class ErpPayable
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:58
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpDocument import ErpDocument

@dataclass
class ErpPayable(ErpDocument):
    """A transaction that represents an invoice from a supplier. A payable (or
    voucher) is an open item, approved and ready for payment, in the Accounts
    Payable ledger.
    """
    pass
