#######################################################
# 
# ErpPOLineItem.py
# Python implementation of the Class ErpPOLineItem
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:49
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpPurchaseOrder import ErpPurchaseOrder
from TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpDocument import ErpDocument

@dataclass
class ErpPOLineItem(ErpDocument):
    """Of an ErpPurchaseOrder, this is an individually ordered item or product along
    with the quantity, price and other descriptive information.
    """
    ErpPurchaseOrder: Optional[ErpPurchaseOrder] = None
     