#######################################################
# 
# ErpPayableLineItem.py
# Python implementation of the Class ErpPayableLineItem
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:58
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.Common.Status import Status
from TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpPayment import ErpPayment
from TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpIdentifiedObject import ErpIdentifiedObject
from TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpPayable import ErpPayable
from TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpJournalEntry import ErpJournalEntry

@dataclass
class ErpPayableLineItem(ErpIdentifiedObject):
    """Of an ErpPayable, a line item references an ErpInvoiceLineitem or other source
    such as credit memos.
    """
    status: Status  = None
 
    erpPayments: List[ErpPayment] = []
 
    erpPayable: Optional[ErpPayable] = None
 
    erpJournalEntrys: List[ErpJournalEntry] = []
     