#######################################################
# 
# ErpPersonnel.py
# Python implementation of the Class ErpPersonnel
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:49
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.Common.Status import Status
from TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpIdentifiedObject import ErpIdentifiedObject

@dataclass
class ErpPersonnel(ErpIdentifiedObject):
    """Information that applies to the basic data about a utility person, used by ERP
    applications to transfer Personnel data for a worker.
    """
    status: Status  = None
     