#######################################################
# 
# ErpRequisition.py
# Python implementation of the Class ErpRequisition
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:00
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpDocument import ErpDocument

@dataclass
class ErpRequisition(ErpDocument):
    """General information that applies to a utility requisition that is a request for
    the purchase of goods or services. Typically, a requisition leads to the
    creation of a purchase order to a specific supplier.
    """
    pass
