#######################################################
# 
# ErpTimeSheet.py
# Python implementation of the Class ErpTimeSheet
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:51
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpDocument import ErpDocument
from TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpTimeEntry import ErpTimeEntry

@dataclass
class ErpTimeSheet(ErpDocument):
    """Time sheet for employees and contractors. Note that ErpTimeSheet inherits the
    relationship to ErpPerson from Document.
    """
    ErpTimeEntrys: List[ErpTimeEntry] = []
     