#######################################################
# 
# CurrentTransformer.py
# Python implementation of the Class CurrentTransformer
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:22
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Domain.PerCent import PerCent
from TC57CIM.IEC61970.Base.Domain.ActivePower import ActivePower
from TC57CIM.IEC61970.Base.AuxiliaryEquipment.Sensor import Sensor

@dataclass
class CurrentTransformer(Sensor):
    """Instrument transformer used to measure electrical qualities of the circuit that
    is being protected and/or monitored. Typically used as current transducer for
    the purpose of metering or protection. A typical secondary current rating would
    be 5A.
    """
    # CT accuracy classification.
    accuracyClass: String  = None
 
    # Percent of rated current for which the CT remains accurate within specified
    # limits.
    accuracyLimit: PerCent  = None
 
    # CT classification; i.e. class 10P.
    ctClass: String  = None
 
    # Intended usage of the CT; i.e. metering, protection.
    usage: String  = None
 
    # Power burden of the CT core.
    coreBurden: ActivePower  = None
     