#######################################################
# 
# PotentialTransformer.py
# Python implementation of the Class PotentialTransformer
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:13
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.AuxiliaryEquipment.PotentialTransformerKind import PotentialTransformerKind
from TC57CIM.IEC61970.Base.AuxiliaryEquipment.Sensor import Sensor

@dataclass
class PotentialTransformer(Sensor):
    """Instrument transformer (also known as Voltage Transformer) used to measure
    electrical qualities of the circuit that is being protected and/or monitored.
    Typically used as voltage transducer for the purpose of metering, protection,
    or sometimes auxiliary substation supply. A typical secondary voltage rating
    would be 120V.
    """
    # PT accuracy classification.
    accuracyClass: String  = None
 
    # Nominal ratio between the primary and secondary voltage.
    nominalRatio: Float  = None
 
    # Potential transformer (PT) classification covering burden.
    ptClass: String  = None
 
    # Potential transformer construction type.
    type: PotentialTransformerKind  = None
     