#######################################################
# 
# RemoteSignalKind.py
# Python implementation of the Class RemoteSignalKind
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:40
# Original author: ppbr003
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class RemoteSignalKind(Enum):
    """Type of input signal coming from remote bus.
    """
    # Input is voltage frequency from remote terminal bus.
    remoteBusVoltageFrequency = auto()
    # Input is voltage frequency deviation from remote terminal bus.
    remoteBusVoltageFrequencyDeviation = auto()
    # Input is frequency from remote terminal bus.
    remoteBusFrequency = auto()
    # Input is frequency deviation from remote terminal bus.
    remoteBusFrequencyDeviation = auto()
    # Input is voltage amplitude from remote terminal bus.
    remoteBusVoltageAmplitude = auto()
    # Input is voltage from remote terminal bus.
    remoteBusVoltage = auto()
    # Input is branch current amplitude from remote terminal bus.
    remoteBranchCurrentAmplitude = auto()
    # Input is branch current amplitude derivative from remote terminal bus.
    remoteBusVoltageAmplitudeDerivative = auto()
    # Input is PU voltage derivative from remote terminal bus.
    remotePuBusVoltageDerivative = auto()