#######################################################
# 
# DynamicsFunctionBlock.py
# Python implementation of the Class DynamicsFunctionBlock
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:37
# Original author: ppbr003
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Boolean import Boolean
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.Core.IdentifiedObject import IdentifiedObject

@dataclass
class DynamicsFunctionBlock(IdentifiedObject):
    """Abstract parent class for all Dynamics function blocks.
    """
    # Function block used indicator.
    # true = use of function block is enabled
    # false = use of function block is disabled.
    enabled: Boolean  = None
     