#######################################################
# 
# RotatingMachineDynamics.py
# Python implementation of the Class RotatingMachineDynamics
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:38
# Original author: ppbr003
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Simple_Float import Simple_Float
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Seconds import Seconds
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.PU import PU
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.DynamicsFunctionBlock import DynamicsFunctionBlock

@dataclass
class RotatingMachineDynamics(DynamicsFunctionBlock):
    """Abstract parent class for all synchronous and asynchronous machine standard
    models.
    """
    # Damping torque coefficient (D).  A proportionality constant that, when
    # multiplied by the angular velocity of the rotor poles with respect to the
    # magnetic field (frequency), results in the damping torque.  This value is often
    # zero when the sources of damping torques (generator damper windings, load
    # damping effects, etc.) are modelled in detail.  Typical Value = 0.
    damping: Simple_Float  = None
 
    # Inertia constant of generator or motor and mechanical load (H) (>0).  This is
    # the specification for the stored energy in the rotating mass when operating at
    # rated speed.  For a generator, this includes the generator plus all other
    # elements (turbine, exciter) on the same shaft and has units of MW*sec.  For a
    # motor, it includes the motor plus its mechanical load. Conventional units are
    # per unit on the generator MVA base, usually expressed as MW*second/MVA or just
    # second.   This value is used in the accelerating power reference frame for
    # operator training simulator solutions.  Typical Value = 3.
    inertia: Seconds  = None
 
    # Saturation factor at rated terminal voltage (S1) (> or =0).  Not used by
    # simplified model.  Defined by defined by S(E1) in the
    # SynchronousMachineSaturationParameters diagram.  Typical Value = 0.02.
    saturationFactor: Simple_Float  = None
 
    # Saturation factor at 120% of rated terminal voltage (S12) (> or =S1). Not used
    # by the simplified model, defined by S(E2) in the
    # SynchronousMachineSaturationParameters diagram.  Typical Value = 0.12.
    saturationFactor120: Simple_Float  = None
 
    # Stator leakage reactance (Xl) (> or =0). Typical Value = 0.15.
    statorLeakageReactance: PU  = None
 
    # Stator (armature) resistance (Rs) (> or =0). Typical Value = 0.005.
    statorResistance: PU  = None
     