#######################################################
# 
# ControlAreaGeneratingUnit.py
# Python implementation of the Class ControlAreaGeneratingUnit
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:16
# Original author: kdd
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.ControlArea.AltGeneratingUnitMeas import AltGeneratingUnitMeas
from TC57CIM.IEC61970.Base.Generation.Production.GeneratingUnit import GeneratingUnit
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

@dataclass
class ControlAreaGeneratingUnit(IdentifiedObject):
    """A control area generating unit. This class is needed so that alternate control
    area definitions may include the same generating unit.   Note only one instance
    within a control area should reference a specific generating unit.
    """
    # The link to prioritized measurements for this GeneratingUnit.
    altGeneratingUnitMeass: List[AltGeneratingUnitMeas] = []
 
    # The generating unit specified for this control area.  Note that a control area
    # should include a GeneratingUnit only once.
    generatingUnit: Optional[GeneratingUnit] = None
     