#######################################################
# 
# AssetModelCatalogueItem.py
# Python implementation of the Class AssetModelCatalogueItem
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:47:54
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Money import Money
from TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpQuoteLineItem import ErpQuoteLineItem
from TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpPOLineItem import ErpPOLineItem
from TC57CIM.IEC61968.Common.Document import Document
from TC57CIM.IEC61968.InfIEC61968.InfAssetInfo.AssetModelCatalogue import AssetModelCatalogue

@dataclass
class AssetModelCatalogueItem(Document):
    """Provides pricing and other relevant information about a specific manufacturer's
    product (i.e., AssetModel), and its price from a given supplier. A single
    AssetModel may be availble from multiple suppliers. Note that manufacturer and
    supplier are both types of organisation, which the association is inherited
    from Document.
    """
    # Unit cost for an asset model from a specific supplier, either for a unit cost
    # or cost per unit length. Cost is for material or asset only and does not
    # include labor to install/construct or configure it.
    unitCost: Money  = None
 
    erpQuoteLineItems: List[ErpQuoteLineItem] = []
 
    erpPOLineItems: List[ErpPOLineItem] = []
 
    assetModelCatalogue: Optional[AssetModelCatalogue] = None
     