#######################################################
# 
# CompositeSwitchInfo.py
# Python implementation of the Class CompositeSwitchInfo
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:10
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61968.InfIEC61968.InfAssetInfo.CompositeSwitchKind import CompositeSwitchKind
from TC57CIM.IEC61970.Base.Domain.Integer import Integer
from TC57CIM.IEC61970.Base.Domain.CurrentFlow import CurrentFlow
from TC57CIM.IEC61970.Base.Domain.Voltage import Voltage
from TC57CIM.IEC61970.Base.Core.PhaseCode import PhaseCode
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61968.Assets.AssetInfo import AssetInfo

@dataclass
class CompositeSwitchInfo(AssetInfo):
    """Properties of a composite switch.
    """
    # Initial operating mode, with the following values: Automatic, Manual.
    initOpMode: String  = None
 
    # Kind of composite switch.
    kind: CompositeSwitchKind  = None
 
    # Number of switch states represented by the composite switch.
    switchStateCount: Integer  = None
 
    # Breaking capacity, or short circuit rating, is the maximum rated current which
    # the device can safely interrupt at the rated voltage.
    interruptingRating: CurrentFlow  = None
 
    # Rated voltage.
    ratedVoltage: Voltage  = None
 
    # Phases carried, if applicable.
    phaseCode: PhaseCode  = None
 
    # Supported number of phases, typically 0, 1 or 3.
    phaseCount: Integer  = None
 
    # True if device is capable of being operated by remote control.
    remote: Boolean  = None
 
    # True if multi-phase switch controls all phases concurrently.
    ganged: Boolean  = None
     