#######################################################
# 
# OldTransformerEndInfo.py
# Python implementation of the Class OldTransformerEndInfo
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:06
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.InfIEC61968.InfAssetInfo.WindingInsulationKind import WindingInsulationKind
from TC57CIM.IEC61970.Base.Domain.Weight import Weight
from TC57CIM.IEC61970.Base.Domain.ApparentPower import ApparentPower
from TC57CIM.IEC61968.AssetInfo.TransformerEndInfo import TransformerEndInfo

@dataclass
class OldTransformerEndInfo(TransformerEndInfo):
    # Type of insultation used for transformer windings.
    windingInsulationKind: WindingInsulationKind  = None
 
    # Weight of solid insultation in transformer.
    solidInsulationWeight: Weight  = None
 
    # Overload rating for 1 hour.
    hourOverLoadRating: ApparentPower  = None
 
    # Overload rating for 24 hours.
    dayOverLoadRating: ApparentPower  = None
     