#######################################################
# 
# PotentialTransformerInfo.py
# Python implementation of the Class PotentialTransformerInfo
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:13
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Voltage import Voltage
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61968.InfIEC61968.InfCommon.Ratio import Ratio
from TC57CIM.IEC61968.Assets.AssetInfo import AssetInfo

@dataclass
class PotentialTransformerInfo(AssetInfo):
    """Properties of potential transformer asset.
    """
    # Rated voltage on the primary side.
    ratedVoltage: Voltage  = None
 
    accuracyClass: String  = None
 
    ptClass: String  = None
 
    nominalRatio: Ratio  = None
 
    # Ratio for the primary winding tap changer.
    primaryRatio: Ratio  = None
 
    # Ratio for the secondary winding tap changer.
    secondaryRatio: Ratio  = None
 
    # Ratio for the tertiary winding tap changer.
    tertiaryRatio: Ratio  = None
     