#######################################################
# 
# RecloserInfo.py
# Python implementation of the Class RecloserInfo
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:35
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.CurrentFlow import CurrentFlow
from TC57CIM.IEC61970.Base.Domain.Integer import Integer
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61968.InfIEC61968.InfAssetInfo.OldSwitchInfo import OldSwitchInfo

@dataclass
class RecloserInfo(OldSwitchInfo):
    """Properties of recloser assets.
    """
    # Phase trip rating.
    phaseTripRating: CurrentFlow  = None
 
    # Total number of phase reclose operations.
    recloseLockoutCount: int  = None
 
    # True if device has ground trip capability.
    groundTripCapable: bool  = None
 
    # True if normal status of ground trip is enabled.
    groundTripNormalEnabled: bool  = None
 
    # Ground trip rating.
    groundTripRating: CurrentFlow  = None
     