#######################################################
# 
# CommodityKind.py
# Python implementation of the Class CommodityKind
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:10
# Original author: Marty
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class CommodityKind(Enum):
    # Not Applicable
    none = auto()
    # All types of metered quantities. This type of reading comes from the meter and
    # represents a “secondary” metered value.
    electricitySecondaryMetered = auto()
    # It is possible for a meter to be outfitted with an external VT and/or CT. The
    # meter might not be aware of these devices, and the display not compensate for
    # their presence. Ultimately, when these scalars are applied, the value that
    # represents the service value is called the “primary metered” value. The “index”
    # in sub-category 3 mirrors those of sub-category 0.
    electricityPrimaryMetered = auto()
    # A measurement of the communication infrastructure itself.
    communication = auto()
    air = auto()
    # (SF<sub>6</sub> is found separately below.)
    insulativeGas = auto()
    insulativeOil = auto()
    naturalGas = auto()
    propane = auto()
    # Drinkable water
    potableWater = auto()
    # Water in steam form, usually used for heating.
    steam = auto()
    # (Sewerage)
    wasteWater = auto()
    # This fluid is likely in liquid form. It is not necessarily water or water based.
    # The warm fluid returns cooler than when it was sent. The heat conveyed may be
    # metered.
    heatingFluid = auto()
    # The cool fluid returns warmer than when it was sent. The heat conveyed may be
    # metered.
    coolingFluid = auto()
    # Reclaimed water – possibly used for irrigation but not sufficiently treated to
    # be considered safe for drinking.
    nonpotableWater = auto()
    # Nitrous Oxides NO<sub>X</sub>
    nox = auto()
    # Sulfur Dioxide SO<sub>2</sub>
    so2 = auto()
    # Methane CH<sub>4</sub>
    ch4 = auto()
    # Carbon Dioxide CO<sub>2</sub>
    co2 = auto()
    carbon = auto()
    # Hexachlorocyclohexane HCH
    hch = auto()
    # Perfluorocarbons PFC
    pfc = auto()
    # Sulfurhexafluoride SF<sub>6</sub>
    sf6 = auto()
    # Television
    tvLicence = auto()
    # Internet service
    internet = auto()
    # trash
    refuse = auto()