#######################################################
# 
# CurtailmentProfile.py
# Python implementation of the Class CurtailmentProfile
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:22
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC62325.MarketOperations.MarketSystem.ExternalInputs.Profile import Profile

@dataclass
class CurtailmentProfile(Profile):
    """Curtailing entity must be providing at least one service to the
    EnergyTransaction. The CurtailmentProfile must be completely contained within
    the EnergyProfile timeframe for this EnergyTransaction.
    """
    pass
