#######################################################
# 
# TieLine.py
# Python implementation of the Class TieLine
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:51:03
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC62325.MarketOperations.ReferenceData.SubControlArea import SubControlArea

@dataclass
class TieLine(IdentifiedObject):
    # The SubControlArea is on the A side of a collection of metered points which
    # define the SubControlArea's boundary for a ControlAreaOperator or
    # CustomerConsumer.
    subControlArea: Optional[SubControlArea] = None
 
    # The SubControlArea is on the B side of a collection of metered points which
    # define the SubControlArea's boundary for a ControlAreaOperator or
    # CustomerConsumer.
    subControlArea: Optional[SubControlArea] = None
     