#######################################################
# 
# TransmissionRightOfWay.py
# Python implementation of the Class TransmissionRightOfWay
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:41:05
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Core.PowerSystemResource import PowerSystemResource

@dataclass
class TransmissionRightOfWay(PowerSystemResource):
    """A collection of transmission lines that are close proximity to each other.
    """
    pass
