#######################################################
# 
# GateLogicKind.py
# Python implementation of the Class GateLogicKind
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:11
# Original author: sveinols
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class GateLogicKind(Enum):
    """Define the different logical operations.
    """
    # A logical AND operation. True when all input are true.
    and = auto()
    # A logical OR operation. True when one or more input are true.
    or = auto()
    # A logical NOR operation. False when one or more input are true.
    nor = auto()
    # A logical NAND operation. False when all input are true.
    nand = auto()
    # A logical NOT operation. Only one input and true input will give false out and
    # false in will give true out. An inverter.
    not = auto()
    # A logical XNOR operation. The function is the inverse of the exclusive OR (XOR)
    # gate. All input false or true will give true. Otherwise false.
    xnor = auto()
    # A logical XOR operation.  All input false or true will give false. Otherwise
    # true.
    xor = auto()