#######################################################
# 
# PinEquipmentKind.py
# Python implementation of the Class PinEquipmentKind
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:11
# Original author: sveinols
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class PinEquipmentKind(Enum):
    """Categorisation of type of compare done on Equipment.
    """
    # Check if equipment is in service, True if in service otherwise false.
    inService = auto()
    # Compare load flow result against rated current on the equipment (switch).
    ratedCurrent = auto()
    # Compare load flow result against the active voltage limit for the equipment.
    voltageLimit = auto()
    # Compare load flow result against the active current limit for the equipment.
    currentLimit = auto()
    # Compare load flow result against the active limit for active power for the
    # given equipment.
    activePowerLimit = auto()
    # Compare load flow result against the active limit for apparent power for the
    # given equipment.
    apparentPowerLimit = auto()
    # Check if all terminal on the equipment is connected.
    connected = auto()