#######################################################
# 
# ProtectiveActionEquipment.py
# Python implementation of the Class ProtectiveActionEquipment
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:21
# Original author: sveinols
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61970.Base.Core.Equipment import Equipment
from TC57CIM.IEC61970.InfIEC61970.InfSIPS.ProtectiveAction import ProtectiveAction

@dataclass
class ProtectiveActionEquipment(ProtectiveAction):
    """Protective action to put an Equipment in-service/out-of-service.
    """
    # If true the equipment is put in-service, otherwise out-of-service.
    inService: Boolean  = None
 
    equipment: Optional[Equipment] = None
     