#######################################################
# 
# TriggerCondition.py
# Python implementation of the Class TriggerCondition
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:51:11
# Original author: sveinols
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC61970.InfIEC61970.InfSIPS.RemedialActionScheme import RemedialActionScheme
from TC57CIM.IEC61970.InfIEC61970.InfSIPS.Gate import Gate

@dataclass
class TriggerCondition(IdentifiedObject):
    """A conditions that can trigger remedial actions.
    """
    remedialActionScheme: Optional[RemedialActionScheme] = None
 
    gate: Optional[Gate] = None
     