#######################################################
# 
# DefaultBidCurveData.py
# Python implementation of the Class DefaultBidCurveData
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:31
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC62325.MarketOperations.MktDomain.BidCalculationBasis import BidCalculationBasis
from TC57CIM.IEC61970.Base.Core.CurveData import CurveData

@dataclass
class DefaultBidCurveData(CurveData):
    """Curve data for default bid curve and startup cost curve.
    """
    # Type of calculation basis used to define the default bid segment curve.
    bidSegmentCalcType: BidCalculationBasis  = None
     