#######################################################
# 
# DiscreteMeasurementValueQuality.py
# Python implementation of the Class DiscreteMeasurementValueQuality
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:43
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61970.Base.Meas.MeasurementValueQuality import MeasurementValueQuality
from TC57CIM.IEC62325.MarketOperations.MarketSystem.ExternalInputs.MktDiscreteValue import MktDiscreteValue

@dataclass
class DiscreteMeasurementValueQuality(MeasurementValueQuality):
    """Measurement quality flags for Discrete Values.
    """
    # Switch Manual Replace Indicator. Flag indicating that the switch is manual
    # replace.
    manualReplaceIndicator: bool  = None
 
    # Removed From Operation Indicator. Flag indicating that the switch is removed
    # from operation.
    removeFromOperationIndicator: bool  = None
 
    mktDiscreteValue: Optional[MktDiscreteValue] = None
     