#######################################################
# 
# GeneratingUnitDynamicValues.py
# Python implementation of the Class GeneratingUnitDynamicValues
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:21
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC62325.MarketOperations.ReferenceData.Flowgate import Flowgate
from TC57CIM.IEC62325.MarketOperations.MarketOpCommon.MktGeneratingUnit import MktGeneratingUnit

@dataclass
class GeneratingUnitDynamicValues:
    """Optimal Power Flow or State Estimator Unit Data for Operator Training Simulator.
    This is used for RealTime, Study and Maintenance Users
    """
    # Loss Factor
    lossFactor: float  = None
 
    # The maximum active power generation of the unit in MW
    maximumMW: float  = None
 
    # The minimum active power generation of the unit in MW
    minimumMW: float  = None
 
    # Unit reactive power generation in MVAR
    mVAR: float  = None
 
    # Unit active power generation in MW
    mw: float  = None
 
    # Unit sencivity factor. The distribution factors (DFAX) for the unit
    sensitivity: float  = None
 
    flowgate: Optional[Flowgate] = None
 
    mktGeneratingUnit: Optional[MktGeneratingUnit] = None
     