#######################################################
# 
# InterchangeSchedule.py
# Python implementation of the Class InterchangeSchedule
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:40
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC62325.MarketOperations.MktDomain.CheckOutType import CheckOutType
from TC57CIM.IEC62325.MarketOperations.MktDomain.InterTieDirection import InterTieDirection
from TC57CIM.IEC62325.MarketOperations.MktDomain.MarketProductType import MarketProductType
from TC57CIM.IEC61970.Base.Domain.Integer import Integer
from TC57CIM.IEC62325.MarketOperations.MktDomain.MarketType import MarketType
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC62325.MarketOperations.MktDomain.EnergyProductType import EnergyProductType
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC62325.MarketOperations.ReferenceData.SchedulingPoint import SchedulingPoint
from TC57CIM.IEC62325.MarketOperations.ReferenceData.RegisteredInterTie import RegisteredInterTie
from TC57CIM.IEC62325.MarketOperations.MarketSystem.ExternalInputs.InterchangeETCData import InterchangeETCData
from TC57CIM.IEC61970.Base.Core.Curve import Curve

@dataclass
class InterchangeSchedule(Curve):
    """Interchange schedule class to hold information for interchange schedules such
    as import export type, energy type, and etc.
    """
    # To indicate a check out type such as adjusted capacity or dispatch capacity.
    checkOutType: CheckOutType  = None
 
    # Import or export.
    directionType: InterTieDirection  = None
 
    # Energy product type.
    energyType: MarketProductType  = None
 
    # Interval length.
    intervalLength: int  = None
 
    # Market type.
    marketType: MarketType  = None
 
    # Operating date, hour.
    operatingDate: DateTime  = None
 
    # To indicate an out-of-market (OOM) schedule.
    outOfMarketType: bool  = None
 
    # Schedule type.
    scheduleType: EnergyProductType  = None
 
    # Wheeling Counter-Resource ID (required when Schedule Type=Wheel).
    wcrID: str  = None
 
    schedulingPoint: Optional[SchedulingPoint] = None
 
    registeredInterTie: Optional[RegisteredInterTie] = None
 
    interchangeETCDatas: List[InterchangeETCData] = []
     