#######################################################
# 
# LoadDistributionFactor.py
# Python implementation of the Class LoadDistributionFactor
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:46
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float

@dataclass
class LoadDistributionFactor:
    """This class models the load distribution factors. This class should be used in
    one of two ways:
    
      Use it along with the AggregatedPnode and the IndividualPnode to show the
    distriubtion of each individual party
    
      OR
    
      Use it with Mkt_EnergyConsumer to represent the current MW/Mvar distribution
    within it's parnet load group.
    """
    # Real power (MW) load distribution factor
    pDistFactor: float  = None
 
    # Reactive power (MVAr) load distribution factor
    qDistFactor: float  = None
     