#######################################################
# 
# MktACLineSegment.py
# Python implementation of the Class MktACLineSegment
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:50
# Original author: mspivbe2
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Wires.ACLineSegment import ACLineSegment

@dataclass
class MktACLineSegment(ACLineSegment):
    """Subclass of IEC61970:Wires:ACLineSegment
    """
    pass
