#######################################################
# 
# ServicePoint.py
# Python implementation of the Class ServicePoint
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:51
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC62325.MarketOperations.MarketSystem.ExternalInputs.TransmissionPath import TransmissionPath
from TC57CIM.IEC62325.MarketOperations.MarketSystem.ExternalInputs.TransmissionReservation import TransmissionReservation

@dataclass
class ServicePoint(IdentifiedObject):
    """The defined termination points of a transmission path (down to distribution
    level or to a customer - generation or consumption or both). Service points are
    defined from the viewpoint of the transmission service. Each service point is
    contained within (or on the boundary of) an interchange area. A service point
    is source or destination of a transaction.
    """
    # A transmission path has a "point-of-receipt" service point
    transmissionPaths: List[TransmissionPath] = []
 
    # A transmission path has a "point-of-delivery" service point
    transmissionPaths: List[TransmissionPath] = []
 
    transmissionReservations: List[TransmissionReservation] = []
 
    transmissionReservations: List[TransmissionReservation] = []
     