#######################################################
# 
# TransmissionReservation.py
# Python implementation of the Class TransmissionReservation
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:41:05
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC62325.MarketOperations.ParticipantInterfaces.TransactionBid import TransactionBid
from TC57CIM.IEC62325.MarketOperations.MarketSystem.ExternalInputs.EnergyTransaction import EnergyTransaction

@dataclass
class TransmissionReservation:
    """A transmission reservation is obtained from the OASIS system to reserve
    transmission for a specified time period, transmission path and transmission
    product.
    """
    TransactionBid: Optional[TransactionBid] = None
 
    EnergyTransaction: Optional[EnergyTransaction] = None
     