#######################################################
# 
# TransferInterfaceSolution.py
# Python implementation of the Class TransferInterfaceSolution
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:51:07
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC62325.MarketOperations.ReferenceData.MktContingency import MktContingency
from TC57CIM.IEC62325.MarketOperations.MarketSystem.ExternalInputs.TransferInterface import TransferInterface

@dataclass
class TransferInterfaceSolution:
    """TNA Interface Definitions from OPF for VSA
    """
    # The margin for the interface
    interfaceMargin: Float  = None
 
    # Transfer Interface + Limit
    # Attribute Usage: The absoloute of the maximum flow on the transfer interface.
    # This is a positive MW value.
    transferLimit: Float  = None
 
    # Post Transfer MW for step
    postTransferMW: Float  = None
 
    mktContingency: Optional[MktContingency] = None
 
    mktContingency: Optional[MktContingency] = None
 
    transferInterface: Optional[TransferInterface] = None
     