#######################################################
# 
# GenerationProvider.py
# Python implementation of the Class GenerationProvider
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:21
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.Common.Organisation import Organisation

@dataclass
class GenerationProvider(Organisation):
    """The energy seller in the energy marketplace.
    """
    pass
