#######################################################
# 
# Marketer.py
# Python implementation of the Class Marketer
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:43
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.Common.Organisation import Organisation

@dataclass
class Marketer(Organisation):
    """Matches buyers and sellers, and secures transmission (and other ancillary
    services) needed to complete the energy transaction.
    """
    pass
