#######################################################
# 
# TransmissionProduct.py
# Python implementation of the Class TransmissionProduct
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:51:10
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC62325.InfIEC62325.InfFinancial.TransmissionProvider import TransmissionProvider
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC62325.MarketOperations.MarketSystem.ExternalInputs.TransmissionPath import TransmissionPath

@dataclass
class TransmissionProduct(IdentifiedObject):
    # Type of the transmission product. This could be a transmission service class
    # (firm, total transmission capability, or non-firm), transmission service period
    # (on-peak, full-period, off-peak), transmission service increments (yearly
    # extended, hourly fixed, monthly sliding, etc.), transmission service type
    # (network, available transmission capability, or point-to-point, or a
    # transmission service window (fixed hourly, sliding weekly, extended monthly,
    # etc.).
    transmissionProductType: String  = None
 
    # A TransmissionProvider offers a TransmissionProduct.
    transmissionProvider: Optional[TransmissionProvider] = None
 
    # A transmission product is located on a transmission path.
    transmissionPaths: List[TransmissionPath] = []
     