#######################################################
# 
# OperationalLimitType.py
# Python implementation of the Class OperationalLimitType
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:00
# Original author: andre
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Seconds import Seconds
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.OperationalLimits.LimitTypeKind import LimitTypeKind
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.OperationalLimits.OperationalLimitDirectionKind import OperationalLimitDirectionKind
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.Core.IdentifiedObject import IdentifiedObject

@dataclass
class OperationalLimitType(IdentifiedObject):
    """The operational meaning of a category of limits.
    """
    # The nominal acceptable duration of the limit.  Limits are commonly expressed in
    # terms of the a time limit for which the limit is normally acceptable.   The
    # actual acceptable duration of a specific limit may depend on other local
    # factors such as temperature or wind speed.
    acceptableDuration: Seconds  = None
 
    # Types of limits defined in the ENTSO-E Operational Handbook Policy 3.
    limitType: LimitTypeKind  = None
 
    # The direction of the limit.
    direction: OperationalLimitDirectionKind  = None
     