#######################################################
# 
# MarketLedger.py
# Python implementation of the Class MarketLedger
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:44
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC62325.MarketOperations.MarketOpCommon.MarketLedgerEntry import MarketLedgerEntry

@dataclass
class MarketLedger:
    """In accounting transactions, a ledger is a book containing accounts to which
    debits and credits are posted from journals, where transactions are initially
    recorded. Journal entries are periodically posted to the ledger. Ledger Actual
    represents actual amounts by account within ledger within company or business
    area. Actual amounts may be generated in a source application and then loaded
    to a specific ledger within the enterprise general ledger or budget application.
    """
    marketLedgerEntrys: List[MarketLedgerEntry] = []
     