#######################################################
# 
# MarketInvoiceLineItem.py
# Python implementation of the Class MarketInvoiceLineItem
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:51
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.DateTimeInterval import DateTimeInterval
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC62325.MarketOperations.MktDomain.MktInvoiceLineItemKind import MktInvoiceLineItemKind
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC62325.MarketOperations.MarketSystem.MarketResults.Settlement import Settlement
from TC57CIM.IEC62325.MarketOperations.MarketOpCommon.MarketInvoice import MarketInvoice

@dataclass
class MarketInvoiceLineItem:
    """An individual line item on an invoice.
    """
    # Bill period for the line item.
    billPeriod: DateTimeInterval  = None
 
    # General Ledger account code, shall be a valid combination.
    glAccount: str  = None
 
    # Date and time line item will be posted to the General Ledger. 
    glDateTime: DateTime  = None
 
    # Kind of line item.
    kind: MktInvoiceLineItemKind  = None
 
    # Amount due for this line item.
    lineAmount: float  = None
 
    # Line item number on invoice statement.
    lineNumber: str  = None
 
    # Version number of the bill run.
    lineVersion: str  = None
 
    # Net line item charge amount.
    netAmount: float  = None
 
    # Previous line item charge amount. 
    previousAmount: float  = None
 
    settlements: List[Settlement] = []
 
    marketInvoiceLineItem: Optional[MarketInvoiceLineItem] = None
 
    marketInvoice: Optional[MarketInvoice] = None
     