#######################################################
# 
# MktActivityRecord.py
# Python implementation of the Class MktActivityRecord
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:46
# Original author: mspivbe2
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.Common.ActivityRecord import ActivityRecord

@dataclass
class MktActivityRecord(ActivityRecord):
    """Subclass of IEC61968: Common:ActivityRecord
    """
    pass
