#######################################################
# 
# MktEnergyConsumer.py
# Python implementation of the Class MktEnergyConsumer
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:51
# Original author: mspivbe2
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Wires.EnergyConsumer import EnergyConsumer

@dataclass
class MktEnergyConsumer(EnergyConsumer):
    """Subclass of IEC61970:Wires:EnergyConsumer
    """
    pass
