#######################################################
# 
# MktTerminal.py
# Python implementation of the Class MktTerminal
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:00
# Original author: mspivbe2
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC62325.MarketOperations.ReferenceData.Flowgate import Flowgate
from TC57CIM.IEC61970.Base.Core.Terminal import Terminal

@dataclass
class MktTerminal(Terminal):
    """Subclass of IEC61970:Core:Terminal
    """
    # This is the begin date/time of the element eligibility for the flowgate.
    startEffectiveDate: DateTime  = None
 
    # This is the end date/time of the element eligibility for the flowgate.
    endEffectiveDate: DateTime  = None
 
    flowgate: Optional[Flowgate] = None
     