#######################################################
# 
# BWRSteamSupply.py
# Python implementation of the Class BWRSteamSupply
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:03
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.PU import PU
from TC57CIM.IEC61970.Base.Domain.Seconds import Seconds
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Generation.GenerationTrainingSimulation.SteamSupply import SteamSupply

@dataclass
class BWRSteamSupply(SteamSupply):
    """Boiling water reactor used as a steam supply to a steam turbine.
    """
    # High power limit.
    highPowerLimit: PU  = None
 
    # In-core thermal time constant.
    inCoreThermalTC: Seconds  = None
 
    # Integral gain.
    integralGain: Float  = None
 
    # Initial lower limit.
    lowerLimit: PU  = None
 
    # Low power limit.
    lowPowerLimit: PU  = None
 
    # Pressure limit.
    pressureLimit: PU  = None
 
    # Pressure setpoint gain adjuster.
    pressureSetpointGA: Float  = None
 
    # Pressure setpoint time constant.
    pressureSetpointTC1: Seconds  = None
 
    # Pressure setpoint time constant.
    pressureSetpointTC2: Seconds  = None
 
    # Proportional gain.
    proportionalGain: Float  = None
 
    # Coefficient for modeling the effect of off-nominal frequency and voltage on
    # recirculation and core flow, which affects the BWR power output.
    rfAux1: PU  = None
 
    # Coefficient for modeling the effect of off-nominal frequency and voltage on
    # recirculation and core flow, which affects the BWR power output.
    rfAux2: PU  = None
 
    # Coefficient for modeling the effect of off-nominal frequency and voltage on
    # recirculation and core flow, which affects the BWR power output.
    rfAux3: PU  = None
 
    # Coefficient for modeling the effect of off-nominal frequency and voltage on
    # recirculation and core flow, which affects the BWR power output.
    rfAux4: PU  = None
 
    # Coefficient for modeling the effect of off-nominal frequency and voltage on
    # recirculation and core flow, which affects the BWR power output.
    rfAux5: PU  = None
 
    # Coefficient for modeling the effect of off-nominal frequency and voltage on
    # recirculation and core flow, which affects the BWR power output.
    rfAux6: PU  = None
 
    # Coefficient for modeling the effect of off-nominal frequency and voltage on
    # recirculation and core flow, which affects the BWR power output.
    rfAux7: PU  = None
 
    # Coefficient for modeling the effect of off-nominal frequency and voltage on
    # recirculation and core flow, which affects the BWR power output.
    rfAux8: PU  = None
 
    # Rod pattern.
    rodPattern: PU  = None
 
    # Constant associated with rod pattern.
    rodPatternConstant: Float  = None
 
    # Initial upper limit.
    upperLimit: PU  = None
     