#######################################################
# 
# CombustionTurbine.py
# Python implementation of the Class CombustionTurbine
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:09
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Temperature import Temperature
from TC57CIM.IEC61970.Base.Domain.PU import PU
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61970.Base.Domain.Seconds import Seconds
from TC57CIM.IEC61970.Base.Generation.Production.AirCompressor import AirCompressor
from TC57CIM.IEC61970.Base.Generation.GenerationTrainingSimulation.PrimeMover import PrimeMover
from TC57CIM.IEC61970.Base.Generation.GenerationTrainingSimulation.CTTempActivePowerCurve import CTTempActivePowerCurve

@dataclass
class CombustionTurbine(PrimeMover):
    """A prime mover that is typically fueled by gas or light oil.
    """
    # Default ambient temperature to be used in modeling applications.
    ambientTemp: Temperature  = None
 
    # Off-nominal frequency effect on turbine auxiliaries. Per unit reduction in
    # auxiliary active power consumption versus per unit reduction in frequency (from
    # rated frequency).
    auxPowerVersusFrequency: PU  = None
 
    # Off-nominal voltage effect on turbine auxiliaries. Per unit reduction in
    # auxiliary active power consumption versus per unit reduction in auxiliary bus
    # voltage (from a specified voltage level).
    auxPowerVersusVoltage: PU  = None
 
    # Off-nominal frequency effect on turbine capability. Per unit reduction in unit
    # active power capability versus per unit reduction in frequency (from rated
    # frequency).
    capabilityVersusFrequency: PU  = None
 
    # Flag that is set to true if the combustion turbine is associated with a heat
    # recovery boiler.
    heatRecoveryFlag: Boolean  = None
 
    # Per unit change in power per (versus) unit change in ambient temperature.
    powerVariationByTemp: PU  = None
 
    # Reference temperature at which the output of the turbine was defined.
    referenceTemp: Temperature  = None
 
    # The time constant for the turbine.
    timeConstant: Seconds  = None
 
    # A CAES air compressor is driven by combustion turbine.
    AirCompressor: Optional[AirCompressor] = None
 
    # A combustion turbine may have an active power versus ambient temperature
    # relationship.
    CTTempActivePowerCurve: Optional[CTTempActivePowerCurve] = None
     