#######################################################
# 
# CTTempActivePowerCurve.py
# Python implementation of the Class CTTempActivePowerCurve
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:28
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Core.Curve import Curve

@dataclass
class CTTempActivePowerCurve(Curve):
    """Relationship between the combustion turbine's power output rating in gross
    active power (X-axis) and the ambient air temperature (Y-axis).
    """
    pass
