#######################################################
# 
# DrumBoiler.py
# Python implementation of the Class DrumBoiler
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:37
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Generation.GenerationTrainingSimulation.FossilSteamSupply import FossilSteamSupply

@dataclass
class DrumBoiler(FossilSteamSupply):
    """Drum boiler.
    """
    # Rating of drum boiler in steam units.
    drumBoilerRating: Float  = None
     