#######################################################
# 
# SteamSupply.py
# Python implementation of the Class SteamSupply
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:57
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Generation.GenerationTrainingSimulation.SteamTurbine import SteamTurbine
from TC57CIM.IEC61970.Base.Core.PowerSystemResource import PowerSystemResource

@dataclass
class SteamSupply(PowerSystemResource):
    """Steam supply for steam turbine.
    """
    # Rating of steam supply.
    steamSupplyRating: float  = None
 
    # Steam turbines may have steam supplied by a steam supply.
    steamTurbines: List[SteamTurbine] = []
     