#######################################################
# 
# Supercritical.py
# Python implementation of the Class Supercritical
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:52
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Generation.GenerationTrainingSimulation.FossilSteamSupply import FossilSteamSupply

@dataclass
class Supercritical(FossilSteamSupply):
    """Once-through supercritical boiler.
    """
    pass
