#######################################################
# 
# Pss2ST.py
# Python implementation of the Class Pss2ST
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:17
# Original author: pcha006
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Dynamics.StandardModels.PowerSystemStabilizerDynamics.InputSignalKind import InputSignalKind
from TC57CIM.IEC61970.Base.Domain.PU import PU
from TC57CIM.IEC61970.Base.Domain.Seconds import Seconds
from TC57CIM.IEC61970.Dynamics.StandardModels.PowerSystemStabilizerDynamics.PowerSystemStabilizerDynamics import PowerSystemStabilizerDynamics

@dataclass
class Pss2ST(PowerSystemStabilizerDynamics):
    """PTI Microprocessor-Based Stabilizer type 1.
    """
    # Type of input signal #1.  Typical Value = rotorAngularFrequencyDeviation.
    inputSignal1Type: InputSignalKind  = None
 
    # Type of input signal #2.  Typical Value = generatorElectricalPower.
    inputSignal2Type: InputSignalKind  = None
 
    # Gain (K1). 
    k1: PU  = None
 
    # Gain (K2). 
    k2: PU  = None
 
    # Time constant (T1). 
    t1: Seconds  = None
 
    # Time constant (T2).
    t2: Seconds  = None
 
    # Time constant (T3). 
    t3: Seconds  = None
 
    # Time constant (T4).
    t4: Seconds  = None
 
    # Time constant (T5). 
    t5: Seconds  = None
 
    # Time constant (T6). 
    t6: Seconds  = None
 
    # Time constant (T7). 
    t7: Seconds  = None
 
    # Time constant (T8). 
    t8: Seconds  = None
 
    # Time constant (T9). 
    t9: Seconds  = None
 
    # Time constant (T10). 
    t10: Seconds  = None
 
    # Limiter (Lsmax). 
    lsmax: PU  = None
 
    # Limiter (Lsmin). 
    lsmin: PU  = None
 
    # Cutoff limiter (Vcu). 
    vcu: PU  = None
 
    # Cutoff limiter (Vcl). 
    vcl: PU  = None
     