#######################################################
# 
# DiscontinuousExcitationControlDynamics.py
# Python implementation of the Class DiscontinuousExcitationControlDynamics
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:43
# Original author: ppbr003
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Dynamics.StandardModels.DynamicsFunctionBlock import DynamicsFunctionBlock
from TC57CIM.IEC61970.Dynamics.StandardModels.ExcitationSystemDynamics.ExcitationSystemDynamics import ExcitationSystemDynamics
from TC57CIM.IEC61970.Dynamics.StandardInterconnections.RemoteInputSignal import RemoteInputSignal

@dataclass
class DiscontinuousExcitationControlDynamics(DynamicsFunctionBlock):
    """Discontinuous excitation control function block whose behaviour is described by
    reference to a standard model <font color="#0f0f0f">or by definition of a user-
    defined model</font>.
    """
    # Excitation system model with which this discontinuous excitation control model
    # is associated.
    excitationSystemDynamics: Optional[ExcitationSystemDynamics] = None
 
    # Remote input signal used by this discontinuous excitation control system model.
    remoteInputSignal: Optional[RemoteInputSignal] = None
     