#######################################################
# 
# BaseVoltage.py
# Python implementation of the Class BaseVoltage
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:01
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Voltage import Voltage
from TC57CIM.IEC61970.Base.Core.ConductingEquipment import ConductingEquipment
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

@dataclass
class BaseVoltage(IdentifiedObject):
    """Defines a system base voltage which is referenced.
    """
    # The power system resource's base voltage.
    nominalVoltage: Voltage  = None
 
    # All conducting equipment with this base voltage.  Use only when there is no
    # voltage level container used and only one base voltage applies.  For example,
    # not used for transformers.
    ConductingEquipments: List[ConductingEquipment] = []
     