#######################################################
# 
# BusbarConfiguration.py
# Python implementation of the Class BusbarConfiguration
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:04
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class BusbarConfiguration(Enum):
    """Busbar layout for bay.
    """
    # Single bus.
    singleBus = auto()
    # Double bus.
    doubleBus = auto()
    # Main bus with transfer bus.
    mainWithTransfer = auto()
    # Ring bus.
    ringBus = auto()