#######################################################
# 
# ConnectivityNode.py
# Python implementation of the Class ConnectivityNode
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:22
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Core.ConnectivityNodeContainer import ConnectivityNodeContainer
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from ENTSOE.Extension.ENTSOEConnectivityNode import ENTSOEConnectivityNode

@dataclass
class ConnectivityNode(IdentifiedObject, ENTSOEConnectivityNode):
    """Connectivity nodes are points where terminals of AC conducting equipment are
    connected together with zero impedance.
    """
    # Container of this connectivity node.
    connectivityNodeContainer: Optional[ConnectivityNodeContainer] = None
     