#######################################################
# 
# NameTypeAuthority.py
# Python implementation of the Class NameTypeAuthority
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:52
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String

@dataclass
class NameTypeAuthority:
    """Authority responsible for creation and management of names of a given type;
    typically an organization or an enterprise system.
    """
    # Name of the name type authority.
    name: String  = None
 
    # Description of the name type authority.
    description: String  = None
     