#######################################################
# 
# Name.py
# Python implementation of the Class Name
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:55
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Core.NameType import NameType
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

@dataclass
class Name:
    """The Name class provides the means to define any number of human readable  names
    for an object. A name is <b>not</b> to be used for defining inter-object
    relationships. For inter-object relationships instead use the object
    identification 'mRID'.
    """
    # Any free text that name the object.
    name: String  = None
 
    # Type of this name.
    nameType: Optional[NameType] = None
 
    # Identified object that this name designates.
    identifiedObject: Optional[IdentifiedObject] = None
     