#######################################################
# 
# SubGeographicalRegion.py
# Python implementation of the Class SubGeographicalRegion
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:46
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Wires.Line import Line
from TC57CIM.IEC61970.Base.Core.Substation import Substation
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

@dataclass
class SubGeographicalRegion(IdentifiedObject):
    """A subset of a geographical region of a power system network model.
    """
    # The lines within the sub-geographical region.
    Lines: List[Line] = []
 
    # The substations in this sub-geographical region.
    Substations: List[Substation] = []
     