#######################################################
# 
# Substation.py
# Python implementation of the Class Substation
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:52
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Core.EquipmentContainer import EquipmentContainer
from TC57CIM.IEC61970.Base.Core.VoltageLevel import VoltageLevel
from TC57CIM.IEC61970.Base.Core.Bay import Bay
from TC57CIM.IEC61970.Base.DC.DCConverterUnit import DCConverterUnit

@dataclass
class Substation(EquipmentContainer):
    """A collection of equipment for purposes other than generation or utilization,
    through which electric energy in bulk is passed for the purposes of switching
    or modifying its characteristics.
    """
    # The voltage levels within this substation.
    voltageLevels: List[VoltageLevel] = []
 
    # Bays contained in the substation.
    bays: List[Bay] = []
 
    dCConverterUnits: List[DCConverterUnit] = []
     