#######################################################
# 
# Terminal.py
# Python implementation of the Class Terminal
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:57
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Core.PhaseCode import PhaseCode
from TC57CIM.IEC61970.Base.Core.ConnectivityNode import ConnectivityNode
from TC57CIM.IEC61970.Base.Core.ConductingEquipment import ConductingEquipment
from TC57CIM.IEC61970.Base.Wires.RegulatingControl import RegulatingControl
from TC57CIM.IEC61970.Base.Core.ACDCTerminal import ACDCTerminal

@dataclass
class Terminal(ACDCTerminal):
    """An AC electrical connection point to a piece of conducting equipment. Terminals
    are connected at physical connection points called connectivity nodes.
    """
    # Represents the normal network phasing condition.
    # If the attribute is missing three phases (ABC or ABCN) shall be assumed.
    phases: PhaseCode  = None
 
    # The connectivity node to which this terminal connects with zero impedance.
    ConnectivityNode: Optional[ConnectivityNode] = None
 
    # The conducting equipment of the terminal.  Conducting equipment have  terminals
    # that may be connected to other conducting equipment terminals via connectivity
    # nodes or topological nodes.
    ConductingEquipment: Optional[ConductingEquipment] = None
 
    # The controls regulating this terminal.
    RegulatingControls: List[RegulatingControl] = []
     