#######################################################
# 
# ExcST3A.py
# Python implementation of the Class ExcST3A
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:12
# Original author: tsaxton
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.PU import PU
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Seconds import Seconds
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.AngleDegrees import AngleDegrees
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.ExcitationSystemDynamics.ExcitationSystemDynamics import ExcitationSystemDynamics

@dataclass
class ExcST3A(ExcitationSystemDynamics):
    """Modified IEEE ST3A static excitation system with added speed multiplier.
    """
    # Maximum voltage regulator input limit (Vimax).  Typical Value = 0.2.
    vimax: PU  = None
 
    # Minimum voltage regulator input limit (Vimin).  Typical Value = -0.2.
    vimin: PU  = None
 
    # AVR gain (Kj).  Typical Value = 200.
    kj: PU  = None
 
    # Voltage regulator time constant (Tb).  Typical Value = 6.67.
    tb: Seconds  = None
 
    # Voltage regulator time constant (Tc).  Typical Value = 1.
    tc: Seconds  = None
 
    # Maximum AVR output (Efdmax).  Typical Value = 6.9.
    efdmax: PU  = None
 
    # Forward gain constant of the inner loop field regulator (Km).  Typical Value =
    # 7.04.
    km: PU  = None
 
    # Forward time constant of inner loop field regulator (Tm).  Typical Value = 1.
    tm: Seconds  = None
 
    # Maximum voltage regulator output (Vrmax).  Typical Value = 1.
    vrmax: PU  = None
 
    # Minimum voltage regulator output (Vrmin).  Typical Value = 0.
    vrmin: PU  = None
 
    # Feedback gain constant of the inner loop field regulator (Kg).  Typical Value =
    # 1.
    kg: PU  = None
 
    # Potential source gain (Kp) (>0).  Typical Value = 4.37.
    kp: PU  = None
 
    # Potential circuit phase angle (thetap).  Typical Value = 20.
    thetap: AngleDegrees  = None
 
    # Potential circuit gain coefficient (Ki).  Typical Value = 4.83.
    ki: PU  = None
 
    # Rectifier loading factor proportional to commutating reactance (Kc). Typical
    # Value = 1.1.
    kc: PU  = None
 
    # Reactance associated with potential source (Xl).  Typical Value = 0.09.
    xl: PU  = None
 
    # Maximum excitation voltage (Vbmax).  Typical Value = 8.63.
    vbmax: PU  = None
 
    # Maximum inner loop feedback voltage (Vgmax).  Typical Value = 6.53.
    vgmax: PU  = None
 
    # Coefficient to allow different usage of the model-speed coefficient (Ks).
    # Typical Value = 0.
    ks: PU  = None
 
    # Coefficient to allow different usage of the model-speed coefficient (Ks1).
    # Typical Value = 0.
    ks1: PU  = None
     