#######################################################
# 
# ExcST7B.py
# Python implementation of the Class ExcST7B
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:13
# Original author: tsaxton
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.PU import PU
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.ExcitationSystemDynamics.ExcST7BOELselectorKind import ExcST7BOELselectorKind
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Seconds import Seconds
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.ExcitationSystemDynamics.ExcST7BUELselectorKind import ExcST7BUELselectorKind
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.ExcitationSystemDynamics.ExcitationSystemDynamics import ExcitationSystemDynamics

@dataclass
class ExcST7B(ExcitationSystemDynamics):
    """Modified IEEE ST7B static excitation system without stator current limiter
    (SCL) and current compensator (DROOP) inputs.
    """
    # High-value gate feedback gain (Kh).  Typical Value = 1.
    kh: PU  = None
 
    # Voltage regulator integral gain (Kia).  Typical Value = 1.
    kia: PU  = None
 
    # Low-value gate feedback gain (Kl).  Typical Value = 1.
    kl: PU  = None
 
    # Voltage regulator proportional gain (Kpa).  Typical Value = 40.
    kpa: PU  = None
 
    # OEL input selector (OELin). Typical Value = noOELinput.
    oelin: ExcST7BOELselectorKind  = None
 
    # Regulator lag time constant (Tb).  Typical Value = 1.
    tb: Seconds  = None
 
    # Regulator lead time constant (Tc).  Typical Value = 1.
    tc: Seconds  = None
 
    # Excitation control system stabilizer time constant (Tf).  Typical Value = 1.
    tf: Seconds  = None
 
    # Feedback time constant of inner loop field voltage regulator (Tg).  Typical
    # Value = 1.
    tg: Seconds  = None
 
    # Feedback time constant (Tia).  Typical Value = 3.
    tia: Seconds  = None
 
    # Rectifier firing time constant (Ts).  Typical Value = 0.
    ts: Seconds  = None
 
    # UEL input selector (UELin). Typical Value = noUELinput.
    uelin: ExcST7BUELselectorKind  = None
 
    # Maximum voltage reference signal (Vmax).  Typical Value = 1.1.
    vmax: PU  = None
 
    # Minimum voltage reference signal (Vmin).  Typical Value = 0.9.
    vmin: PU  = None
 
    # Maximum voltage regulator output (Vrmax).  Typical Value = 5.
    vrmax: PU  = None
 
    # Minimum voltage regulator output (Vrmin).  Typical Value = -4.5.
    vrmin: PU  = None
     