#######################################################
# 
# ExtPhaseCodeKind.py
# Python implementation of the Class ExtPhaseCodeKind
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:05
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class ExtPhaseCodeKind(Enum):
    """Enumeration of phase identifiers. Allows designation of phases for both
    transmission and distribution equipment, circuits and loads.
      Residential and small commercial loads are often served from single-phase, or
    split-phase, secondary circuits. Phases 1 and 2 refer to hot wires that are 180
    degrees out of phase, while N refers to the neutral wire. Through single-phase
    transformer connections, these secondary circuits may be served from one or two
    of the primary phases A, B, and C. For three-phase loads, use the A, B, C phase
    codes instead of s12N.
    """
    # ABC to Neutral
    ABCN = auto()
    # Involving all phases
    ABC = auto()
    # AB to Neutral
    ABN = auto()
    # Phases A, C and neutral.
    ACN = auto()
    # BC to neutral.
    BCN = auto()
    # Phases A to B
    AB = auto()
    # Phases A and C
    AC = auto()
    # Phases B to C
    BC = auto()
    # Phases A to neutral.
    AN = auto()
    # Phases B to neutral.
    BN = auto()
    # Phases C to neutral.
    CN = auto()
    # Phase A.
    A = auto()
    # Phase B.
    B = auto()
    # Phase C.
    C = auto()
    # Neutral
    N = auto()
    # Phase S2 to neutral.
    S2N = auto()
    # Phase S1, S2 to neutral.
    S12N = auto()
    # Phase S1 to Neutral
    S1N = auto()
    # Phase S2.
    S2 = auto()
    # Phase S1 to S2
    S12 = auto()
    # Not applicable to any phase
    none = auto()
    # Phase A current relative to Phase A voltage
    AtoAv = auto()
    # Phase B current or voltage relative to Phase A voltage
    BAv = auto()
    # CA to Neutral
    CAN = auto()
    # hase C current or voltage relative to Phase A voltage
    CAv = auto()
    # Neutral to ground
    NG = auto()
    # Phase S1
    S1 = auto()