#######################################################
# 
# ExtUnitMultiplierKind.py
# Python implementation of the Class ExtUnitMultiplierKind
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:05
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class ExtUnitMultiplierKind(Enum):
    """The unit multipliers defined for the CIM.
    """
    # Pico 10**-12
    p = auto()
    # Nano 10**-9
    n = auto()
    # Micro 10**-6
    micro = auto()
    # Milli 10**-3
    m = auto()
    # Centi 10**-2
    c = auto()
    # Deci 10**-1
    d = auto()
    # Kilo 10**3
    k = auto()
    # Mega 10**6
    M = auto()
    # Giga 10**9
    G = auto()
    # Tera 10**12
    T = auto()
    # Not Applicable or "x1"
    none = auto()
    # deca 10**1
    da = auto()
    # hecto 10**2
    h = auto()