#######################################################
# 
# Breaker.py
# Python implementation of the Class Breaker
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:11
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.SteadyStateHypothesisProfile.Wires.ProtectedSwitch import ProtectedSwitch

@dataclass
class Breaker(ProtectedSwitch):
    """A mechanical switching device capable of making, carrying, and breaking
    currents under normal circuit conditions and also making, carrying for a
    specified time, and breaking currents under specified abnormal circuit
    conditions e.g.  those of short circuit.
    """
    pass
