#######################################################
# 
# EnergySource.py
# Python implementation of the Class EnergySource
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:42
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.ActivePower import ActivePower
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.ReactivePower import ReactivePower
from ENTSOE.CommonGridModelExchangeStandard.SteadyStateHypothesisProfile.Core.ConductingEquipment import ConductingEquipment

@dataclass
class EnergySource(ConductingEquipment):
    """A generic equivalent for an energy supplier on a transmission or distribution
    voltage level.
    """
    # High voltage source active injection. Load sign convention is used, i.e.
    # positive sign means flow out from a node.
    # Starting value for steady state solutions.
    activePower: ActivePower  = None
 
    # High voltage source reactive injection. Load sign convention is used, i.e.
    # positive sign means flow out from a node.
    # Starting value for steady state solutions.
    reactivePower: ReactivePower  = None
     