#######################################################
# 
# GroundDisconnector.py
# Python implementation of the Class GroundDisconnector
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:29
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.SteadyStateHypothesisProfile.Wires.Switch import Switch

@dataclass
class GroundDisconnector(Switch):
    """A manually operated or motor operated mechanical switching device used for
    isolating a circuit or equipment from ground.
    """
    pass
