#######################################################
# 
# PhaseTapChanger.py
# Python implementation of the Class PhaseTapChanger
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:05
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.SteadyStateHypothesisProfile.Wires.TapChanger import TapChanger

@dataclass
class PhaseTapChanger(TapChanger):
    """A transformer phase shifting tap model that controls the phase angle difference
    across the power transformer and potentially the active power flow through the
    power transformer.  This phase tap model may also impact the voltage magnitude.
    """
    pass
