#######################################################
# 
# PhaseTapChangerNonLinear.py
# Python implementation of the Class PhaseTapChangerNonLinear
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:18
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.SteadyStateHypothesisProfile.Wires.PhaseTapChanger import PhaseTapChanger

@dataclass
class PhaseTapChangerNonLinear(PhaseTapChanger):
    """The non-linear phase tap changer describes the non-linear behavior of a phase
    tap changer. This is a base class for the symmetrical and asymmetrical phase
    tap changer models. The details of these models can be found in the IEC 61970-
    301 document.
    """
    pass
