#######################################################
# 
# Assignment.py
# Python implementation of the Class Assignment
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:47:55
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.DateTimeInterval import DateTimeInterval
from TC57CIM.IEC61968.InfIEC61968.InfWork.WorkDocument import WorkDocument

@dataclass
class Assignment(WorkDocument):
    """An assignment is given to an ErpPerson, Crew, Organisation, Equipment Item,
    Tool, etc. and may be used to perform Work, WorkTasks, Procedures, etc.
    TimeSchedules may be set up directly for Assignments or indirectly via the
    associated WorkTask. Note that these associations are all inherited through the
    recursive relationship on Document.
    """
    # Period between the assignment becoming effective and its expiration.
    effectivePeriod: DateTimeInterval  = None
     