#######################################################
# 
# ConditionFactor.py
# Python implementation of the Class ConditionFactor
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:11
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.InfIEC61968.InfWork.ConditionFactorKind import ConditionFactorKind
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61968.Common.Status import Status
from TC57CIM.IEC61968.InfIEC61968.InfWork.WorkIdentifiedObject import WorkIdentifiedObject

@dataclass
class ConditionFactor(WorkIdentifiedObject):
    """This is to specify the various condition factors for a design that may alter
    the cost estimate or the allocation.
    """
    # Kind of this condition factor.
    kind: ConditionFactorKind  = None
 
    # The actual value of the condition factor, such as labor flat fee or percentage.
    cfValue: String  = None
 
    status: Status  = None
     