#######################################################
# 
# CULaborCode.py
# Python implementation of the Class CULaborCode
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:21
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61968.Common.Status import Status
from TC57CIM.IEC61968.InfIEC61968.InfWork.WorkIdentifiedObject import WorkIdentifiedObject

@dataclass
class CULaborCode(WorkIdentifiedObject):
    """Labor code associated with various compatible unit labor items.
    """
    # Labor code.
    code: String  = None
 
    status: Status  = None
     