#######################################################
# 
# PropertyUnit.py
# Python implementation of the Class PropertyUnit
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:19
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.InfIEC61968.InfWork.WorkActionKind import WorkActionKind
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61968.Common.Status import Status
from TC57CIM.IEC61968.InfIEC61968.InfWork.WorkIdentifiedObject import WorkIdentifiedObject
from TC57CIM.IEC61968.InfIEC61968.InfWork.CompatibleUnit import CompatibleUnit
from TC57CIM.IEC61968.InfIEC61968.InfWork.CUMaterialItem import CUMaterialItem

@dataclass
class PropertyUnit(WorkIdentifiedObject):
    """Unit of property for reporting purposes.
    """
    # Activity code identifies a specific and distinguishable work action.
    activityCode: WorkActionKind  = None
 
    # Used for property record accounting. For example, in the USA, this would be a
    # FERC account.
    propertyAccount: String  = None
 
    # A code that identifies appropriate type of property accounts such as
    # distribution, streetlgihts, communications.
    accountingUsage: String  = None
 
    status: Status  = None
 
    compatibleUnits: List[CompatibleUnit] = []
 
    cUMaterialItems: List[CUMaterialItem] = []
     