#######################################################
# 
# Regulation.py
# Python implementation of the Class Regulation
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:32
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61968.InfIEC61968.InfWork.WorkDocument import WorkDocument

@dataclass
class Regulation(WorkDocument):
    """Special requirements and/or regulations may pertain to certain types of assets
    or work. For example, fire protection and scaffolding.
    """
    # External reference to regulation, if applicable.
    referenceNumber: String  = None
     