#######################################################
# 
# WorkDocument.py
# Python implementation of the Class WorkDocument
# Generated by Enterprise Architect
# Created on:      21-May-2025 11:00:39
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.Common.Document import Document

@dataclass
class WorkDocument(Document):
    """Shadow class for Document, to isolate subclassing from this package. If any
    subclass gets normative and needs inheritance, it will inherit directly from
    Document.
    """
    pass
