#######################################################
# 
# WorkCostSummary.py
# Python implementation of the Class WorkCostSummary
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:51:32
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.InfIEC61968.InfWork.WorkDocument import WorkDocument

@dataclass
class WorkCostSummary(WorkDocument):
    """A roll up by cost type for the entire cost of a work order. For example, total
    labor.
    """
    pass
