#######################################################
# 
# Route.py
# Python implementation of the Class Route
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:34
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61968.Common.Status import Status
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC61968.Common.Location import Location

@dataclass
class Route(IdentifiedObject):
    """Route that is followed, for example by service crews.
    """
    # Classification by utility's work management standards and practices.
    type: String  = None
 
    status: Status  = None
 
    Locations: List[Location] = []
     