#######################################################
# 
# EquivalentEquipment.py
# Python implementation of the Class EquivalentEquipment
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:45
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.SteadyStateHypothesisProfile.Core.ConductingEquipment import ConductingEquipment

@dataclass
class EquivalentEquipment(ConductingEquipment):
    """The class represents equivalent objects that are the result of a network
    reduction. The class is the base for equivalent objects of different types.
    """
    pass
