#######################################################
# 
# ContingencyEquipment.py
# Python implementation of the Class ContingencyEquipment
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:16
# Original author: kdd
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Contingency.ContingencyEquipmentStatusKind import ContingencyEquipmentStatusKind
from TC57CIM.IEC61970.Base.Contingency.ContingencyElement import ContingencyElement
from TC57CIM.IEC61970.Base.Core.Equipment import Equipment

@dataclass
class ContingencyEquipment(ContingencyElement):
    """A equipment to which the in service status is to change such as a power
    transformer or AC line segment.
    """
    # The status for the associated equipment when in the contingency state.   This
    # status is independent of the case to which the contingency is originally
    # applied, but defines the equipment status when the contingency is applied.
    contingentStatus: ContingencyEquipmentStatusKind  = None
 
    # The single piece of equipment to which to apply the contingency.
    Equipment: Optional[Equipment] = None
     