#######################################################
# 
# ContingencyElement.py
# Python implementation of the Class ContingencyElement
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:16
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

@dataclass
class ContingencyElement(IdentifiedObject):
    """An element of a system event to be studied by contingency analysis,
    representing a change in status of a single piece of equipment.
    """
    pass
