#######################################################
# 
# ContingencyEquipmentStatusKind.py
# Python implementation of the Class ContingencyEquipmentStatusKind
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:16
# Original author: kdd
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class ContingencyEquipmentStatusKind(Enum):
    """Indicates the state which the contingency equipment is to be in when the
    contingency is applied.
    """
    # The equipment is in service.
    inService = auto()
    # The equipment is to be taken out of service.
    outOfService = auto()