#######################################################
# 
# CsOperatingModeKind.py
# Python implementation of the Class CsOperatingModeKind
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:28
# Original author: selaost1
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class CsOperatingModeKind(Enum):
    """Operating mode for HVDC line operating as Current Source Converter.
    """
    # Operating as inverter
    inverter = auto()
    # Operating as rectifier.
    rectifier = auto()