#######################################################
# 
# IEC61968CIMVersion.py
# Python implementation of the Class IEC61968CIMVersion
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:37
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Date import Date
from TC57CIM.IEC61970.Base.Domain.String import String

@dataclass
class IEC61968CIMVersion:
    """IEC 61968 version number assigned to this UML model.
    """
    # Form is YYYY-MM-DD for example for January 5, 2009 it is 2009-01-05.
    date: str  ="2014-02-01"
 
    # Form is IEC61968CIMXXvYY where XX is the major CIM package version and the YY
    # is the minor version. For example IEC61968CIM10v17.
    version: str  = "IEC61968CIM12v08"
     