#######################################################
# 
# TextDiagramObject.py
# Python implementation of the Class TextDiagramObject
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:51:03
# Original author: Jean-Luc
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.String import String
from ENTSOE.CommonGridModelExchangeStandard.DiagramLayoutProfile.DiagramLayout.DiagramObject import DiagramObject

@dataclass
class TextDiagramObject(DiagramObject):
    """A diagram object for placing free-text or text derived from an associated
    domain object.
    """
    # The text that is displayed by this text diagram object.
    text: String  = None
     