#######################################################
# 
# DiscExcContIEEEDEC2A.py
# Python implementation of the Class DiscExcContIEEEDEC2A
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:42
# Original author: pcha006
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.PU import PU
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Seconds import Seconds
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.DiscontinuousExcitationControlDynamics.DiscontinuousExcitationControlDynamics import DiscontinuousExcitationControlDynamics

@dataclass
class DiscExcContIEEEDEC2A(DiscontinuousExcitationControlDynamics):
    """The class represents IEEE Type DEC2A model for the discontinuous excitation
    control. This system provides transient excitation boosting via an open-loop
    control as initiated by a trigger signal generated remotely.
    
      Reference: IEEE Standard 421.5-2005 Section 12.3.
    """
    # Discontinuous controller input reference (<i>V</i><i><sub>K</sub></i>). 
    vk: PU  = None
 
    # Discontinuous controller time constant (<i>T</i><i><sub>D1</sub></i>). 
    td1: Seconds  = None
 
    # Discontinuous controller washout time constant (<i>T</i><i><sub>D2</sub></i>). 
    td2: Seconds  = None
 
    # Limiter (<i>V</i><i><sub>DMIN</sub></i>). 
    vdmin: PU  = None
 
    # Limiter (<i>V</i><i><sub>DMAX</sub></i>). 
    vdmax: PU  = None
     