#######################################################
# 
# EnergySource.py
# Python implementation of the Class EnergySource
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:42
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.EquipmentBoundaryProfile.Core.ConductingEquipment import ConductingEquipment
from ENTSOE.CommonGridModelExchangeStandard.EquipmentBoundaryProfile.Wires.EnergySchedulingType import EnergySchedulingType

@dataclass
class EnergySource(ConductingEquipment):
    """A generic equivalent for an energy supplier on a transmission or distribution
    voltage level.
    """
    # Energy Scheduling Type of an Energy Source
    EnergySchedulingType: Optional[EnergySchedulingType] = None
     