#######################################################
# 
# Junction.py
# Python implementation of the Class Junction
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:31
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.EquipmentBoundaryProfile.Wires.Connector import Connector

@dataclass
class Junction(Connector):
    """A point where one or more conducting equipments are connected with zero
    resistance.
    """
    pass
