#######################################################
# 
# ChargeComponent.py
# Python implementation of the Class ChargeComponent
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:05
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC62325.MarketOperations.MarketSystem.MarketResults.BillDeterminant import BillDeterminant

@dataclass
class ChargeComponent(IdentifiedObject):
    """A Charge Component is a list of configurable charge quality items to feed into
    settlement calculation and/or bill determinants.
    """
    deleteStatus: String  = None
 
    effectiveDate: DateTime  = None
 
    terminationDate: DateTime  = None
 
    message: String  = None
 
    type: String  = None
 
    sum: String  = None
 
    roundOff: String  = None
 
    equation: String  = None
 
    # A BillDeterminant can have 0-n ChargeComponent and a ChargeComponent can
    # associate to 0-n BillDeterminant.
    billDeterminants: List[BillDeterminant] = []
     