#######################################################
# 
# ChargeGroup.py
# Python implementation of the Class ChargeGroup
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:14
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC62325.MarketOperations.MarketOpCommon.MktUserAttribute import MktUserAttribute

@dataclass
class ChargeGroup(IdentifiedObject):
    """Charge Group is the grouping of Charge Types for settlement invoicing purpose.
    Examples such as Ancillary Services, Interests, etc.
    """
    marketCode: str  = None
 
    effectiveDate: DateTime  = None
 
    terminationDate: DateTime  = None
 
    # A ChargeGroup instance can have relationships with other ChargeGroup instances.
    chargeGroup: Optional[ChargeGroup] = None
 
    mktUserAttributes: List[MktUserAttribute] = []
     