#######################################################
# 
# ChargeType.py
# Python implementation of the Class ChargeType
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:15
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61968.Common.Document import Document
from TC57CIM.IEC62325.MarketOperations.ParticipantInterfaces.ChargeGroup import ChargeGroup
from TC57CIM.IEC62325.MarketOperations.ParticipantInterfaces.ChargeComponent import ChargeComponent
from TC57CIM.IEC62325.MarketOperations.MarketOpCommon.MktUserAttribute import MktUserAttribute

@dataclass
class ChargeType(Document):
    """Charge Type is the basic level configuration for settlement to process specific
    charges for invoicing purpose. Examples such as: Day Ahead Spinning Reserve
    Default Invoice Interest Charge, etc.
    """
    effectiveDate: DateTime  = None
 
    terminationDate: DateTime  = None
 
    factor: str  = None
 
    chargeOrder: str  = None
 
    frequencyType: str  = None
 
    chargeVersion: str  = None
 
    totalInterval: str  = None
 
    # A ChargeGroup can have 0-n ChargeType. A ChargeType can associate to 0-n
    # ChargeGroup.
    chargeGroups: List[ChargeGroup] = []
 
    # A ChargeType can have 0-n ChargeComponent and a ChargeComponent can associate
    # to 0-n ChargeType
    chargeComponents: List[ChargeComponent] = []
 
    mktUserAttributes: List[MktUserAttribute] = []
     