#######################################################
# 
# GeneratingBid.py
# Python implementation of the Class GeneratingBid
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:12
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Domain.ActivePowerChangeRate import ActivePowerChangeRate
from TC57CIM.IEC61970.Base.Domain.ActivePower import ActivePower
from TC57CIM.IEC61970.Base.Domain.Integer import Integer
from TC57CIM.IEC62325.MarketOperations.ParticipantInterfaces.ResourceBid import ResourceBid
from TC57CIM.IEC62325.MarketOperations.ParticipantInterfaces.NotificationTimeCurve import NotificationTimeCurve
from TC57CIM.IEC62325.MarketOperations.ParticipantInterfaces.RampRateCurve import RampRateCurve
from TC57CIM.IEC62325.MarketOperations.MarketSystem.ExternalInputs.SecurityConstraints import SecurityConstraints

@dataclass
class GeneratingBid(ResourceBid):
    """Offer to supply energy/ancillary services from a generating unit or resource
    """
    # Will indicate if the unit is part of a CC offer or not
    combinedCycleUnitOffer: String  = None
 
    # Maximum down time.
    downTimeMax: Float  = None
 
    # Installed Capacity value
    installedCapacity: Float  = None
 
    # Maximum Dn ramp rate in MW/min
    lowerRampRate: ActivePowerChangeRate  = None
 
    # Power rating available for unit under emergency conditions greater than or
    # equal to maximum economic limit.
    maxEmergencyMW: ActivePower  = None
 
    # Maximum high economic MW limit, that should not exceed the maximum operating MW
    # limit
    maximumEconomicMW: Float  = None
 
    # Minimum power rating for unit under emergency conditions, which is less than or
    # equal to the economic minimum.
    minEmergencyMW: ActivePower  = None
 
    # Low economic MW limit that shall be greater than or equal to the minimum
    # operating MW limit
    minimumEconomicMW: Float  = None
 
    # Resource fixed no load cost.
    noLoadCost: Float  = None
 
    # Time required for crew notification prior to start up of the unit.
    notificationTime: Float  = None
 
    # Bid operating mode ('C' - cycling, 'F' - fixed, 'M' - must run, 'U' -
    # unavailable)
    operatingMode: String  = None
 
    # Maximum Up ramp rate in MW/min
    raiseRampRate: ActivePowerChangeRate  = None
 
    # Ramp curve type:
    # 0 - Fixed ramp rate independent of rate function unit MW output
    # 1 - Static ramp rates as a function of unit MW output only
    # 2 - Dynamic ramp rates as a function of unit MW output and ramping time
    rampCurveType: Integer  = None
 
    # Startup cost/price
    startupCost: Float  = None
 
    # Resource startup ramp rate (MW/minute)
    startUpRampRate: ActivePowerChangeRate  = None
 
    # Resource startup type:
    # 1 - Fixed startup time and fixed startup cost
    # 2 - Startup time as a function of down time and fixed startup cost
    # 3 - Startup cost as a function of down time
    startUpType: Integer  = None
 
    # Maximum up time.
    upTimeMax: Float  = None
 
    notificationTimeCurve: Optional[NotificationTimeCurve] = None
 
    rampRateCurves: List[RampRateCurve] = []
 
    securityConstraintss: List[SecurityConstraints] = []
     