#######################################################
# 
# LoadFollowingInst.py
# Python implementation of the Class LoadFollowingInst
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:39
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC61970.Base.Domain.Float import Float

@dataclass
class LoadFollowingInst:
    """Metered SubSystem Load Following Instruction
    """
    # Unique instruction id per instruction, assigned by the SC and provided to ADS.
    # ADS passes through.
    mssInstructionID: String  = None
 
    # Instruction Start Time
    startTime: DateTime  = None
 
    # Instruction End Time
    endTime: DateTime  = None
 
    # Load Following MW Positive for follow-up and negative for follow-down
    loadFollowingMW: Float  = None
     