#######################################################
# 
# ExcCZ.py
# Python implementation of the Class ExcCZ
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:54
# Original author: tsaxton
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.PU import PU
from TC57CIM.IEC61970.Base.Domain.Seconds import Seconds
from TC57CIM.IEC61970.Dynamics.StandardModels.ExcitationSystemDynamics.ExcitationSystemDynamics import ExcitationSystemDynamics

@dataclass
class ExcCZ(ExcitationSystemDynamics):
    """Czech Proportion/Integral Exciter.
    """
    # Regulator proportional gain (Kp).
    kp: PU  = None
 
    # Regulator integral time constant (Tc). 
    tc: Seconds  = None
 
    # Voltage regulator maximum limit (Vrmax). 
    vrmax: PU  = None
 
    # Voltage regulator minimum limit (Vrmin). 
    vrmin: PU  = None
 
    # Regulator gain (Ka).
    ka: PU  = None
 
    # Regulator time constant (Ta).
    ta: Seconds  = None
 
    # Exciter constant related to self-excited field (Ke).
    ke: PU  = None
 
    # Exciter time constant, integration rate associated with exciter control (Te).
    te: Seconds  = None
 
    # Exciter output maximum limit (Efdmax).
    efdmax: PU  = None
 
    # Exciter output minimum limit (Efdmin). 
    efdmin: PU  = None
     