#######################################################
# 
# ExcST6BOELselectorKind.py
# Python implementation of the Class ExcST6BOELselectorKind
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:04
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class ExcST6BOELselectorKind(Enum):
    """Type of connection for the OEL input used for static excitation systems type 6B.
    """
    # No OEL input is used.
    noOELinput = auto()
    # The connection is before UEL.
    beforeUEL = auto()
    # The connection is after UEL.
    afterUEL = auto()