#######################################################
# 
# CRRMarket.py
# Python implementation of the Class CRRMarket
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:18
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC62325.MarketOperations.MarketPlan.Market import Market

@dataclass
class CRRMarket(Market):
    """Model that describes the Congestion Revenue Rights Auction Market
    """
    # labelID - an ID for a set of apnodes/pnodes used in a CRR market
    labelID: String  = None
     