#######################################################
# 
# MarketProduct.py
# Python implementation of the Class MarketProduct
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:44
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC62325.MarketOperations.MktDomain.MarketProductType import MarketProductType
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC62325.MarketOperations.ParticipantInterfaces.ProductBid import ProductBid
from TC57CIM.IEC62325.MarketOperations.MarketSystem.MarketResults.ResourceAwardInstruction import ResourceAwardInstruction
from TC57CIM.IEC62325.MarketOperations.ParticipantInterfaces.BidError import BidError
from TC57CIM.IEC62325.MarketOperations.ReferenceData.BidPriceCap import BidPriceCap
from TC57CIM.IEC62325.MarketOperations.MarketSystem.MarketResults.MarketRegionResults import MarketRegionResults
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC62325.MarketOperations.MarketPlan.Market import Market

@dataclass
class MarketProduct(IdentifiedObject):
    """A product traded by an RTO (e.g. energy, 10 minute spinning reserve).Ancillary
    service product examples include:Regulation UpRegulation DnSpinning ReserveNon-
    Spinning ReserveOperating Reserve
    """
    # Market product type examples:
    # 
    # EN (Energy)
    # RU (Regulation Up)
    # RD (Regulation Dn)
    # SR (Spinning Reserve)
    # NR (Non-Spinning Reserve)
    # RC (RUC)
    marketProductType: MarketProductType  = None
 
    # Ramping time interval for the specific market product type specified by
    # marketProductType attribute. For example, if marketProductType = EN (from
    # enumeration MarketProductType), then the rampInterval is the ramping time
    # interval for Energy.
    rampInterval: Float  = None
 
    productBids: List[ProductBid] = []
 
    resourceAwardInstructions: List[ResourceAwardInstruction] = []
 
    bidErrors: List[BidError] = []
 
    bidPriceCaps: List[BidPriceCap] = []
 
    marketRegionResults: Optional[MarketRegionResults] = None
 
    market: Optional[Market] = None
     