#######################################################
# 
# ComModule.py
# Python implementation of the Class ComModule
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:08
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Domain.Minutes import Minutes
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61968.Assets.Asset import Asset
from TC57CIM.IEC61968.Metering.ComFunction import ComFunction

@dataclass
class ComModule(Asset):
    """An asset having communications capabilities that can be paired with a meter or
    other end device to provide the device with communication ability, through
    associated communication function. An end device that has communications
    capabilities through embedded hardware can use that function directly (without
    the communication module), or combine embedded communication function with
    additional communication functions provided through an external communication
    module (e.g. zigbee).
    """
    # Automated meter reading (AMR) system communicating with this com module.
    amrSystem: String  = None
 
    # Time zone offset relative to GMT for the location of this com module.
    timeZoneOffset: Minutes  = None
 
    # If true, autonomous daylight saving time (DST) function is supported.
    supportsAutonomousDst: Boolean  = None
 
    # All functions this communication module performs.
    comFunctions: List[ComFunction] = []
     