#######################################################
# 
# EndDeviceCapability.py
# Python implementation of the Class EndDeviceCapability
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:38
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean

@dataclass
class EndDeviceCapability:
    """Inherent capabilities of an end device (i.e., the functions it supports).
    """
    # True if reverse flow function is supported.
    reverseFlow: Boolean  = None
 
    # True if demand response function is supported.
    demandResponse: Boolean  = None
 
    # True if metrology function is supported.
    metrology: Boolean  = None
 
    # True if outage history function is supported.
    outageHistory: Boolean  = None
 
    # True if relays programming function is supported.
    relaysProgramming: Boolean  = None
 
    # True if on request read function is supported.
    onRequestRead: Boolean  = None
 
    # True if autonomous DST (daylight saving time) function is supported.
    autonomousDst: Boolean  = None
 
    # True if communication function is supported.
    communication: Boolean  = None
 
    # True if connect and disconnect function is supported.
    connectDisconnect: Boolean  = None
 
    # True if electric metering function is supported.
    electricMetering: Boolean  = None
 
    # True if gas metering function is supported.
    gasMetering: Boolean  = None
 
    # True if water metering function is supported.
    waterMetering: Boolean  = None
 
    # True if the displaying of text messages is supported.
    textMessage: Boolean  = None
 
    # True if pricing information is supported.
    pricingInfo: Boolean  = None
 
    # True if device produces pulse outputs.
    pulseOutput: Boolean  = None
 
    # True if device performs pressure compensation for metered quantities.
    pressureCompensation: Boolean  = None
 
    # True if device performs temperature compensation for metered quantities.
    temperatureCompensation: Boolean  = None
 
    # True if device performs super compressibility compensation for metered
    # quantities.
    superCompressibilityCompensation: Boolean  = None
     