#######################################################
# 
# EndDeviceControl.py
# Python implementation of the Class EndDeviceControl
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:39
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Domain.DateTimeInterval import DateTimeInterval
from TC57CIM.IEC61970.Base.Domain.FloatQuantity import FloatQuantity
from TC57CIM.IEC61970.Base.Domain.Integer import Integer
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61968.Metering.EndDeviceTiming import EndDeviceTiming
from TC57CIM.IEC61968.Metering.EndDeviceControlType import EndDeviceControlType
from TC57CIM.IEC61968.Metering.UsagePointGroup import UsagePointGroup
from TC57CIM.IEC61968.Metering.UsagePoint import UsagePoint
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC61968.Metering.EndDeviceAction import EndDeviceAction
from TC57CIM.IEC61968.Metering.EndDevice import EndDevice

@dataclass
class EndDeviceControl(IdentifiedObject):
    """Instructs an end device (or an end device group) to perform a specified action.
    """
    # Identifier assigned by the initiator (e.g. retail electric provider) of an end
    # device control action to uniquely identify the demand response event, text
    # message, or other subject of the control action. Can be used when cancelling an
    # event or text message request or to identify the originating event or text
    # message in a consequential end device event.
    issuerTrackingID: String  = None
 
    # Unique identifier of the business entity originating an end device control.
    issuerID: String  = None
 
    # Reason for the control action that allows to determine how to continue
    # processing. For example, disconnect meter command may require different
    # processing by the receiving system if it has been issued for a network-related
    # reason (protection) or for a payment-related reason.
    reason: String  = None
 
    # (if control has scheduled duration) Date and time interval the control has been
    # scheduled to execute within.
    scheduledInterval: DateTimeInterval  = None
 
    # (if applicable) Price signal used as parameter for this end device control.
    priceSignal: FloatQuantity  = None
 
    # Level of a demand response program request, where 0=emergency. Note: Attribute
    # is not defined on DemandResponseProgram as it is not its inherent property (it
    # serves to control it).
    drProgramLevel: Integer  = None
 
    # Whether a demand response program request is mandatory. Note: Attribute is not
    # defined on DemandResponseProgram as it is not its inherent property (it serves
    # to control it).
    drProgramMandatory: Boolean  = None
 
    # Timing for the control actions performed on the device identified in the end
    # device control.
    primaryDeviceTiming: EndDeviceTiming  = None
 
    # Timing for the control actions performed by devices that are responding to
    # event related information sent to the primary device indicated in the end
    # device control.  For example, load control actions performed by a PAN device in
    # response to demand response event information sent to a PAN gateway server.
    secondaryDeviceTiming: EndDeviceTiming  = None
 
    # Type of this end device control.
    EndDeviceControlType: Optional[EndDeviceControlType] = None
 
    # All usage point groups receiving commands from this end device control.
    UsagePointGroups: List[UsagePointGroup] = []
 
    # All usage points receiving commands from this end device control.
    UsagePoints: List[UsagePoint] = []
 
    # End device action issued by this end device control.
    EndDeviceAction: Optional[EndDeviceAction] = None
 
    # All end devices receiving commands from this end device control.
    EndDevices: List[EndDevice] = []
     