#######################################################
# 
# EndDeviceEventType.py
# Python implementation of the Class EndDeviceEventType
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:39
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

@dataclass
class EndDeviceEventType(IdentifiedObject):
    """Detailed description for an event produced by an end device. Values in
    attributes allow for creation of recommended codes to be used for identifying
    end device events as follows: <type>.<domain>.<subDomain>.<eventOrAction>.
    """
    # Type of physical device from which the event was created. A value of zero (0)
    # can be used when the source is unknown.
    type: String  = None
 
    # High-level nature of the event. By properly classifying events by a small set
    # of domain codes, a system can more easily run reports based on the types of
    # events that have occurred or been received.
    domain: String  = None
 
    # More specific nature of the event, as a further sub-categorisation of 'domain'.
    subDomain: String  = None
 
    # The most specific part of this event type. It is mainly in the form of a verb
    # that gives action to the event that just occurred.
    eventOrAction: String  = None
     