#######################################################
# 
# Meter.py
# Python implementation of the Class Meter
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:45
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61968.Metering.MeterReading import MeterReading
from TC57CIM.IEC61968.Metering.MeterMultiplier import MeterMultiplier
from TC57CIM.IEC61968.Metering.EndDevice import EndDevice

@dataclass
class Meter(EndDevice):
    """Physical asset that performs the metering role of the usage point. Used for
    measuring consumption and detection of events.
    """
    # Meter form designation per ANSI C12.10 or other applicable standard. An
    # alphanumeric designation denoting the circuit arrangement for which the meter
    # is applicable and its specific terminal arrangement.
    formNumber: String  = None
 
    # All meter readings provided by this meter.
    MeterReadings: List[MeterReading] = []
 
    # All multipliers applied at this meter.
    MeterMultipliers: List[MeterMultiplier] = []
     