#######################################################
# 
# PanPricing.py
# Python implementation of the Class PanPricing
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:12
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Integer import Integer
from TC57CIM.IEC61968.Metering.PanPricingDetail import PanPricingDetail
from TC57CIM.IEC61968.Metering.EndDeviceAction import EndDeviceAction

@dataclass
class PanPricing(EndDeviceAction):
    """PAN action/command used to issue pricing information to a PAN device.
    """
    # Unique identifier for the commodity provider.
    providerID: int  = None
 
    # All pricing details issued by this PAN pricing command/action.
    panPricingDetails: List[PanPricingDetail] = []
     