#######################################################
# 
# Reading.py
# Python implementation of the Class Reading
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:27
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.Metering.ReadingReasonKind import ReadingReasonKind
from TC57CIM.IEC61968.Metering.ReadingType import ReadingType
from TC57CIM.IEC61968.Metering.BaseReading import BaseReading
from TC57CIM.IEC61968.Metering.MeterReading import MeterReading

@dataclass
class Reading(BaseReading):
    """Specific value measured by a meter or other asset, or calculated by a system.
    Each Reading is associated with a specific ReadingType.
    """
    # Reason for this reading being taken.
    reason: ReadingReasonKind  = None
 
    # Type information for this reading value.
    readingType: Optional[ReadingType] = None
 
    # All meter readings (sets of values) containing this reading value.
    meterReadings: List[MeterReading] = []
     