#######################################################
# 
# MarketParticipant.py
# Python implementation of the Class MarketParticipant
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:44
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.Common.Organisation import Organisation
from TC57CIM.IEC62325.MarketManagement.MarketDocument import MarketDocument

@dataclass
class MarketParticipant(Organisation):
    """An identification of a party acting in a electricity market business process.
    This class is used to identify organizations that can participate in market
    management and/or market operations.
    """
    marketDocuments: List[MarketDocument] = []
     