#######################################################
# 
# WindGenTurbineType3aIEC.py
# Python implementation of the Class WindGenTurbineType3aIEC
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:41:19
# Original author: ppbr003
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Domain.PU import PU
from TC57CIM.IEC61970.Base.Domain.Seconds import Seconds
from TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics.WindGenTurbineType3IEC import WindGenTurbineType3IEC

@dataclass
class WindGenTurbineType3aIEC(WindGenTurbineType3IEC):
    """IEC Type 3A generator set model.
    
      Reference: IEC Standard 61400-27-1 Section 6.6.3.2.
    """
    # Current PI controller proportional gain (K<sub>Pc</sub>). It is type dependent
    # parameter.
    kpc: Float  = None
 
    # Electromagnetic transient reactance (x<sub>S</sub>). It is type dependent
    # parameter.
    xs: PU  = None
 
    # Current PI controller integration time constant (T<sub>Ic</sub>). It is type
    # dependent parameter.
    tic: Seconds  = None
     