#######################################################
# 
# WindContPType4aIEC.py
# Python implementation of the Class WindContPType4aIEC
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:51:23
# Original author: ppbr003
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.PU import PU
from TC57CIM.IEC61970.Base.Domain.Seconds import Seconds
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics.WindTurbineType4aIEC import WindTurbineType4aIEC

@dataclass
class WindContPType4aIEC(IdentifiedObject):
    """P control model Type 4A.
    
      Reference: IEC Standard 61400-27-1 Section 6.6.5.4.
    """
    # Maximum wind turbine power ramp rate (<i>dp</i><sub>max</sub>). It is project
    # dependent parameter.
    dpmax: PU  = None
 
    # Time constant in power order lag (<i>T</i><sub>pord</sub>). It is type
    # dependent parameter.
    tpord: Seconds  = None
 
    # Voltage measurement filter time constant (<i>T</i><sub>ufilt</sub>). It is type
    # dependent parameter.
    tufilt: Seconds  = None
 
    # Wind turbine type 4A model with which this wind control P type 4A model is
    # associated.
    windTurbineType4aIEC: Optional[WindTurbineType4aIEC] = None
     