#######################################################
# 
# WindDynamicsLookupTable.py
# Python implementation of the Class WindDynamicsLookupTable
# Generated by Enterprise Architect
# Created on:      21-May-2025 11:00:31
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics.WindLookupTableFunctionKind import WindLookupTableFunctionKind
from TC57CIM.IEC61970.Base.Domain.Integer import Integer
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics.WindPlantFreqPcontrolIEC import WindPlantFreqPcontrolIEC
from TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics.WindContCurrLimIEC import WindContCurrLimIEC
from TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics.WindContPType3IEC import WindContPType3IEC
from TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics.WindContRotorRIEC import WindContRotorRIEC

@dataclass
class WindDynamicsLookupTable(IdentifiedObject):
    """The class models a look up table for the purpose of wind standard models.
    """
    # Input value (x) for the lookup table function.
    input: float  = None
 
    # Type of the lookup table function.
    lookupTableFunctionType: WindLookupTableFunctionKind  = None
 
    # Output value (y) for the lookup table function.
    output: float  = None
 
    # Sequence numbers of the pairs of the input (x) and the output (y) of the lookup
    # table function.
    sequence: int  = None
 
    # The frequency and active power wind plant control model with which this wind
    # dynamics lookup table is associated.
    windPlantFreqPcontrolIEC: Optional[WindPlantFreqPcontrolIEC] = None
 
    # The current control limitation model with which this wind dynamics lookup table
    # is associated.
    windContCurrLimIEC: Optional[WindContCurrLimIEC] = None
 
    # The P control type 3 model with which this wind dynamics lookup table is
    # associated.
    windContPType3IEC: Optional[WindContPType3IEC] = None
 
    # The rotor resistance control model with which this wind dynamics lookup table
    # is associated.
    windContRotorRIEC: Optional[WindContRotorRIEC] = None
     