#######################################################
# 
# WindTurbineType3or4Dynamics.py
# Python implementation of the Class WindTurbineType3or4Dynamics
# Generated by Enterprise Architect
# Created on:      21-May-2025 11:00:37
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Wires.EnergySource import EnergySource
from TC57CIM.IEC61970.Dynamics.StandardModels.DynamicsFunctionBlock import DynamicsFunctionBlock
from TC57CIM.IEC61970.Dynamics.StandardInterconnections.RemoteInputSignal import RemoteInputSignal

@dataclass
class WindTurbineType3or4Dynamics(DynamicsFunctionBlock):
    """Parent class supporting relationships to wind turbines Type 3 and 4 and wind
    plant including their control models.
    """
    # Energy Source (current source) with which this wind Type 3 or 4 dynamics model
    # is asoociated.
    energySource: Optional[EnergySource] = None
 
    # Remote input signal used by these wind turbine Type 3 or 4 models.
    remoteInputSignal: Optional[RemoteInputSignal] = None
     