#######################################################
# 
# CommunicationLink.py
# Python implementation of the Class CommunicationLink
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:10
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.SCADA.RemoteUnit import RemoteUnit
from TC57CIM.IEC61970.Base.Core.PowerSystemResource import PowerSystemResource

@dataclass
class CommunicationLink(PowerSystemResource):
    """The connection to remote units is through one or more communication links.
    Reduntant links may exist. The CommunicationLink class inherit
    PowerSystemResource. The intention is to allow CommunicationLinks to have
    Measurements. These Measurements can be used to model link status as
    operational, out of service, unit failure etc.
    """
    # RTUs may be attached to communication links.
    RemoteUnits: List[RemoteUnit] = []
     