#######################################################
# 
# RemoteControl.py
# Python implementation of the Class RemoteControl
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:39
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.SCADA.RemotePoint import RemotePoint
from TC57CIM.IEC61970.Base.Meas.Control import Control

@dataclass
class RemoteControl(RemotePoint):
    """Remote controls are ouputs that are sent by the remote unit to actuators in the
    process.
    """
    # Set to true if the actuator is remotely controlled.
    remoteControlled: bool  = None
 
    # The maximum set point value accepted by the remote control point.
    actuatorMaximum: float  = None
 
    # The minimum set point value accepted by the remote control point.
    actuatorMinimum: float  = None
 
    # The Control for the RemoteControl point.
    control: Optional[Control] = None
     