#######################################################
# 
# ConcentricNeutralCableInfo.py
# Python implementation of the Class ConcentricNeutralCableInfo
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:18
# Original author: Tom
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Length import Length
from TC57CIM.IEC61970.Base.Domain.Integer import Integer
from TC57CIM.IEC61970.Base.Domain.ResistancePerLength import ResistancePerLength
from TC57CIM.IEC61968.AssetInfo.CableInfo import CableInfo

@dataclass
class ConcentricNeutralCableInfo(CableInfo):
    """Concentric neutral cable data.
    """
    # Diameter over the concentric neutral strands.
    diameterOverNeutral: Length  = None
 
    # Number of concentric neutral strands.
    neutralStrandCount: int  = None
 
    # Outside radius of the neutral strand.
    neutralStrandRadius: Length  = None
 
    # Geometric mean radius of the neutral strand.
    neutralStrandGmr: Length  = None
 
    # DC resistance per unit length of the neutral strand at 20 °C.
    neutralStrandRDC20: ResistancePerLength  = None
     