#######################################################
# 
# NoLoadTest.py
# Python implementation of the Class NoLoadTest
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:55
# Original author: Tom
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.PerCent import PerCent
from TC57CIM.IEC61970.Base.Domain.KiloActivePower import KiloActivePower
from TC57CIM.IEC61970.Base.Domain.Voltage import Voltage
from TC57CIM.IEC61968.AssetInfo.TransformerEndInfo import TransformerEndInfo
from TC57CIM.IEC61968.AssetInfo.TransformerTest import TransformerTest

@dataclass
class NoLoadTest(TransformerTest):
    """No-load test results determine core admittance parameters. They include
    exciting current and core loss measurements from applying voltage to one
    winding. The excitation may be positive sequence or zero sequence. The test may
    be repeated at different voltages to measure saturation.
    """
    # Exciting current measured from a positive-sequence or single-phase excitation
    # test.
    excitingCurrent: PerCent  = None
 
    # Exciting current measured from a zero-sequence open-circuit excitation test.
    excitingCurrentZero: PerCent  = None
 
    # Losses measured from a positive-sequence or single-phase excitation test.
    loss: KiloActivePower  = None
 
    # Losses measured from a zero-sequence excitation test.
    lossZero: KiloActivePower  = None
 
    # Voltage applied to the winding (end) during test.
    energisedEndVoltage: Voltage  = None
 
    # Transformer end that current is applied to in this no-load test.
    transformerEndInfo: Optional[TransformerEndInfo] = None
     