#######################################################
# 
# OverheadWireInfo.py
# Python implementation of the Class OverheadWireInfo
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:04
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.AssetInfo.WireInfo import WireInfo

@dataclass
class OverheadWireInfo(WireInfo):
    """Overhead wire data.
    """
    pass
