#######################################################
# 
# ShuntCompensatorInfo.py
# Python implementation of the Class ShuntCompensatorInfo
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:45
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Voltage import Voltage
from TC57CIM.IEC61970.Base.Domain.CurrentFlow import CurrentFlow
from TC57CIM.IEC61970.Base.Domain.ReactivePower import ReactivePower
from TC57CIM.IEC61970.Base.Domain.ApparentPower import ApparentPower
from TC57CIM.IEC61968.Assets.AssetInfo import AssetInfo
from TC57CIM.IEC61968.InfIEC61968.InfWiresExt.ShuntCompensatorControl import ShuntCompensatorControl

@dataclass
class ShuntCompensatorInfo(AssetInfo):
    """Properties of shunt capacitor, shunt reactor or switchable bank of shunt
    capacitor or reactor assets.
    """
    # Rated voltage.
    ratedVoltage: Voltage  = None
 
    # Rated current.
    ratedCurrent: CurrentFlow  = None
 
    # Rated reactive power.
    ratedReactivePower: ReactivePower  = None
 
    # Maximum allowed apparent power loss.
    maxPowerLoss: ApparentPower  = None
 
    shuntCompensatorControl: Optional[ShuntCompensatorControl] = None
     