#######################################################
# 
# ConformLoadGroup.py
# Python implementation of the Class ConformLoadGroup
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:11
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.LoadModel.LoadGroup import LoadGroup
from TC57CIM.IEC61970.Base.LoadModel.ConformLoad import ConformLoad
from TC57CIM.IEC61970.Base.LoadModel.ConformLoadSchedule import ConformLoadSchedule

@dataclass
class ConformLoadGroup(LoadGroup):
    """A group of loads conforming to an allocation pattern.
    """
    # Conform loads assigned to this ConformLoadGroup.
    conformLoads: List[ConformLoad] = []
 
    # The ConformLoadSchedules in the ConformLoadGroup.
    conformLoadSchedules: List[ConformLoadSchedule] = []
     