#######################################################
# 
# LoadResponseCharacteristic.py
# Python implementation of the Class LoadResponseCharacteristic
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:36
# Original author: kdd
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

@dataclass
class LoadResponseCharacteristic(IdentifiedObject):
    """Models the characteristic response of the load demand due to changes in system
    conditions such as voltage and frequency. This is not related to demand
    response.
    
      If LoadResponseCharacteristic.exponentModel is True, the voltage exponents
    are specified and used as to calculate:
    
      Active power component = Pnominal * (Voltage/cim:BaseVoltage.nominalVoltage)
    ** cim:LoadResponseCharacteristic.pVoltageExponent
    
      Reactive power component = Qnominal * (Voltage/cim:BaseVoltage.
    nominalVoltage)** cim:LoadResponseCharacteristic.qVoltageExponent
    
      Where  * means "multiply" and ** is "raised to power of".
    """
    # Indicates the exponential voltage dependency model is to be used.   If false,
    # the coefficient model is to be used.
    # The exponential voltage dependency model consist of the attributes
    # - pVoltageExponent
    # - qVoltageExponent.
    # The coefficient model consist of the attributes
    # - pConstantImpedance
    # - pConstantCurrent
    # - pConstantPower
    # - qConstantImpedance
    # - qConstantCurrent
    # - qConstantPower.
    # The sum of pConstantImpedance, pConstantCurrent and pConstantPower shall equal
    # 1.
    # The sum of qConstantImpedance, qConstantCurrent and qConstantPower shall equal
    # 1.
    exponentModel: Boolean  = None
 
    # Portion of active power load modeled as constant current.
    pConstantCurrent: Float  = None
 
    # Portion of active power load modeled as constant impedance.
    pConstantImpedance: Float  = None
 
    # Portion of active power load modeled as constant power.
    pConstantPower: Float  = None
 
    # Exponent of per unit frequency effecting active power.
    pFrequencyExponent: Float  = None
 
    # Exponent of per unit voltage effecting real power.
    pVoltageExponent: Float  = None
 
    # Portion of reactive power load modeled as constant current.
    qConstantCurrent: Float  = None
 
    # Portion of reactive power load modeled as constant impedance.
    qConstantImpedance: Float  = None
 
    # Portion of reactive power load modeled as constant power.
    qConstantPower: Float  = None
 
    # Exponent of per unit frequency effecting reactive power.
    qFrequencyExponent: Float  = None
 
    # Exponent of per unit voltage effecting reactive power.
    qVoltageExponent: Float  = None
     