#######################################################
# 
# LoadGroup.py
# Python implementation of the Class LoadGroup
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:36
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

@dataclass
class LoadGroup(IdentifiedObject):
    """The class is the third level in a hierarchical structure for grouping of loads
    for the purpose of load flow load scaling.
    """
    pass
