#######################################################
# 
# NonConformLoadGroup.py
# Python implementation of the Class NonConformLoadGroup
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:04
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.LoadModel.NonConformLoad import NonConformLoad
from TC57CIM.IEC61970.Base.LoadModel.LoadGroup import LoadGroup
from TC57CIM.IEC61970.Base.LoadModel.NonConformLoadSchedule import NonConformLoadSchedule

@dataclass
class NonConformLoadGroup(LoadGroup):
    """Loads that do not follow a daily and seasonal load variation pattern.
    """
    # Conform loads assigned to this ConformLoadGroup.
    nonConformLoads: List[NonConformLoad] = []
 
    # The NonConformLoadSchedules in the NonConformLoadGroup.
    nonConformLoadSchedules: List[NonConformLoadSchedule] = []
     