#######################################################
# 
# StationSupply.py
# Python implementation of the Class StationSupply
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:44
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Wires.EnergyConsumer import EnergyConsumer

@dataclass
class StationSupply(EnergyConsumer):
    """Station supply with load derived from the station output.
    """
    pass
