#######################################################
# 
# ResourceGroupReq.py
# Python implementation of the Class ResourceGroupReq
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:43
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC62325.MarketOperations.ReferenceData.RTO import RTO

@dataclass
class ResourceGroupReq(IdentifiedObject):
    """Ancillary service requirements for a market.
    """
    rTOs: List[RTO] = []
     