#######################################################
# 
# CashierShift.py
# Python implementation of the Class CashierShift
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:14
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Money import Money
from TC57CIM.IEC61968.PaymentMetering.PointOfSale import PointOfSale
from TC57CIM.IEC61968.PaymentMetering.Receipt import Receipt
from TC57CIM.IEC61968.PaymentMetering.Transaction import Transaction
from TC57CIM.IEC61968.PaymentMetering.Shift import Shift

@dataclass
class CashierShift(Shift):
    """The operating shift for a cashier, during which the cashier may transact
    against the cashier shift, subject to vendor shift being open.
    """
    # The amount of cash that the cashier brings to start the shift and that will be
    # taken away at the end of the shift; i.e. the cash float does not get banked.
    cashFloat: Money  = None
 
    # Point of sale that is in operation during this shift.
    pointOfSale: Optional[PointOfSale] = None
 
    # All Receipts recorded for this Shift.
    receipts: List[Receipt] = []
 
    # All transactions recorded during this cashier shift.
    transactions: List[Transaction] = []
     