#######################################################
# 
# MerchantAgreement.py
# Python implementation of the Class MerchantAgreement
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:49
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.Common.Agreement import Agreement
from TC57CIM.IEC61968.PaymentMetering.MerchantAccount import MerchantAccount

@dataclass
class MerchantAgreement(Agreement):
    """A formal controlling contractual agreement between supplier and merchant, in
    terms of which the merchant is authorised to vend tokens and receipt payments
    on behalf of the supplier. The merchant is accountable to the supplier for
    revenue collected at point of sale.
    """
    # All merchant accounts instantiated as a result of this merchant agreement.
    merchantAccounts: List[MerchantAccount] = []
     