#######################################################
# 
# PointOfSale.py
# Python implementation of the Class PointOfSale
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:09
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

@dataclass
class PointOfSale(IdentifiedObject):
    """Logical point where transactions take place with operational interaction
    between cashier and the payment system; in certain cases the point of sale
    interacts directly with the end customer, in which case the cashier might not
    be a real person: for example a self-service kiosk or over the internet.
    """
    # Local description for where this point of sale is physically located.
    location: String  = None
     