#######################################################
# 
# Transactor.py
# Python implementation of the Class Transactor
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:51:07
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

@dataclass
class Transactor(IdentifiedObject):
    """The entity that ultimately executes the transaction and which is in control of
    the process; typically this is embodied in secure software running on a server
    that may employ secure hardware encryption devices for secure transaction
    processing.
    """
    pass
