#######################################################
# 
# DescriptionID.py
# Python implementation of the Class DescriptionID
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:31
# Original author: SELAOST1
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ModelMetaData.ModelDescription.Description import Description

@dataclass
class DescriptionID(Description):
    uri: String  = None
     