#######################################################
# 
# ModelDescriptionCIMVersion.py
# Python implementation of the Class ModelDescriptionCIMVersion
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:00
# Original author: 222206
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Date import Date
from TC57CIM.IEC61970.Base.Domain.String import String

@dataclass
class ModelDescriptionCIMVersion:
    date: str  = None
 
    version: str  = None
     