#######################################################
# 
# Model.py
# Python implementation of the Class Model
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:49
# Original author: selaost1
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

@dataclass
class Model:
    created: DateTime  = None
 
    scenarioTime: DateTime  = None
 
    description: String  = None
 
    modelingAuthoritySet: URI  = None
 
    profile: URI  = None
 
    version: String  = None
 
    Models: List[Model] = []
 
    Models: List[Model] = []
     