#######################################################
# 
# EnergySourceAction.py
# Python implementation of the Class EnergySourceAction
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:42
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.Operations.TempEquipActionKind import TempEquipActionKind
from TC57CIM.IEC61968.Operations.SwitchingStep import SwitchingStep
from TC57CIM.IEC61970.Base.Wires.EnergySource import EnergySource

@dataclass
class EnergySourceAction(SwitchingStep):
    """Action on energy source as a switching step.
    """
    # Switching action to perform.
    kind: TempEquipActionKind  = None
 
    # Energy source on which this action is taken.
    EnergySource: Optional[EnergySource] = None
     