#######################################################
# 
# ServicePointOutageSummary.py
# Python implementation of the Class ServicePointOutageSummary
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:51
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Integer import Integer

@dataclass
class ServicePointOutageSummary:
    """Summary counts of service points affected by an outage. These counts are
    sometimes referred to as total and critical customer count.
    """
    # Number of all service (delivery) points affected by an outage.
    totalCount: int  = None
 
    # Number of critical service (delivery) points affected by an outage.
    criticalCount: int  = None
     