#######################################################
# 
# SwitchingStepGroup.py
# Python implementation of the Class SwitchingStepGroup
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:50
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Integer import Integer
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61968.Common.Document import Document
from TC57CIM.IEC61968.Operations.ClearanceAction import ClearanceAction
from TC57CIM.IEC61968.Operations.GenericAction import GenericAction
from TC57CIM.IEC61968.Operations.JumperAction import JumperAction
from TC57CIM.IEC61968.Operations.CutAction import CutAction
from TC57CIM.IEC61968.Operations.SwitchAction import SwitchAction
from TC57CIM.IEC61968.Operations.TagAction import TagAction
from TC57CIM.IEC61968.Operations.GroundAction import GroundAction
from TC57CIM.IEC61968.Operations.EnergySourceAction import EnergySourceAction

@dataclass
class SwitchingStepGroup(Document):
    """A logical step, grouping atomic switching steps that are important to
    distinguish when they may change topology (e.g. placing a jumper between two
    cuts).
    """
    # Order of this activity in the sequence of activities within the switching plan.
    sequenceNumber: Integer  = None
 
    # If true, the sequence number serves for presentation purposes only, and the
    # activity itself may be executed at any time.
    isFreeSequence: Boolean  = None
 
    # All clearance action steps in this group.
    ClearanceActions: List[ClearanceAction] = []
 
    # All generic action steps in this group.
    GenericActions: List[GenericAction] = []
 
    # All jumper action steps in this group.
    JumperActions: List[JumperAction] = []
 
    # All cut action steps in this group.
    CutActions: List[CutAction] = []
 
    # All switch action steps in this group.
    SwitchActions: List[SwitchAction] = []
 
    # All tag action steps in this group.
    TagActions: List[TagAction] = []
 
    # All ground action steps in this group.
    GroundActions: List[GroundAction] = []
 
    # All energy source action steps in this group.
    EnergySourceActions: List[EnergySourceAction] = []
     