#######################################################
# 
# TagAction.py
# Python implementation of the Class TagAction
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:58
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.Operations.TagActionKind import TagActionKind
from TC57CIM.IEC61968.Operations.SwitchingStep import SwitchingStep
from TC57CIM.IEC61968.Operations.OperationTag import OperationTag

@dataclass
class TagAction(SwitchingStep):
    """Action on operation tag as a switching step.
    """
    # Kind of tag action.
    kind: TagActionKind  = None
 
    # Tag associated with this tag action.
    operationTag: Optional[OperationTag] = None
     