#######################################################
# 
# TempEquipActionKind.py
# Python implementation of the Class TempEquipActionKind
# Generated by Enterprise Architect
# Created on:      21-May-2025 11:00:08
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class TempEquipActionKind(Enum):
    """Kind of action on temporary equipment (such as cut, jumper, ground, energy
    source).
    """
    # Place the jumper (close) or the cut (open).
    place = auto()
    # Remove the jumper (open) or the cut (close).
    remove = auto()