#######################################################
# 
# BankAccount.py
# Python implementation of the Class BankAccount
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:07
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61968.Common.Document import Document
from TC57CIM.IEC61968.InfIEC61968.InfCommon.Bank import Bank

@dataclass
class BankAccount(Document):
    """Bank account.
    """
    # Account reference number.
    accountNumber: str  = None
 
    # Bank that provides this BankAccount.
    bank: Optional[Bank] = None
     