#######################################################
# 
# PersonDocumentRole.py
# Python implementation of the Class PersonDocumentRole
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:14
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.InfIEC61968.InfCommon.Role import Role

@dataclass
class PersonDocumentRole(Role):
    """Roles played between Persons and Documents.
    """
    pass
