#######################################################
# 
# PersonPropertyRole.py
# Python implementation of the Class PersonPropertyRole
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:14
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.InfIEC61968.InfCommon.Role import Role

@dataclass
class PersonPropertyRole(Role):
    """The role of a person relative to a given piece of property. Examples of roles
    include: owner, renter, contractor, etc.
    """
    pass
