#######################################################
# 
# Ratio.py
# Python implementation of the Class Ratio
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:26
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float

@dataclass
class Ratio:
    """Fraction specified explicitly with a numerator and denominator, which can be
    used to calculate the quotient.
    """
    # The part of a fraction that is above the line and signifies the number to be
    # divided by the denominator.
    numerator: Float  = None
 
    # The part of a fraction that is below the line and that functions as the divisor
    # of the numerator.
    denominator: Float  = None
     