#######################################################
# 
# SkillLevelKind.py
# Python implementation of the Class SkillLevelKind
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:53
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class SkillLevelKind(Enum):
    """Kind of skill level.
    """
    master = auto()
    standard = auto()
    apprentice = auto()
    other = auto()