#######################################################
# 
# ACDCTerminal.py
# Python implementation of the Class ACDCTerminal
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:37:48
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.Core.IdentifiedObject import IdentifiedObject

@dataclass
class ACDCTerminal(IdentifiedObject):
    """An electrical connection point (AC or DC) to a piece of conducting equipment.
    Terminals are connected at physical connection points called connectivity nodes.
    """
    pass
