#######################################################
# 
# InspectionDataSet.py
# Python implementation of the Class InspectionDataSet
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:39
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61968.Assets.ProcedureDataSet import ProcedureDataSet

@dataclass
class InspectionDataSet(ProcedureDataSet):
    """Documents the result of one inspection, for a given attribute of an asset.
    """
    # Description of the conditions of the location where the asset resides.
    locationCondition: str  = None
     