#######################################################
# 
# BranchGroup.py
# Python implementation of the Class BranchGroup
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:02
# Original author: kdd
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.ActivePower import ActivePower
from TC57CIM.IEC61970.Base.Domain.ReactivePower import ReactivePower
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61970.Base.OperationalLimits.BranchGroupTerminal import BranchGroupTerminal
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

@dataclass
class BranchGroup(IdentifiedObject):
    """A group of branch terminals whose directed flow summation is to be monitored. A
    branch group need not form a cutset of the network.
    """
    # The maximum active power flow.
    maximumActivePower: ActivePower  = None
 
    # The maximum reactive power flow.
    maximumReactivePower: ReactivePower  = None
 
    # The minimum active power flow.
    minimumActivePower: ActivePower  = None
 
    # The minimum reactive power flow.
    minimumReactivePower: ReactivePower  = None
 
    # Monitor the active power flow.
    monitorActivePower: Boolean  = None
 
    # Monitor the reactive power flow.
    monitorReactivePower: Boolean  = None
 
    # The directed branch group terminals to be summed.
    branchGroupTerminals: List[BranchGroupTerminal] = []
     