#######################################################
# 
# OperationalLimitSet.py
# Python implementation of the Class OperationalLimitSet
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:57
# Original author: kdd
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.OperationalLimits.OperationalLimit import OperationalLimit
from TC57CIM.IEC61970.Base.Core.Equipment import Equipment
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC61970.Base.Core.ACDCTerminal import ACDCTerminal

@dataclass
class OperationalLimitSet(IdentifiedObject):
    """A set of limits associated with equipment.  Sets of limits might apply to a
    specific temperature, or season for example. A set of limits may contain
    different severities of limit levels that would apply to the same equipment.
    The set may contain limits of different types such as apparent power and
    current limits or high and low voltage limits  that are logically applied
    together as a set.
    """
    # Values of equipment limits.
    OperationalLimits: List[OperationalLimit] = []
 
    # The equipment to which the limit set applies.
    Equipment: Optional[Equipment] = None
 
    ACDCTerminal: Optional[ACDCTerminal] = None
     