#######################################################
# 
# ViolationLimit.py
# Python implementation of the Class ViolationLimit
# Generated by Enterprise Architect
# Created on:      21-May-2025 11:00:25
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61970.Base.Meas.Limit import Limit
from TC57CIM.IEC62325.MarketOperations.ReferenceData.Flowgate import Flowgate
from TC57CIM.IEC62325.MarketOperations.MarketOpCommon.MktMeasurement import MktMeasurement
from TC57CIM.IEC62325.MarketOperations.MarketOpCommon.MktOrganisation import MktOrganisation

@dataclass
class ViolationLimit(Limit):
    """A type of limit that indicates if it is enforced and, through association, the
    organisation responsible for setting the limit.
    """
    # True if limit is enforced. 
    enforced: bool  = None
 
    flowgate: Optional[Flowgate] = None
 
    mktMeasurement: Optional[MktMeasurement] = None
 
    mktOrganisations: List[MktOrganisation] = []
     