#######################################################
# 
# ProprietaryParameterDynamics.py
# Python implementation of the Class ProprietaryParameterDynamics
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:19
# Original author: ppbr003
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Integer import Integer
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Boolean import Boolean
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Simple_Float import Simple_Float
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.UserDefinedModels.LoadUserDefined import LoadUserDefined
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.UserDefinedModels.VoltageCompensatorUserDefined import VoltageCompensatorUserDefined
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.UserDefinedModels.PFVArControllerType2UserDefined import PFVArControllerType2UserDefined
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.UserDefinedModels.VoltageAdjusterUserDefined import VoltageAdjusterUserDefined
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.UserDefinedModels.PFVArControllerType1UserDefined import PFVArControllerType1UserDefined
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.UserDefinedModels.DiscontinuousExcitationControlUserDefined import DiscontinuousExcitationControlUserDefined
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.UserDefinedModels.PowerSystemStabilizerUserDefined import PowerSystemStabilizerUserDefined
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.UserDefinedModels.UnderexcitationLimiterUserDefined import UnderexcitationLimiterUserDefined
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.UserDefinedModels.OverexcitationLimiterUserDefined import OverexcitationLimiterUserDefined
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.UserDefinedModels.ExcitationSystemUserDefined import ExcitationSystemUserDefined
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.UserDefinedModels.MechanicalLoadUserDefined import MechanicalLoadUserDefined
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.UserDefinedModels.TurbineLoadControllerUserDefined import TurbineLoadControllerUserDefined
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.UserDefinedModels.TurbineGovernorUserDefined import TurbineGovernorUserDefined
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.UserDefinedModels.AsynchronousMachineUserDefined import AsynchronousMachineUserDefined
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.UserDefinedModels.SynchronousMachineUserDefined import SynchronousMachineUserDefined
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.UserDefinedModels.WindType3or4UserDefined import WindType3or4UserDefined
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.UserDefinedModels.WindType1or2UserDefined import WindType1or2UserDefined
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.UserDefinedModels.WindPlantUserDefined import WindPlantUserDefined

@dataclass
class ProprietaryParameterDynamics:
    """Supports definition of one or more parameters of several different datatypes
    for use by proprietary user-defined models.  NOTE: This class does not inherit
    from IdentifiedObject since it is not intended that a single instance of it be
    referenced by more than one proprietary user-defined model instance.
    """
    # Sequence number of the parameter among the set of parameters associated with
    # the related proprietary user-defined model.
    parameterNumber: Integer  = None
 
    # Used for boolean parameter value. If this attribute is populated,
    # integerParameterValue and floatParameterValue will not be.
    booleanParameterValue: Boolean  = None
 
    # Used for integer parameter value.  If this attribute is populated,
    # booleanParameterValue and floatParameterValue will not be.
    integerParameterValue: Integer  = None
 
    # Used for floating point parameter value.  If this attribute is populated,
    # booleanParameterValue and integerParameterValue will not be.
    floatParameterValue: Simple_Float  = None
 
    # Proprietary user-defined model with which this parameter is associated.
    loadUserDefined: Optional[LoadUserDefined] = None
 
    # Proprietary user-defined model with which this parameter is associated.
    voltageCompensatorUserDefined: Optional[VoltageCompensatorUserDefined] = None
 
    # Proprietary user-defined model with which this parameter is associated.
    pFVArControllerType2UserDefined: Optional[PFVArControllerType2UserDefined] = None
 
    # Proprietary user-defined model with which this parameter is associated.
    voltageAdjusterUserDefined: Optional[VoltageAdjusterUserDefined] = None
 
    # Proprietary user-defined model with which this parameter is associated.
    pFVArControllerType1UserDefined: Optional[PFVArControllerType1UserDefined] = None
 
    # Proprietary user-defined model with which this parameter is associated.
    discontinuousExcitationControlUserDefined: Optional[DiscontinuousExcitationControlUserDefined] = None
 
    # Proprietary user-defined model with which this parameter is associated.
    powerSystemStabilizerUserDefined: Optional[PowerSystemStabilizerUserDefined] = None
 
    # Proprietary user-defined model with which this parameter is associated.
    underexcitationLimiterUserDefined: Optional[UnderexcitationLimiterUserDefined] = None
 
    # Proprietary user-defined model with which this parameter is associated.
    overexcitationLimiterUserDefined: Optional[OverexcitationLimiterUserDefined] = None
 
    # Proprietary user-defined model with which this parameter is associated.
    excitationSystemUserDefined: Optional[ExcitationSystemUserDefined] = None
 
    # Proprietary user-defined model with which this parameter is associated.
    mechanicalLoadUserDefined: Optional[MechanicalLoadUserDefined] = None
 
    # Proprietary user-defined model with which this parameter is associated.
    turbineLoadControllerUserDefined: Optional[TurbineLoadControllerUserDefined] = None
 
    # Proprietary user-defined model with which this parameter is associated.
    turbineGovernorUserDefined: Optional[TurbineGovernorUserDefined] = None
 
    # Proprietary user-defined model with which this parameter is associated.
    asynchronousMachineUserDefined: Optional[AsynchronousMachineUserDefined] = None
 
    # Proprietary user-defined model with which this parameter is associated.
    synchronousMachineUserDefined: Optional[SynchronousMachineUserDefined] = None
 
    # Proprietary user-defined model with which this parameter is associated.
    windType3or4UserDefined: Optional[WindType3or4UserDefined] = None
 
    # Proprietary user-defined model with which this parameter is associated.
    windType1or2UserDefined: Optional[WindType1or2UserDefined] = None
 
    # Proprietary user-defined model with which this parameter is associated.
    windPlantUserDefined: Optional[WindPlantUserDefined] = None
     