#######################################################
# 
# TurbineGovernorUserDefined.py
# Python implementation of the Class TurbineGovernorUserDefined
# Generated by Enterprise Architect
# Created on:      21-May-2025 11:00:19
# Original author: ppbr003
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Boolean import Boolean
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.TurbineGovernorDynamics.TurbineGovernorDynamics import TurbineGovernorDynamics

@dataclass
class TurbineGovernorUserDefined(TurbineGovernorDynamics):
    """Turbine-governor function block whose dynamic behaviour is described by <font
    color="#0f0f0f">a user-defined model.</font>
    """
    # Behaviour is based on proprietary model as opposed to detailed model.
    # true = user-defined model is proprietary with behaviour mutually understood by
    # sending and receiving applications and parameters passed as general attributes
    # false = user-defined model is explicitly defined in terms of control blocks and
    # their input and output signals.
    proprietary: bool  = None
     