#######################################################
# 
# ActivePowerPerFrequency.py
# Python implementation of the Class ActivePowerPerFrequency
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:37:50
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.UnitMultiplier import UnitMultiplier
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.UnitSymbol import UnitSymbol
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Float import Float

@dataclass
class ActivePowerPerFrequency:
    """Active power variation with frequency.
    """
    denominatorMultiplier: UnitMultiplier =  UnitMultiplier.none
 
    denominatorUnit: UnitSymbol =  UnitSymbol.Hz
 
    multiplier: UnitMultiplier =  UnitMultiplier.M
 
    unit: UnitSymbol =  UnitSymbol.W
 
    value: Float  = None
     