#######################################################
# 
# ApparentPower.py
# Python implementation of the Class ApparentPower
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:37:54
# Original author: andre
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Float import Float
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.UnitSymbol import UnitSymbol
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.UnitMultiplier import UnitMultiplier

@dataclass
class ApparentPower:
    """Product of the RMS value of the voltage and the RMS value of the current.
    """
    value: Float  = None
 
    unit: UnitSymbol =  UnitSymbol.VA
 
    multiplier: UnitMultiplier =  UnitMultiplier.M
     