#######################################################
# 
# Float.py
# Python implementation of the Class Float
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:16
# Original author: Jean-Luc
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

@dataclass
class Float:
    """A floating point number. The range is unspecified and not limited.
    """
    pass
