#######################################################
# 
# Frequency.py
# Python implementation of the Class Frequency
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:08
# Original author: Jean-Luc
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Float import Float
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.UnitSymbol import UnitSymbol
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.UnitMultiplier import UnitMultiplier

@dataclass
class Frequency:
    """Cycles per second.
    """
    value: Float  = None
 
    unit: UnitSymbol =  UnitSymbol.Hz
 
    multiplier: UnitMultiplier =  UnitMultiplier.none
     