#######################################################
# 
# Inductance.py
# Python implementation of the Class Inductance
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:31
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Float import Float
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.UnitSymbol import UnitSymbol
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.UnitMultiplier import UnitMultiplier

@dataclass
class Inductance:
    """Inductive part of reactance (imaginary part of impedance), at rated frequency.
    """
    value: Float  = None
 
    unit: UnitSymbol =  UnitSymbol.H
 
    multiplier: UnitMultiplier =  UnitMultiplier.none
     