#######################################################
# 
# MonthDayInterval.py
# Python implementation of the Class MonthDayInterval
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:50
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.MonthDay import MonthDay

@dataclass
class MonthDayInterval:
    """Interval between two times specified as mont and date.
    """
    # End time of this interval.
    end: MonthDay  = None
 
    # Start time of this interval.
    start: MonthDay  = None
     