#######################################################
# 
# Reactance.py
# Python implementation of the Class Reactance
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:27
# Original author: Jean-Luc
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Float import Float
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.UnitSymbol import UnitSymbol
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.UnitMultiplier import UnitMultiplier

@dataclass
class Reactance:
    """Reactance (imaginary part of impedance), at rated frequency.
    """
    value: Float  = None
 
    unit: UnitSymbol =  UnitSymbol.ohm
 
    multiplier: UnitMultiplier =  UnitMultiplier.none
     