#######################################################
# 
# AssetPropertyCurve.py
# Python implementation of the Class AssetPropertyCurve
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:47:54
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Core.Curve import Curve

@dataclass
class AssetPropertyCurve(Curve):
    """An Asset Property that is described through curves rather than as a data point.
    The relationship is to be defined between an independent variable (X-axis) and
    one or two dependent variables (Y1-axis and Y2-axis).
    """
    pass
