#######################################################
# 
# BushingInsulationPfTestKind.py
# Python implementation of the Class BushingInsulationPfTestKind
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:05
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class BushingInsulationPfTestKind(Enum):
    """Kind of PF test for bushing insulation.
    """
    # Power factor tap-to-ground.
    c1 = auto()
    # Power factor tap-to-conductor.
    c2 = auto()