#######################################################
# 
# CoolingKind.py
# Python implementation of the Class CoolingKind
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:18
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class CoolingKind(Enum):
    """Kind of cooling.
    """
    selfCooling = auto()
    forcedAir = auto()
    forcedOilAndAir = auto()
    other = auto()