#######################################################
# 
# FACTSDevice.py
# Python implementation of the Class FACTSDevice
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:05
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.InfIEC61968.InfAssets.FACTSDeviceKind import FACTSDeviceKind
from TC57CIM.IEC61968.Assets.Asset import Asset

@dataclass
class FACTSDevice(Asset):
    """FACTS device asset.
    """
    # Kind of FACTS device.
    kind: FACTSDeviceKind  = None
     