#######################################################
# 
# FinancialInfo.py
# Python implementation of the Class FinancialInfo
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:07
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Money import Money
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Domain.IntegerQuantity import IntegerQuantity
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC61968.Assets.Asset import Asset

@dataclass
class FinancialInfo(IdentifiedObject):
    """Various current financial properties associated with a particular asset.
    Historical properties may be determined by ActivityRecords associated with the
    asset.
    """
    # Value of asset as of 'valueDateTime'.
    financialValue: Money  = None
 
    # Date and time at which the financial value was last established.
    valueDateTime: DateTime  = None
 
    # Date and time asset's financial value was put in plant for regulatory
    # accounting purposes (e.g., for rate base calculations). This is sometime
    # referred to as the "in-service date".
    plantTransferDateTime: DateTime  = None
 
    # Date and time warranty on asset expires.
    warrantyEndDateTime: DateTime  = None
 
    # Date and time asset was purchased.
    purchaseDateTime: DateTime  = None
 
    # Purchase order identifier.
    purchaseOrderNumber: String  = None
 
    # The actual purchase cost of this particular asset.
    actualPurchaseCost: Money  = None
 
    # The account to which this actual material item is charged.
    account: String  = None
 
    # The quantity of the asset if per unit length, for example conductor.
    quantity: IntegerQuantity  = None
 
    # Description of the cost.
    costDescription: String  = None
 
    # Type of cost to which this Material Item belongs.
    costType: String  = None
 
    asset: Optional[Asset] = None
     