#######################################################
# 
# StreetlightLampKind.py
# Python implementation of the Class StreetlightLampKind
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:57
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class StreetlightLampKind(Enum):
    """Kind of lamp for the streetlight.
    """
    highPressureSodium = auto()
    mercuryVapor = auto()
    metalHalide = auto()
    other = auto()