#######################################################
# 
# StructureSupportKind.py
# Python implementation of the Class StructureSupportKind
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:46
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class StructureSupportKind(Enum):
    """Kind of structure support.
    """
    anchor = auto()
    guy = auto()