#######################################################
# 
# AceTariffType.py
# Python implementation of the Class AceTariffType
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:37:49
# Original author: mspivbe2
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC62325.MarketManagement.Unit import Unit
from TC57CIM.IEC62325.MarketManagement.MarketDocument import MarketDocument

@dataclass
class AceTariffType:
    """The Area Control Error tariff type that is applied or used.
    """
    # The coded type of an ACE tariff.
    type: String  = None
 
    Units: List[Unit] = []
 
    MarketDocuments: List[MarketDocument] = []
     