#######################################################
# 
# BidTimeSeries.py
# Python implementation of the Class BidTimeSeries
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:10
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Domain.Decimal import Decimal
from TC57CIM.IEC62325.MarketManagement.TimeSeries import TimeSeries

@dataclass
class BidTimeSeries(TimeSeries):
    """The formal specification of specific characteristics related to a bid.
    """
    # Indication that  the values in the period are considered as a whole. They
    # cannot be changed or subdivided.
    blockBid: str  = None
 
    # The coded identification of the energy flow.
    direction: str  = None
 
    # An indication whether or not each element of the bid may be partially accepted
    # or not.
    divisible: str  = None
 
    # Unique identification associated with all linked bids.
    linkedBidsIdentification: str  = None
 
    # The minimum quantity of energy that can be activated at a given time interval.
    minimumActivationQuantity: Decimal  = None
 
    # The minimum increment that can be applied for an increase in an activation
    # request.
    stepIncrementQuantity: Decimal  = None
     