#######################################################
# 
# MarketAgreement.py
# Python implementation of the Class MarketAgreement
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:42
# Original author: effantin-cyr
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC62325.MarketManagement.MarketDocument import MarketDocument

@dataclass
class MarketAgreement(MarketDocument):
    """An identification  or eventually the contents of an agreement between two or
    more parties.
    """
    pass
