#######################################################
# 
# MktPSRType.py
# Python implementation of the Class MktPSRType
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:59
# Original author: mspivbe2
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Core.PSRType import PSRType
from TC57CIM.IEC62325.MarketManagement.TimeSeries import TimeSeries

@dataclass
class MktPSRType(PSRType):
    """The type of a power system resource.
    """
    # The coded type of a power system resource.
    psrType: str  = None
 
    timeSeriess: List[TimeSeries] = []
     