#######################################################
# 
# VsConverter.py
# Python implementation of the Class VsConverter
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:51:21
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.AngleDegrees import AngleDegrees
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Voltage import Voltage
from ENTSOE.CommonGridModelExchangeStandard.StateVariablesProfile.DC.ACDCConverter import ACDCConverter

@dataclass
class VsConverter(ACDCConverter):
    """DC side of the voltage source converter (VSC).
    """
    # Angle between uf and uc. Converter state variable used in power flow.
    delta: AngleDegrees  = None
 
    # Filter bus voltage. Converter state variable, result from power flow.
    uf: Voltage  = None
     