#######################################################
# 
# AccumulatorValue.py
# Python implementation of the Class AccumulatorValue
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:37:47
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Integer import Integer
from TC57CIM.IEC61970.Base.Meas.MeasurementValue import MeasurementValue

@dataclass
class AccumulatorValue(MeasurementValue):
    """AccumulatorValue represents an accumulated (counted) MeasurementValue.
    """
    # The value to supervise. The value is positive.
    value: Integer  = None
     