#######################################################
# 
# AccumulatorLimitSet.py
# Python implementation of the Class AccumulatorLimitSet
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:47:43
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Meas.AccumulatorLimit import AccumulatorLimit
from TC57CIM.IEC61970.Base.Meas.LimitSet import LimitSet

@dataclass
class AccumulatorLimitSet(LimitSet):
    """An AccumulatorLimitSet specifies a set of Limits that are associated with an
    Accumulator measurement.
    """
    # The limit values used for supervision of Measurements.
    accumulatorLimits: List[AccumulatorLimit] = []
     