#######################################################
# 
# AnalogLimit.py
# Python implementation of the Class AnalogLimit
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:37:53
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Meas.Limit import Limit

@dataclass
class AnalogLimit(Limit):
    """Limit values for Analog measurements.
    """
    # The value to supervise against.
    value: Float  = None
     