#######################################################
# 
# Command.py
# Python implementation of the Class Command
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:17
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Integer import Integer
from TC57CIM.IEC61970.Base.Meas.ValueAliasSet import ValueAliasSet
from TC57CIM.IEC61970.Base.Meas.Control import Control
from TC57CIM.IEC61970.InfIEC61970.ICCP.ICCPCommandPoint import ICCPCommandPoint

@dataclass
class Command(Control):
    """A Command is a discrete control used for supervisory control.
    """
    # Normal value for Control.value e.g. used for percentage scaling.
    normalValue: int  = None
 
    # The value representing the actuator output.
    value: int  = None
 
    # The ValueAliasSet used for translation of a Control value to a name.
    valueAliasSet: Optional[ValueAliasSet] = None
 
    iCCPCommandPoints: List[ICCPCommandPoint] = []
     