#######################################################
# 
# Discrete.py
# Python implementation of the Class Discrete
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:34
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Integer import Integer
from TC57CIM.IEC61970.Base.Meas.Measurement import Measurement
from TC57CIM.IEC61970.Base.Meas.DiscreteValue import DiscreteValue

@dataclass
class Discrete(Measurement):
    """Discrete represents a discrete Measurement, i.e. a Measurement representing
    discrete values, e.g. a Breaker position.
    """
    # Normal value range maximum for any of the MeasurementValue.values. Used for
    # scaling, e.g. in bar graphs or of telemetered raw values.
    maxValue: Integer  = None
 
    # Normal value range minimum for any of the MeasurementValue.values. Used for
    # scaling, e.g. in bar graphs or of telemetered raw values.
    minValue: Integer  = None
 
    # Normal measurement value, e.g., used for percentage calculations.
    normalValue: Integer  = None
 
    # The values connected to this measurement.
    discreteValues: List[DiscreteValue] = []
     