#######################################################
# 
# DiscreteCommand.py
# Python implementation of the Class DiscreteCommand
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:34
# Original author: selaost1
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Meas.Command import Command

@dataclass
class DiscreteCommand(Command):
    pass
