#######################################################
# 
# MeasurementValueQuality.py
# Python implementation of the Class MeasurementValueQuality
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:55
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Meas.Quality61850 import Quality61850

@dataclass
class MeasurementValueQuality(Quality61850):
    """Measurement quality flags. Bits 0-10 are defined for substation automation in
    draft IEC 61850 part 7-3. Bits 11-15 are reserved for future expansion by that
    document. Bits 16-31 are reserved for EMS applications.
    """
    pass
