#######################################################
# 
# StringMeasurement.py
# Python implementation of the Class StringMeasurement
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:45
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Meas.Measurement import Measurement

@dataclass
class StringMeasurement(Measurement):
    """StringMeasurement represents a measurement with values of type string.
    """
    pass
