#######################################################
# 
# DynamicsFunctionBlock.py
# Python implementation of the Class DynamicsFunctionBlock
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:46
# Original author: ppbr003
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

@dataclass
class DynamicsFunctionBlock(IdentifiedObject):
    """Abstract parent class for all Dynamics function blocks.
    """
    # Function block used indicator.
    # true = use of function block is enabled
    # false = use of function block is disabled.
    enabled: bool  = None
     