#######################################################
# 
# CombinedCycleTransitionState.py
# Python implementation of the Class CombinedCycleTransitionState
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:16
# Original author: mspivbe2
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean

@dataclass
class CombinedCycleTransitionState:
    """Defines the available from and to Transition States for the Combine Cycle
    Configurations.
    """
    # Flag indicating whether this is an UP transition.
    # If not, it is a DOWN transition.
    upTransition: bool  = None
     