#######################################################
# 
# FlowgatePartner.py
# Python implementation of the Class FlowgatePartner
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:07
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC62325.MarketOperations.ReferenceData.FlowgateValue import FlowgateValue

@dataclass
class FlowgatePartner(IdentifiedObject):
    """Flowgate defined partner
    """
    FlowgateValue: Optional[FlowgateValue] = None
     