#######################################################
# 
# FuelRegion.py
# Python implementation of the Class FuelRegion
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:10
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC62325.MarketOperations.ReferenceData.RegisteredGenerator import RegisteredGenerator

@dataclass
class FuelRegion(IdentifiedObject):
    """Indication of region for fuel inventory purposes
    """
    # end effective date
    endEffectiveDate: DateTime  = None
 
    # The type of fuel region
    fuelRegionType: String  = None
 
    # Time of last update
    lastModified: DateTime  = None
 
    # start effective date
    startEffectiveDate: DateTime  = None
 
    registeredGenerators: List[RegisteredGenerator] = []
     