#######################################################
# 
# GasPrice.py
# Python implementation of the Class GasPrice
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:19
# Original author: USRAKHA
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC62325.MarketOperations.ReferenceData.FuelRegion import FuelRegion

@dataclass
class GasPrice:
    """Price of gas in monetary units
    """
    # The average natural gas price at a defined fuel region.
    gasPriceIndex: float  = None
 
    fuelRegion: Optional[FuelRegion] = None
     