#######################################################
# 
# IndividualPnode.py
# Python implementation of the Class IndividualPnode
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:31
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC62325.MarketOperations.ReferenceData.Pnode import Pnode
from TC57CIM.IEC62325.MarketOperations.ReferenceData.PnodeDistributionFactor import PnodeDistributionFactor
from TC57CIM.IEC62325.MarketOperations.MarketSystem.ExternalInputs.GenDistributionFactor import GenDistributionFactor
from TC57CIM.IEC62325.MarketOperations.MarketSystem.ExternalInputs.LoadDistributionFactor import LoadDistributionFactor
from TC57CIM.IEC62325.MarketOperations.MarketOpCommon.MktConnectivityNode import MktConnectivityNode

@dataclass
class IndividualPnode(Pnode):
    """Individual pricing node based on Pnode
    """
    pnodeDistributionFactors: List[PnodeDistributionFactor] = []
 
    genDistributionFactor: Optional[GenDistributionFactor] = None
 
    loadDistributionFactor: Optional[LoadDistributionFactor] = None
 
    mktConnectivityNode: Optional[MktConnectivityNode] = None
     