#######################################################
# 
# LoadRatio.py
# Python implementation of the Class LoadRatio
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:36
# Original author: USRAKHA
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC61970.Base.Domain.PerCent import PerCent
from TC57CIM.IEC62325.MarketOperations.ReferenceData.SchedulingCoordinator import SchedulingCoordinator

@dataclass
class LoadRatio:
    """Representing the ratio of the load share for the associated SC.
    """
    # Interval Start Time
    intervalStartTime: DateTime  = None
 
    # Interval End Time
    intervalEndTime: DateTime  = None
 
    # Share in percentage of total Market load for the selected time interval.
    share: PerCent  = None
 
    SchedulingCoordinator: Optional[SchedulingCoordinator] = None
     