#######################################################
# 
# MarketPerson.py
# Python implementation of the Class MarketPerson
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:51
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61968.Common.ElectronicAddress import ElectronicAddress
from TC57CIM.IEC61968.Common.TelephoneNumber import TelephoneNumber
from TC57CIM.IEC61968.Common.Status import Status
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC62325.MarketOperations.ReferenceData.MarketSkill import MarketSkill

@dataclass
class MarketPerson(IdentifiedObject):
    """General purpose information for name and other information to contact people.
    """
    # Category of this person relative to utility operations, classified according to
    # the utility's corporate standards and practices. Examples include employee,
    # contractor, agent, not affiliated, etc.
    # This field is not used to indicate whether this person is a customer of the
    # utility. Often an employee or contractor is also a customer. Customer
    # information is gained with relationship to Organisation and CustomerData. In
    # similar fashion, this field does not indicate the various roles this person may
    # fill as part of utility operations.
    category: str  = None
 
    # Alternate Electronic address.
    electronicAddressAlternate: ElectronicAddress  = None
 
    # Primary Electronic address.
    electronicAddressPrimary: ElectronicAddress  = None
 
    # Person's first name.
    firstName: str  = None
 
    # Unique identifier for person relative to its governing authority, for example a
    # federal tax identifier (such as a Social Security number in the United States).
    governmentID: str  = None
 
    # Landline phone number.
    landlinePhone: TelephoneNumber  = None
 
    # Person's last (family, sir) name.
    lastName: str  = None
 
    # Middle name(s) or initial(s).
    mName: str  = None
 
    # Mobile phone number.
    mobilePhone: TelephoneNumber  = None
 
    # A prefix or title for the person's name, such as Miss, Mister, Doctor, etc.
    prefix: str  = None
 
    # Special service needs for the person (contact) are described; examples include
    # life support, etc.
    specialNeed: str  = None
 
    status: Status  = None
 
    # A suffix for the person's name, such as II, III, etc.
    suffix: str  = None
 
    # The user name for the person; required to log in.
    userID: str  = None
 
    marketSkills: List[MarketSkill] = []
     