#######################################################
# 
# MaxStartUpCostCurve.py
# Python implementation of the Class MaxStartUpCostCurve
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:42
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Core.Curve import Curve

@dataclass
class MaxStartUpCostCurve(Curve):
    """The maximum Startup costs and time as a function of down time.  Relationship
    between unit startup cost (Y1-axis) vs. unit elapsed down time (X-axis). This
    is used to validate the information provided in the Bid.
    """
    pass
