#######################################################
# 
# MeteredSubSystem.py
# Python implementation of the Class MeteredSubSystem
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:45
# Original author: mspivbe2
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC62325.MarketOperations.ReferenceData.MSSZone import MSSZone
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

@dataclass
class MeteredSubSystem(IdentifiedObject):
    """A metered subsystem
    """
    MSSZones: List[MSSZone] = []
     