#######################################################
# 
# MktContingency.py
# Python implementation of the Class MktContingency
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:47
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Contingency.Contingency import Contingency

@dataclass
class MktContingency(Contingency):
    """Subclass of IEC61970:Contingency
    """
    # load change flag
    # Flag that indicates whether load rollover and load pickup should be processed
    # for this contingency
    loadRolloverFlag: Boolean  = None
 
    # ltc enable flag
    # Flag that indicates if LTCs regulate voltage during the solution of the
    # contingency
    ltcControlFlag: Boolean  = None
 
    # Participation Factor flag
    # An indication which set of generator participation factors should be used to re-
    # allocate generation in this contingency
    participationFactorSet: String  = None
 
    # sceening flag for outage
    # Flag that indicated whether screening is bypassed for the contingency
    screeningFlag: Boolean  = None
     