#######################################################
# 
# MktCombinedCyclePlant.py
# Python implementation of the Class MktCombinedCyclePlant
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:47
# Original author: mspivbe2
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Generation.Production.CombinedCyclePlant import CombinedCyclePlant
from TC57CIM.IEC62325.MarketOperations.ReferenceData.AggregatedPnode import AggregatedPnode

@dataclass
class MktCombinedCyclePlant(CombinedCyclePlant):
    """Subclass of Production: CombinedCyclePlant from IEC61970 package.
      A set of combustion turbines and steam turbines where the exhaust heat from
    the combustion turbines is recovered to make steam for the steam turbines,
    resulting in greater overall plant efficiency
    """
    AggregatedPnode: Optional[AggregatedPnode] = None
     