#######################################################
# 
# MktConductingEquipment.py
# Python implementation of the Class MktConductingEquipment
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:47
# Original author: mspivbe2
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Core.ConductingEquipment import ConductingEquipment

@dataclass
class MktConductingEquipment(ConductingEquipment):
    """Subclass of IEC61970:Core:ConductingEquipment
    """
    pass
