#######################################################
# 
# MktThermalGeneratingUnit.py
# Python implementation of the Class MktThermalGeneratingUnit
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:53
# Original author: mspivbe2
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Generation.Production.ThermalGeneratingUnit import ThermalGeneratingUnit

@dataclass
class MktThermalGeneratingUnit(ThermalGeneratingUnit):
    """Subclass of ThermalGeneratingUnit from Production Package in IEC61970.
    """
    pass
