#######################################################
# 
# OrgResOwnership.py
# Python implementation of the Class OrgResOwnership
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:02
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC62325.MarketOperations.MktDomain.ResourceAssnType import ResourceAssnType
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC62325.MarketOperations.MktDomain.YesNo import YesNo
from TC57CIM.IEC61970.Base.Domain.PerCent import PerCent
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC62325.MarketOperations.MarketOpCommon.MktOrganisation import MktOrganisation

@dataclass
class OrgResOwnership(IdentifiedObject):
    """This class model the ownership percent and type of ownership between resource
    and organisation
    """
    # association type for the association between Organisation and Resource:
    asscType: ResourceAssnType  = None
 
    # end effective date
    endEffectiveDate: DateTime  = None
 
    # Flag to indicate that the SC representing the Resource is the Master SC.
    masterSchedulingCoordinatorFlag: YesNo  = None
 
    # ownership percentage for each resource
    ownershipPercent: PerCent  = None
 
    # start effective date
    startEffectiveDate: DateTime  = None
 
    mktOrganisation: Optional[MktOrganisation] = None
     