#######################################################
# 
# AssetFunction.py
# Python implementation of the Class AssetFunction
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:03
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

@dataclass
class AssetFunction(IdentifiedObject):
    """Function performed by an asset.
    """
    # Name of program.
    programID: str  = None
 
    # Firmware version.
    firmwareID: str  = None
 
    # Hardware version.
    hardwareID: str  = None
 
    # Password needed to access this function.
    password: str  = None
 
    # Configuration specified for this function.
    configID: str  = None
     