#######################################################
# 
# AssetModelUsageKind.py
# Python implementation of the Class AssetModelUsageKind
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:47:54
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class AssetModelUsageKind(Enum):
    """Usage for an asset model.
    """
    # Asset model is intended for use in distribution overhead network.
    distributionOverhead = auto()
    # Asset model is intended for use in underground distribution network.
    distributionUnderground = auto()
    # Asset model is intended for use in transmission network.
    transmission = auto()
    # Asset model is intended for use in substation.
    substation = auto()
    # Asset model is intended for use as streetlight.
    streetlight = auto()
    # Asset model is intended for use in customer substation.
    customerSubstation = auto()
    # Usage of the asset model is unknown.
    unknown = auto()
    # Other kind of asset model usage.
    other = auto()