#######################################################
# 
# CorporateStandardKind.py
# Python implementation of the Class CorporateStandardKind
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:17
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class CorporateStandardKind(Enum):
    """Kind of corporate standard.
    """
    # Asset model is used as corporate standard.
    standard = auto()
    # Asset model is used experimentally.
    experimental = auto()
    # Asset model usage is under evaluation.
    underEvaluation = auto()
    # Other kind of corporate standard for the asset model.
    other = auto()