#######################################################
# 
# Maintainer.py
# Python implementation of the Class Maintainer
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:49
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.Assets.AssetOrganisationRole import AssetOrganisationRole

@dataclass
class Maintainer(AssetOrganisationRole):
    """Organisation that maintains assets.
    """
    pass
