#######################################################
# 
# ProductAssetModel.py
# Python implementation of the Class ProductAssetModel
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:25
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61968.Assets.CorporateStandardKind import CorporateStandardKind
from TC57CIM.IEC61968.Assets.AssetModelUsageKind import AssetModelUsageKind
from TC57CIM.IEC61970.Base.Domain.Weight import Weight
from TC57CIM.IEC61968.InfIEC61968.InfAssetInfo.AssetModelCatalogueItem import AssetModelCatalogueItem
from TC57CIM.IEC61968.Assets.AssetModel import AssetModel
from TC57CIM.IEC61968.Assets.Manufacturer import Manufacturer

@dataclass
class ProductAssetModel(AssetModel):
    """Asset model by a specific manufacturer.
    """
    # Manufacturer's model number.
    modelNumber: str  = None
 
    # Version number for product model, which indicates vintage of the product.
    modelVersion: str  = None
 
    # Kind of corporate standard for this asset model.
    corporateStandardKind: CorporateStandardKind  = None
 
    # Intended usage for this asset model.
    usageKind: AssetModelUsageKind  = None
 
    # Total manufactured weight of asset.
    weightTotal: Weight  = None
 
    assetModelCatalogueItems: List[AssetModelCatalogueItem] = []
 
    # Manufacturer of this asset model.
    manufacturer: Optional[Manufacturer] = None
     