#######################################################
# 
# Seal.py
# Python implementation of the Class Seal
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:48
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61968.Assets.SealKind import SealKind
from TC57CIM.IEC61968.Assets.SealConditionKind import SealConditionKind
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

@dataclass
class Seal(IdentifiedObject):
    """Physically controls access to AssetContainers.
    """
    # (reserved word) Seal number.
    sealNumber: str  = None
 
    # Kind of seal.
    kind: SealKind  = None
 
    # Condition of seal.
    condition: SealConditionKind  = None
 
    # Date and time this seal has been applied.
    appliedDateTime: DateTime  = None
     