#######################################################
# 
# ENTSOEJunction.py
# Python implementation of the Class ENTSOEJunction
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:52
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.Extension.BoundaryExtensions import BoundaryExtensions

@dataclass
class ENTSOEJunction(BoundaryExtensions):
    """This is a class extension of the class Junction in CIM. The extension is done
    for the purpose of ENTSO-E profiling work.
    """
    pass
