#######################################################
# 
# ICCPIndicationPointType.py
# Python implementation of the Class ICCPIndicationPointType
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:21
# Original author: SELAOST1
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class ICCPIndicationPointType(Enum):
    REAL = auto()
    STATE = auto()
    DISCRETE = auto()