#######################################################
# 
# ICCPPScope.py
# Python implementation of the Class ICCPPScope
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:25
# Original author: selaost1
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class ICCPPScope(Enum):
    VCC = auto()
    ICC = auto()