#######################################################
# 
# ICCPPoint.py
# Python implementation of the Class ICCPPoint
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:32
# Original author: SELAOST1
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.InfIEC61970.ICCP.ICCPPScope import ICCPPScope
from TC57CIM.IEC61970.InfIEC61970.ICCP.TASE2BilateralTable import TASE2BilateralTable
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

@dataclass
class ICCPPoint(IdentifiedObject):
    """The IdentifiedObject.name attribute must have a value.  The name attribute
    shall be used as the DataValue name used for the exchange.
    """
    scope: ICCPPScope  = None
 
    tASE2BilateralTable: Optional[TASE2BilateralTable] = None
     