#######################################################
# 
# ICCPSetPoint.py
# Python implementation of the Class ICCPSetPoint
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:25
# Original author: SELAOST1
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.InfIEC61970.ICCP.ICCPSetPointType import ICCPSetPointType
from TC57CIM.IEC61970.InfIEC61970.ICCP.ICCPControlPoint import ICCPControlPoint

@dataclass
class ICCPSetPoint(ICCPControlPoint):
    type: ICCPSetPointType  = None
     