#######################################################
# 
# ISOUpperLayer.py
# Python implementation of the Class ISOUpperLayer
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:34
# Original author: selaost1
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.InfIEC61970.ICCP.ISOAPAddressing import ISOAPAddressing
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.InfIEC61970.ICCP.TCPAcessPoint import TCPAcessPoint

@dataclass
class ISOUpperLayer(TCPAcessPoint):
    ap: ISOAPAddressing  = None
 
    osiPsel: String  = None
 
    osiSsel: String  = None
 
    osiTsel: String  = None
     