#######################################################
# 
# WindType1or2UserDefined.py
# Python implementation of the Class WindType1or2UserDefined
# Generated by Enterprise Architect
# Created on:      21-May-2025 11:00:37
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61970.Dynamics.UserDefinedModels.ProprietaryParameterDynamics import ProprietaryParameterDynamics
from TC57CIM.IEC61970.Dynamics.StandardModels.WindDynamics.WindTurbineType1or2Dynamics import WindTurbineType1or2Dynamics

@dataclass
class WindType1or2UserDefined(WindTurbineType1or2Dynamics):
    """Wind Type 1 or Type 2 function block whose dynamic behaviour is described by
    <font color="#0f0f0f">a user-defined model.</font>
    """
    # Behaviour is based on proprietary model as opposed to detailed model.
    # true = user-defined model is proprietary with behaviour mutually understood by
    # sending and receiving applications and parameters passed as general attributes
    # false = user-defined model is explicitly defined in terms of control blocks and
    # their input and output signals.
    proprietary: bool  = None
 
    # Parameter of this proprietary user-defined model.
    proprietaryParameterDynamicss: List[ProprietaryParameterDynamics] = []
     