#######################################################
# 
# CustomerAgreement.py
# Python implementation of the Class CustomerAgreement
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:24
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61968.Customers.ServiceLocation import ServiceLocation
from TC57CIM.IEC61968.InfIEC61968.InfCustomers.StandardIndustryCode import StandardIndustryCode
from TC57CIM.IEC61968.PaymentMetering.AuxiliaryAgreement import AuxiliaryAgreement
from TC57CIM.IEC61968.Customers.PricingStructure import PricingStructure
from TC57CIM.IEC61968.Customers.ServiceCategory import ServiceCategory
from TC57CIM.IEC61968.Metering.UsagePoint import UsagePoint
from TC57CIM.IEC61968.Common.Agreement import Agreement

@dataclass
class CustomerAgreement(Agreement):
    """Agreement between the customer and the service supplier to pay for service at a
    specific service location. It records certain billing information about the
    type of service provided at the service location and is used during charge
    creation to determine the type of service.
    """
    # Load management code.
    loadMgmt: String  = None
 
    # All service locations regulated by this customer agreement.
    ServiceLocations: List[ServiceLocation] = []
 
    StandardIndustryCode: Optional[StandardIndustryCode] = None
 
    # All (non-service related) auxiliary agreements that refer to this customer
    # agreement.
    AuxiliaryAgreements: List[AuxiliaryAgreement] = []
 
    # All pricing structures applicable to this customer agreement.
    PricingStructures: List[PricingStructure] = []
 
    # Service category for this agreement.
    ServiceCategory: Optional[ServiceCategory] = None
 
    # All service delivery points regulated by this customer agreement.
    UsagePoints: List[UsagePoint] = []
     