#######################################################
# 
# CustomerAccount.py
# Python implementation of the Class CustomerAccount
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:32
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61968.InfIEC61968.InfERPSupport.ErpInvoice import ErpInvoice
from TC57CIM.IEC61968.InfIEC61968.InfCustomers.WorkBillingInfo import WorkBillingInfo
from TC57CIM.IEC61968.Customers.CustomerAgreement import CustomerAgreement
from TC57CIM.IEC61968.PaymentMetering.Transaction import Transaction
from TC57CIM.IEC61968.Common.Document import Document

@dataclass
class CustomerAccount(Document):
    """Assignment of a group of products and services purchased by the customer
    through a customer agreement, used as a mechanism for customer billing and
    payment. It contains common information from the various types of customer
    agreements to create billings (invoices) for a customer and receive payment.
    """
    # Cycle day on which the associated customer account will normally be billed,
    # used to determine when to produce the billing.
    billingCycle: str  = None
 
    # Budget bill code.
    budgetBill: str  = None
 
    erpInvoices: List[ErpInvoice] = []
 
    workBillingInfos: List[WorkBillingInfo] = []
 
    # All agreements for this customer account.
    customerAgreements: List[CustomerAgreement] = []
 
    # All payment transactions for this customer account.
    transactions: List[Transaction] = []
     