#######################################################
# 
# IncidentHazard.py
# Python implementation of the Class IncidentHazard
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:38
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.Common.Hazard import Hazard

@dataclass
class IncidentHazard(Hazard):
    """Hazardous situation associated with an incident. Examples are line down, gas
    leak, fire, etc.
    """
    pass
