#######################################################
# 
# TroubleReportingKind.py
# Python implementation of the Class TroubleReportingKind
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:41:05
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class TroubleReportingKind(Enum):
    """Kind of trouble reporting.
    """
    # Trouble call received by customer service representative.
    call = auto()
    # Trouble reported by email.
    email = auto()
    # Trouble reported by letter.
    letter = auto()
    # Trouble reported by other means.
    other = auto()
    # Trouble reported through interactive voice response system.
    ivr = auto()