#######################################################
# 
# WindGenType4IEC.py
# Python implementation of the Class WindGenType4IEC
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:41:20
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.PU import PU
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Seconds import Seconds
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.WindDynamics.WindTurbineType3or4IEC import WindTurbineType3or4IEC

@dataclass
class WindGenType4IEC(WindTurbineType3or4IEC):
    """IEC Type 4 generator set model.
    
      Reference: IEC Standard 61400-27-1 Section 6.6.3.4.
    """
    # Maximum active current ramp rate (di<sub>pmax</sub>). It is project dependent
    # parameter.
    dipmax: PU  = None
 
    # Minimum reactive current ramp rate (d<i>i</i><sub>qmin</sub>). It is case
    # dependent parameter.
    diqmin: PU  = None
 
    # Maximum reactive current ramp rate (di<sub>qmax</sub>). It is project dependent
    # parameter.
    diqmax: PU  = None
 
    # Time constant (T<sub>g</sub>). It is type dependent parameter.
    tg: Seconds  = None
     