#######################################################
# 
# WindDynamicsLookupTable.py
# Python implementation of the Class WindDynamicsLookupTable
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:51:24
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Simple_Float import Simple_Float
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.WindDynamics.WindLookupTableFunctionKind import WindLookupTableFunctionKind
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Integer import Integer
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.WindDynamics.WindPlantFreqPcontrolIEC import WindPlantFreqPcontrolIEC
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.Core.IdentifiedObject import IdentifiedObject
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.WindDynamics.WindContRotorRIEC import WindContRotorRIEC
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.WindDynamics.WindContPType3IEC import WindContPType3IEC
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.WindDynamics.WindContCurrLimIEC import WindContCurrLimIEC

@dataclass
class WindDynamicsLookupTable(IdentifiedObject):
    """The class models a look up table for the purpose of wind standard models.
    """
    # Input value (x) for the lookup table function.
    input: Simple_Float  = None
 
    # Type of the lookup table function.
    lookupTableFunctionType: WindLookupTableFunctionKind  = None
 
    # Output value (y) for the lookup table function.
    output: Simple_Float  = None
 
    # Sequence numbers of the pairs of the input (x) and the output (y) of the lookup
    # table function.
    sequence: Integer  = None
 
    # The wind dynamics lookup table associated with this frequency and active power
    # wind plant model.
    windPlantFreqPcontrolIEC: Optional[WindPlantFreqPcontrolIEC] = None
 
    # The rotor resistance control model with which this wind dynamics lookup table
    # is associated.
    windContRotorRIEC: Optional[WindContRotorRIEC] = None
 
    # The wind dynamics lookup table associated with this P control type 3 model.
    windContPType3IEC: Optional[WindContPType3IEC] = None
 
    # The wind dynamics lookup table associated with this current control limitation
    # model.
    windContCurrLimIEC: Optional[WindContCurrLimIEC] = None
     