#######################################################
# 
# WindPitchContEmulIEC.py
# Python implementation of the Class WindPitchContEmulIEC
# Generated by Enterprise Architect
# Created on:      21-May-2025 11:00:34
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Simple_Float import Simple_Float
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.PU import PU
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Seconds import Seconds
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.Core.IdentifiedObject import IdentifiedObject
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.WindDynamics.WindGenTurbineType2IEC import WindGenTurbineType2IEC

@dataclass
class WindPitchContEmulIEC(IdentifiedObject):
    """Pitch control emulator model.
    
      Reference: IEC Standard 61400-27-1 Section 6.6.5.1.
    """
    # Power error gain (<i>K</i><sub>droop</sub>). It is case dependent parameter.
    kdroop: Simple_Float  = None
 
    # Pitch control emulator integral constant (<i>K</i><sub>I,pce</sub>). It is type
    # dependent parameter.
    kipce: Simple_Float  = None
 
    # Aerodynamic power change vs. omega<sub>WTR </sub>change
    # (<i>K</i><sub>omegaaero</sub>). It is case dependent parameter.
    komegaaero: PU  = None
 
    # Pitch control emulator proportional constant (<i>K</i><sub>P,pce</sub>). It is
    # type dependent parameter.
    kppce: Simple_Float  = None
 
    # Rotor speed in initial steady state (omega<sub>ref</sub>). It is case dependent
    # parameter.
    omegaref: PU  = None
 
    # Maximum steady state power (<i>p</i><sub>imax</sub>). It is case dependent
    # parameter.
    pimax: PU  = None
 
    # Minimum steady state power (<i>p</i><sub>imin</sub>). It is case dependent
    # parameter.
    pimin: PU  = None
 
    # First time constant in pitch control lag (<i>T</i><sub>1</sub>). It is type
    # dependent parameter.
    t1: Seconds  = None
 
    # Second time constant in pitch control lag (<i>T</i><sub>2</sub>). It is type
    # dependent parameter.
    t2: Seconds  = None
 
    # Time constant in generator air gap power lag (<i>T</i><sub>pe</sub>). It is
    # type dependent parameter.
    tpe: Seconds  = None
 
    # Wind turbine type 2 model with which this Pitch control emulator model is
    # associated.
    windGenTurbineType2IEC: Optional[WindGenTurbineType2IEC] = None
     