#######################################################
# 
# GovGAST3.py
# Python implementation of the Class GovGAST3
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:13
# Original author: pcha006
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.PU import PU
from TC57CIM.IEC61970.Base.Domain.Seconds import Seconds
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Domain.Temperature import Temperature
from TC57CIM.IEC61970.Dynamics.StandardModels.TurbineGovernorDynamics.TurbineGovernorDynamics import TurbineGovernorDynamics

@dataclass
class GovGAST3(TurbineGovernorDynamics):
    """Generic turbogas with acceleration and temperature controller.
    """
    # Droop (bp).  Typical Value = 0.05.
    bp: PU  = None
 
    # Time constant of speed governor (Tg).  Typical Value = 0.05.
    tg: Seconds  = None
 
    # Maximum fuel flow (RCMX).  Typical Value = 1.
    rcmx: PU  = None
 
    # Minimum fuel flow (RCMN).  Typical Value = -0.1.
    rcmn: PU  = None
 
    # Coefficient of transfer function of fuel valve positioner (Ky).  Typical Value
    # = 1.
    ky: Float  = None
 
    # Time constant of fuel valve positioner (Ty).  Typical Value = 0.2.
    ty: Seconds  = None
 
    # Fuel control time constant (Tac).  Typical Value = 0.1.
    tac: Seconds  = None
 
    # Fuel system feedback (K<sub>AC</sub>).  Typical Value = 0.
    kac: Float  = None
 
    # Compressor discharge volume time constant (Tc).  Typical Value = 0.2.
    tc: Seconds  = None
 
    # Acceleration limit set-point (Bca).  Unit = 1/s.  Typical Value = 0.01.
    bca: Float  = None
 
    # Acceleration control integral gain (Kca). Unit = 1/s.  Typical Value = 100.
    kca: Float  = None
 
    # Exhaust temperature variation due to fuel flow increasing from 0 to 1 PU
    # (deltaTc).  Typical Value = 390.
    dtc: Temperature  = None
 
    # Minimum fuel flow (Ka).  Typical Value = 0.23.
    ka: PU  = None
 
    # Time constant of radiation shield (Tsi).  Typical Value = 15.
    tsi: Seconds  = None
 
    # Gain of radiation shield (Ksi).  Typical Value = 0.8.
    ksi: Float  = None
 
    # Time constant of thermocouple (Ttc).  Typical Value = 2.5.
    ttc: Seconds  = None
 
    # Turbine rated exhaust temperature correspondent to Pm=1 PU (Tfen).  Typical
    # Value = 540.
    tfen: Temperature  = None
 
    # Temperature controller derivative gain (Td).  Typical Value = 3.3.
    td: Seconds  = None
 
    # Temperature controller integration rate (Tt).  Typical Value = 250.
    tt: Temperature  = None
 
    # Fuel flow maximum positive error value (MX<sub>EF</sub>).  Typical Value = 0.05.
    mxef: PU  = None
 
    # Fuel flow maximum negative error value (MN<sub>EF</sub>).  Typical Value = -0.
    # 05.
    mnef: PU  = None
     