#######################################################
# 
# GovSteamIEEE1.py
# Python implementation of the Class GovSteamIEEE1
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:18
# Original author: tsaxton
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.ActivePower import ActivePower
from TC57CIM.IEC61970.Base.Domain.PU import PU
from TC57CIM.IEC61970.Base.Domain.Seconds import Seconds
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Dynamics.StandardModels.TurbineGovernorDynamics.TurbineGovernorDynamics import TurbineGovernorDynamics

@dataclass
class GovSteamIEEE1(TurbineGovernorDynamics):
    """IEEE steam turbine governor model.
    
      Ref<font color="#0f0f0f">erence: IEEE Transactions on Power Apparatus and
    Systems</font>
      <font color="#0f0f0f">November/December 1973, Volume PAS-92, Number 6</font>
      <font color="#0f0f0f"><i><u>Dynamic Models for Steam and Hydro Turbines in
    Power System Studies</u></i>, Page 1904.</font>
    
      <b>Parameter Notes:</b>
      <ol>
      	<li>Per unit parameters are on base of <b>MWbase</b>, which is normally the
    MW capability of the turbine.</li>
      	<li><b>T3</b> must be greater than zero.  All other time constants may be
    zero.</li>
      	<li>For a tandem-compound turbine the parameters <b>K2</b>, <b>K4</b>,
    <b>K6</b>, and <b>K8</b> are ignored. For a cross-compound turbine, two
    generators are connected to this turbine-governor model.</li>
      	<li>Each generator must be represented in the load flow by data on its own
    MVA base.  The values of <b>K1</b>, <b>K3</b>, <b>K5</b>, <b>K7</b> must be
    specified to describe the proportionate development of power on the first
    turbine shaft.  <b>K2</b>, <b>K4</b>, <b>K6</b>, <b>K8</b> must describe the
    second turbine shaft. Normally <b>K1</b> + <b>K3</b> + <b>K5</b> + <b>K7</b> =
    1.0 and <b>K2</b> + <b>K4</b> + <b>K6</b> + <b>K8</b> = 1.0  (if second
    generator is present).</li>
      	<li>The division of power between the two shafts is in proportion to the
    values of MVA bases of the two generators.  The initial condition load flow
    should, therefore, have the two generators loaded to the same fraction of each
    one’s MVA base.</li>
      </ol>
    """
    # Base for power values (MWbase) (> 0)<i>.</i>
    mwbase: ActivePower  = None
 
    # Governor gain (reciprocal of droop) (K) (> 0).  Typical Value = 25.
    k: PU  = None
 
    # Governor lag time constant (T1).  Typical Value = 0.
    t1: Seconds  = None
 
    # Governor lead time constant (T2).  Typical Value = 0.
    t2: Seconds  = None
 
    # Valve positioner time constant (T3) (> 0).  Typical Value = 0.1.
    t3: Seconds  = None
 
    # Maximum valve opening velocity (Uo) (> 0).  Unit = PU/sec.  Typical Value = 1.
    uo: Float  = None
 
    # Maximum valve closing velocity (Uc) (< 0).  Unit = PU/sec.  Typical Value = -10.
    uc: Float  = None
 
    # Maximum valve opening (Pmax) (> Pmin).  Typical Value = 1.
    pmax: PU  = None
 
    # Minimum valve opening (Pmin) (>= 0).  Typical Value = 0.
    pmin: PU  = None
 
    # Inlet piping/steam bowl time constant (T4).  Typical Value = 0.3.
    t4: Seconds  = None
 
    # Fraction of HP shaft power after first boiler pass (K1).  Typical Value = 0.2.
    k1: Float  = None
 
    # Fraction of LP shaft power after first boiler pass (K2).  Typical Value = 0.
    k2: Float  = None
 
    # Time constant of second boiler pass (T5).  Typical Value = 5.
    t5: Seconds  = None
 
    # Fraction of HP shaft power after second boiler pass (K3).  Typical Value = 0.3.
    k3: Float  = None
 
    # Fraction of LP shaft power after second boiler pass (K4).  Typical Value = 0.
    k4: Float  = None
 
    # Time constant of third boiler pass (T6).  Typical Value = 0.5.
    t6: Seconds  = None
 
    # Fraction of HP shaft power after third boiler pass (K5).  Typical Value = 0.5.
    k5: Float  = None
 
    # Fraction of LP shaft power after third boiler pass (K6).  Typical Value = 0.
    k6: Float  = None
 
    # Time constant of fourth boiler pass (T7).  Typical Value = 0.
    t7: Seconds  = None
 
    # Fraction of HP shaft power after fourth boiler pass (K7).  Typical Value = 0.
    k7: Float  = None
 
    # Fraction of LP shaft power after fourth boiler pass (K8).  Typical Value = 0.
    k8: Float  = None
     