#######################################################
# 
# GovSteamEU.py
# Python implementation of the Class GovSteamEU
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:17
# Original author: tsaxton
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.ActivePower import ActivePower
from TC57CIM.IEC61970.Base.Domain.Seconds import Seconds
from TC57CIM.IEC61970.Base.Domain.PU import PU
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Dynamics.StandardModels.TurbineGovernorDynamics.TurbineGovernorDynamics import TurbineGovernorDynamics

@dataclass
class GovSteamEU(TurbineGovernorDynamics):
    """Simplified model  of boiler and steam turbine with PID governor.
    """
    # Base for power values (MWbase) (>0).  Unit = MW.
    mwbase: ActivePower  = None
 
    # Power transducer time constant (Tp).  Typical Value = 0.07.
    tp: Seconds  = None
 
    # Gain of the power controller (Ke).  Typical Value = 0.65.
    ke: PU  = None
 
    # Integral time constant of the power controller (Tip).  Typical Value = 2.
    tip: Seconds  = None
 
    # Derivative time constant of the power controller (Tdp).  Typical Value = 0.
    tdp: Seconds  = None
 
    # Time constant of the power controller (Tfp).  Typical Value = 0.
    tfp: Seconds  = None
 
    # Frequency transducer time constant (Tf).  Typical Value = 0.
    tf: Seconds  = None
 
    # Gain of the frequency corrector (Kfcor).  Typical Value = 20.
    kfcor: PU  = None
 
    # Dead band of the frequency corrector (db1).  Typical Value = 0.
    db1: PU  = None
 
    # Upper limit for frequency correction (Wfmax).  Typical Value = 0.05.
    wfmax: PU  = None
 
    # Lower limit for frequency correction (Wfmin).  Typical Value = -0.05.
    wfmin: PU  = None
 
    # Maximal active power of the turbine (Pmax).  Typical Value = 1.
    pmax: PU  = None
 
    # Electro hydraulic transducer (Ten).  Typical Value = 0.1.
    ten: Seconds  = None
 
    # Speed transducer time constant (Tw).  Typical Value = 0.02.
    tw: Seconds  = None
 
    # Gain of the speed governor (Kwcor).  Typical Value = 20.
    kwcor: PU  = None
 
    # Dead band of the speed governor (db2).  Typical Value = 0.0004.
    db2: PU  = None
 
    # Upper limit for the speed governor (Wwmax).  Typical Value = 0.1.
    wwmax: PU  = None
 
    # Lower limit for the speed governor frequency correction (Wwmin).  Typical Value
    # = -1.
    wwmin: PU  = None
 
    # Emergency speed control lower limit (wmax1).  Typical Value = 1.025.
    wmax1: PU  = None
 
    # Emergency speed control upper limit (wmax2).  Typical Value = 1.05.
    wmax2: PU  = None
 
    # Control valves servo time constant (Tvhp).  Typical Value = 0.1.
    tvhp: Seconds  = None
 
    # Control valves rate opening limit (Cho).  Unit = PU/sec.  Typical Value = 0.17.
    cho: Float  = None
 
    # Control valves rate closing limit (Chc).  Unit = PU/sec.  Typical Value = -3.3.
    chc: Float  = None
 
    # Maximum control valve position (Hhpmax).  Typical Value = 1.
    hhpmax: PU  = None
 
    # Intercept valves servo time constant (Tvip).  Typical Value = 0.15.
    tvip: Seconds  = None
 
    # Intercept valves rate opening limit (Cio).  Typical Value = 0.123.
    cio: PU  = None
 
    # Intercept valves rate closing limit (Cic).  Typical Value = -2.2.
    cic: PU  = None
 
    # Intercept valves transfer limit (Simx).  Typical Value = 0.425.
    simx: PU  = None
 
    # High pressure (HP) time constant of the turbine (Thp).  Typical Value = 0.31.
    thp: Seconds  = None
 
    # Reheater  time constant of the turbine (Trh).  Typical Value = 8.
    trh: Seconds  = None
 
    # Low pressure(LP) time constant of the turbine (Tlp).  Typical Value = 0.45.
    tlp: Seconds  = None
 
    # Maximum low pressure limit (Prhmax).  Typical Value = 1.4.
    prhmax: PU  = None
 
    # Fraction of total turbine output generated by HP part (Khp).  Typical Value = 0.
    # 277.
    khp: PU  = None
 
    # Fraction of total turbine output generated by HP part (Klp).  Typical Value = 0.
    # 723.
    klp: PU  = None
 
    # Boiler time constant (Tb).  Typical Value = 100.
    tb: Seconds  = None
     