#######################################################
# 
# EnergySource.py
# Python implementation of the Class EnergySource
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:42
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Voltage import Voltage
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Resistance import Resistance
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.AngleRadians import AngleRadians
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Reactance import Reactance
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.Core.ConductingEquipment import ConductingEquipment
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.Production.EnergySchedulingType import EnergySchedulingType

@dataclass
class EnergySource(ConductingEquipment):
    """A generic equivalent for an energy supplier on a transmission or distribution
    voltage level.
    """
    # Phase-to-phase nominal voltage.
    nominalVoltage: Voltage  = None
 
    # Positive sequence Thevenin resistance.
    r: Resistance  = None
 
    # Zero sequence Thevenin resistance.
    r0: Resistance  = None
 
    # Negative sequence Thevenin resistance.
    rn: Resistance  = None
 
    # Phase angle of a-phase open circuit.
    voltageAngle: AngleRadians  = None
 
    # Phase-to-phase open circuit voltage magnitude.
    voltageMagnitude: Voltage  = None
 
    # Positive sequence Thevenin reactance.
    x: Reactance  = None
 
    # Zero sequence Thevenin reactance.
    x0: Reactance  = None
 
    # Negative sequence Thevenin reactance.
    xn: Reactance  = None
 
    # Energy Scheduling Type of an Energy Source
    EnergySchedulingType: Optional[EnergySchedulingType] = None
     