#######################################################
# 
# HydroPowerPlant.py
# Python implementation of the Class HydroPowerPlant
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:21
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.Production.HydroPlantStorageKind import HydroPlantStorageKind
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.Core.PowerSystemResource import PowerSystemResource

@dataclass
class HydroPowerPlant(PowerSystemResource):
    """A hydro power station which can generate or pump. When generating, the
    generator turbines receive water from an upper reservoir. When pumping, the
    pumps receive their water from a lower reservoir.
    """
    # The type of hydro power plant water storage.
    hydroPlantStorageType: HydroPlantStorageKind  = None
     