#######################################################
# 
# WindGenUnitKind.py
# Python implementation of the Class WindGenUnitKind
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:41:20
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class WindGenUnitKind(Enum):
    """Kind of wind generating unit.
    """
    # The wind generating unit is located offshore.
    offshore = auto()
    # The wind generating unit is located onshore.
    onshore = auto()