#######################################################
# 
# EquivalentInjection.py
# Python implementation of the Class EquivalentInjection
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:55
# Original author: KLH
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.ActivePower import ActivePower
from TC57CIM.IEC61970.Base.Domain.ReactivePower import ReactivePower
from TC57CIM.IEC61970.Base.Domain.Resistance import Resistance
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61970.Base.Domain.Voltage import Voltage
from TC57CIM.IEC61970.Base.Domain.Reactance import Reactance
from TC57CIM.IEC61970.Base.Equivalents.EquivalentEquipment import EquivalentEquipment

@dataclass
class EquivalentInjection(EquivalentEquipment):
    """This class represents equivalent injections (generation or load).  Voltage
    regulation is allowed only at the point of connection.
    """
    # Maximum active power of the injection.
    maxP: ActivePower  = None
 
    # Used for modeling of infeed for load flow exchange. Not used for short circuit
    # modeling.  If maxQ and minQ are not used ReactiveCapabilityCurve can be used.   
    maxQ: ReactivePower  = None
 
    # Minimum active power of the injection.
    minP: ActivePower  = None
 
    # Used for modeling of infeed for load flow exchange. Not used for short circuit
    # modeling.  If maxQ and minQ are not used ReactiveCapabilityCurve can be used.
    minQ: ReactivePower  = None
 
    # Positive sequence resistance. Used to represent Extended-Ward (IEC 60909).
    # Usage : Extended-Ward is a result of network reduction prior to the data
    # exchange. 
    r: Resistance  = None
 
    # Zero sequence resistance. Used to represent Extended-Ward (IEC 60909).
    # Usage : Extended-Ward is a result of network reduction prior to the data
    # exchange. 
    r0: Resistance  = None
 
    # Negative sequence resistance. Used to represent Extended-Ward (IEC 60909).
    # Usage : Extended-Ward is a result of network reduction prior to the data
    # exchange. 
    r2: Resistance  = None
 
    # Specifies whether or not the EquivalentInjection has the capability to regulate
    # the local voltage.
    regulationCapability: bool  = None
 
    # Specifies the default regulation status of the EquivalentInjection.  True is
    # regulating.  False is not regulating.
    regulationStatus: bool  = None
 
    # The target voltage for voltage regulation.
    regulationTarget: Voltage  = None
 
    # Positive sequence reactance. Used to represent Extended-Ward (IEC 60909).
    # Usage : Extended-Ward is a result of network reduction prior to the data
    # exchange. 
    x: Reactance  = None
 
    # Zero sequence reactance. Used to represent Extended-Ward (IEC 60909).
    # Usage : Extended-Ward is a result of network reduction prior to the data
    # exchange. 
    x0: Reactance  = None
 
    # Negative sequence reactance. Used to represent Extended-Ward (IEC 60909).
    # Usage : Extended-Ward is a result of network reduction prior to the data
    # exchange. 
    x2: Reactance  = None
 
    # Equivalent active power injection. Load sign convention is used, i.e. positive
    # sign means flow out from a node.
    # Starting value for steady state solutions.
    p: ActivePower  = None
 
    # Equivalent reactive power injection. Load sign convention is used, i.e.
    # positive sign means flow out from a node.
    # Starting value for steady state solutions.
    q: ReactivePower  = None
     