#######################################################
# 
# AirCompressor.py
# Python implementation of the Class AirCompressor
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:37:51
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Core.PowerSystemResource import PowerSystemResource

@dataclass
class AirCompressor(PowerSystemResource):
    """Combustion turbine air compressor which is an integral part of a compressed air
    energy storage (CAES) plant.
    """
    # Rating of the CAES air compressor.
    airCompressorRating: Float  = None
     