#######################################################
# 
# CAESPlant.py
# Python implementation of the Class CAESPlant
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:06
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.RealEnergy import RealEnergy
from TC57CIM.IEC61970.Base.Domain.ActivePower import ActivePower
from TC57CIM.IEC61970.Base.Generation.Production.ThermalGeneratingUnit import ThermalGeneratingUnit
from TC57CIM.IEC61970.Base.Generation.Production.AirCompressor import AirCompressor
from TC57CIM.IEC61970.Base.Core.PowerSystemResource import PowerSystemResource

@dataclass
class CAESPlant(PowerSystemResource):
    """Compressed air energy storage plant.
    """
    # The rated energy storage capacity.
    energyStorageCapacity: RealEnergy  = None
 
    # The CAES plant's gross rated generating capacity.
    ratedCapacityP: ActivePower  = None
 
    # A thermal generating unit may be a member of a compressed air energy storage
    # plant.
    ThermalGeneratingUnit: Optional[ThermalGeneratingUnit] = None
 
    # An air compressor may be a member of a compressed air energy storage plant.
    AirCompressor: Optional[AirCompressor] = None
     