#######################################################
# 
# CogenerationPlant.py
# Python implementation of the Class CogenerationPlant
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:16
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Domain.ActivePower import ActivePower
from TC57CIM.IEC61970.Base.Generation.Production.ThermalGeneratingUnit import ThermalGeneratingUnit
from TC57CIM.IEC61970.Base.Generation.Production.SteamSendoutSchedule import SteamSendoutSchedule
from TC57CIM.IEC61970.Base.Core.PowerSystemResource import PowerSystemResource

@dataclass
class CogenerationPlant(PowerSystemResource):
    """A set of thermal generating units for the production of electrical energy and
    process steam (usually from the output of the steam turbines). The steam
    sendout is typically used for industrial purposes or for municipal heating and
    cooling.
    """
    # The high pressure steam sendout.
    cogenHPSendoutRating: float  = None
 
    # The high pressure steam rating.
    cogenHPSteamRating: float  = None
 
    # The low pressure steam sendout.
    cogenLPSendoutRating: float  = None
 
    # The low pressure steam rating.
    cogenLPSteamRating: float  = None
 
    # The rated output active power of the cogeneration plant.
    ratedP: ActivePower  = None
 
    # A thermal generating unit may be a member of a cogeneration plant.
    thermalGeneratingUnits: List[ThermalGeneratingUnit] = []
 
    # A cogeneration plant has a steam sendout schedule.
    steamSendoutSchedule: Optional[SteamSendoutSchedule] = None
     