#######################################################
# 
# FossilFuel.py
# Python implementation of the Class FossilFuel
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:09
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Generation.Production.FuelType import FuelType
from TC57CIM.IEC61970.Base.Generation.Production.CostPerHeatUnit import CostPerHeatUnit
from TC57CIM.IEC61970.Base.Domain.PU import PU
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Domain.PerCent import PerCent
from TC57CIM.IEC61970.Base.Domain.ActivePower import ActivePower
from TC57CIM.IEC61970.Base.Generation.Production.FuelAllocationSchedule import FuelAllocationSchedule
from TC57CIM.IEC61970.Base.Generation.Production.ThermalGeneratingUnit import ThermalGeneratingUnit
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

@dataclass
class FossilFuel(IdentifiedObject):
    """The fossil fuel consumed by the non-nuclear thermal generating unit.   For
    example, coal, oil, gas, etc.   This a the specific fuels that the generating
    unit can consume.
    """
    # The type of fossil fuel, such as coal, oil, or gas.
    fossilFuelType: FuelType  = None
 
    # The cost in terms of heat value for the given type of fuel.
    fuelCost: CostPerHeatUnit  = None
 
    # The cost of fuel used for economic dispatching which includes: fuel cost,
    # transportation cost,  and incremental maintenance cost.
    fuelDispatchCost: CostPerHeatUnit  = None
 
    # The efficiency factor for the fuel (per unit) in terms of the effective energy
    # absorbed.
    fuelEffFactor: PU  = None
 
    # Handling and processing cost associated with this fuel.
    fuelHandlingCost: CostPerHeatUnit  = None
 
    # The amount of heat per weight (or volume) of the given type of fuel.
    fuelHeatContent: Float  = None
 
    # Relative amount of the given type of fuel, when multiple fuels are being
    # consumed.
    fuelMixture: PerCent  = None
 
    # The fuel's fraction of pollution credit per unit of heat content.
    fuelSulfur: PU  = None
 
    # The active power output level of the unit at which the given type of fuel is
    # switched on. This fuel (e.g., oil) is sometimes used to supplement the base
    # fuel (e.g., coal) at high active power output levels.
    highBreakpointP: ActivePower  = None
 
    # The active power output level of the unit at which the given type of fuel is
    # switched off. This fuel (e.g., oil) is sometimes used to stabilize the base
    # fuel (e.g., coal) at low active power output levels.
    lowBreakpointP: ActivePower  = None
 
    # A fuel allocation schedule must have a fossil fuel.
    fuelAllocationSchedules: List[FuelAllocationSchedule] = []
 
    # A thermal generating unit may have one or more fossil fuels.
    thermalGeneratingUnit: Optional[ThermalGeneratingUnit] = None
     