#######################################################
# 
# GeneratorControlMode.py
# Python implementation of the Class GeneratorControlMode
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:10
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class GeneratorControlMode(Enum):
    """Unit control modes.
    """
    # Setpoint control mode.
    setpoint = auto()
    # Pulse control mode.
    pulse = auto()