#######################################################
# 
# GenUnitOpCostCurve.py
# Python implementation of the Class GenUnitOpCostCurve
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:14
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61970.Base.Core.Curve import Curve

@dataclass
class GenUnitOpCostCurve(Curve):
    """Relationship between unit operating cost (Y-axis) and unit output active power
    (X-axis). The operating cost curve for thermal units is derived from heat input
    and fuel costs. The operating cost curve for hydro units is derived from water
    flow rates and equivalent water costs.
    """
    # Flag is set to true when output is expressed in net active power.
    isNetGrossP: Boolean  = None
     