#######################################################
# 
# HeatRateCurve.py
# Python implementation of the Class HeatRateCurve
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:23
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61970.Base.Core.Curve import Curve

@dataclass
class HeatRateCurve(Curve):
    """Relationship between unit heat rate per active power (Y-axis) and  unit output
    (X-axis). The heat input is from all fuels.
    """
    # Flag is set to true when output is expressed in net active power.
    isNetGrossP: Boolean  = None
     