#######################################################
# 
# NuclearGeneratingUnit.py
# Python implementation of the Class NuclearGeneratingUnit
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:54
# Original author: kdd
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Generation.Production.GeneratingUnit import GeneratingUnit

@dataclass
class NuclearGeneratingUnit(GeneratingUnit):
    """A nuclear generating unit.
    """
    pass
