#######################################################
# 
# ThermalGeneratingUnit.py
# Python implementation of the Class ThermalGeneratingUnit
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:58
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Generation.Production.CostPerHeatUnit import CostPerHeatUnit
from TC57CIM.IEC61970.Base.Generation.Production.HeatRateCurve import HeatRateCurve
from TC57CIM.IEC61970.Base.Generation.Production.FuelAllocationSchedule import FuelAllocationSchedule
from TC57CIM.IEC61970.Base.Generation.Production.StartupModel import StartupModel
from TC57CIM.IEC61970.Base.Generation.Production.EmissionCurve import EmissionCurve
from TC57CIM.IEC61970.Base.Generation.Production.ShutdownCurve import ShutdownCurve
from TC57CIM.IEC61970.Base.Generation.Production.IncrementalHeatRateCurve import IncrementalHeatRateCurve
from TC57CIM.IEC61970.Base.Generation.Production.GeneratingUnit import GeneratingUnit
from TC57CIM.IEC61970.Base.Generation.Production.EmissionAccount import EmissionAccount
from TC57CIM.IEC61970.Base.Generation.Production.HeatInputCurve import HeatInputCurve

@dataclass
class ThermalGeneratingUnit(GeneratingUnit):
    """A generating unit whose prime mover could be a steam turbine, combustion
    turbine, or diesel engine.
    """
    # Operating and maintenance cost for the thermal unit.
    oMCost: CostPerHeatUnit  = None
 
    # A thermal generating unit may have a heat rate curve.
    HeatRateCurve: Optional[HeatRateCurve] = None
 
    # A thermal generating unit may have one or more fuel allocation schedules.
    FuelAllocationSchedules: List[FuelAllocationSchedule] = []
 
    # A thermal generating unit may have a startup model.
    StartupModel: Optional[StartupModel] = None
 
    # A thermal generating unit may have  one or more emission curves.
    EmissionCurves: List[EmissionCurve] = []
 
    # A thermal generating unit may have a shutdown curve.
    ShutdownCurve: Optional[ShutdownCurve] = None
 
    # A thermal generating unit may have an incremental heat rate curve.
    IncrementalHeatRateCurve: Optional[IncrementalHeatRateCurve] = None
 
    # A thermal generating unit may have one or more emission allowance accounts.
    EmissionAccounts: List[EmissionAccount] = []
 
    # A thermal generating unit may have a heat input curve.
    HeatInputCurve: Optional[HeatInputCurve] = None
     