#######################################################
# 
# Diagram.py
# Python implementation of the Class Diagram
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:31
# Original author: mcmorran
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.DiagramLayout.OrientationKind import OrientationKind
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

@dataclass
class Diagram(IdentifiedObject):
    """The diagram being exchanged.  The coordinate system is a standard Cartesian
    coordinate system and the orientation attribute defines the orientation.
    """
    # Coordinate system orientation of the diagram.
    orientation: OrientationKind  = None
 
    # X coordinate of the first corner of the initial view.
    x1InitialView: Float  = None
 
    # X coordinate of the second corner of the initial view.
    x2InitialView: Float  = None
 
    # Y coordinate of the first corner of the initial view.
    y1InitialView: Float  = None
 
    # Y coordinate of the second corner of the initial view.
    y2InitialView: Float  = None
     