#######################################################
# 
# DiagramStyle.py
# Python implementation of the Class DiagramStyle
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:33
# Original author: SELAOST1
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC61970.Base.DiagramLayout.Diagram import Diagram

@dataclass
class DiagramStyle(IdentifiedObject):
    """The diagram style refer to a style used by the originating system for a diagram.
     A diagram style describes information such as schematic, geographic, bus-
    branch etc.
    """
    # A DiagramStyle can be used by many Diagrams.
    Diagrams: List[Diagram] = []
     