#######################################################
# 
# StaticLoadModelKind.py
# Python implementation of the Class StaticLoadModelKind
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:43
# Original author: tsaxton
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class StaticLoadModelKind(Enum):
    """Type of static load model.
    """
    # Exponential P and Q equations are used and the following attributes are
    # required:
    # kp1, kp2, kp3, kpf, ep1, ep2, ep3
    # kq1, kq2, kq3, kqf, eq1, eq2, eq3.
    exponential = auto()
    # ZIP1 P and Q equations are used and the following attributes are required:
    # kp1, kp2, kp3, kpf
    # kq1, kq2, kq3, kqf.
    zIP1 = auto()
    # This model separates the frequency-dependent load (primarily motors) from other
    # load.  ZIP2 P and Q equations are used and the following attributes are
    # required:
    # kp1, kp2, kp3, kq4, kpf
    # kq1, kq2, kq3, kq4, kqf.
    zIP2 = auto()
    # The load is represented as a constant impedance.  ConstantZ P and Q equations
    # are used and no attributes are required.
    constantZ = auto()