#######################################################
# 
# BillDeterminant.py
# Python implementation of the Class BillDeterminant
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:10
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC61970.Base.Domain.Integer import Integer
from TC57CIM.IEC61968.Common.Document import Document
from TC57CIM.IEC62325.MarketOperations.MarketSystem.MarketResults.ChargeProfileData import ChargeProfileData
from TC57CIM.IEC62325.MarketOperations.MarketOpCommon.MktUserAttribute import MktUserAttribute

@dataclass
class BillDeterminant(Document):
    """Model various charges to support billing and settlement of
    """
    # Level in charge calculation order.
    calculationLevel: str  = None
 
    # The version of configuration of calculation logic in the settlement.
    configVersion: str  = None
 
    deleteStatus: str  = None
 
    effectiveDate: DateTime  = None
 
    exception: str  = None
 
    factor: str  = None
 
    frequency: str  = None
 
    # Number of intervals of bill determiant in trade day, eg 300 for five minute
    # intervals.
    numberInterval: int  = None
 
    offset: str  = None
 
    # The level of precision in the current value. 
    precisionLevel: str  = None
 
    primaryYN: str  = None
 
    referenceFlag: str  = None
 
    reportable: str  = None
 
    roundOff: str  = None
 
    source: str  = None
 
    terminationDate: DateTime  = None
 
    # The UOM for the current value of the Bill Determinant. 
    unitOfMeasure: str  = None
 
    chargeProfileDatas: List[ChargeProfileData] = []
 
    mktUserAttributes: List[MktUserAttribute] = []
     