#######################################################
# 
# ChargeProfile.py
# Python implementation of the Class ChargeProfile
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:05
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Domain.Integer import Integer
from TC57CIM.IEC62325.MarketOperations.MarketSystem.MarketResults.BillDeterminant import BillDeterminant
from TC57CIM.IEC62325.MarketOperations.MarketSystem.MarketResults.ChargeProfileData import ChargeProfileData
from TC57CIM.IEC62325.MarketOperations.MarketSystem.MarketResults.PassThroughBill import PassThroughBill
from TC57CIM.IEC62325.MarketOperations.MarketSystem.ExternalInputs.Profile import Profile

@dataclass
class ChargeProfile(Profile):
    """A type of profile for financial charges
    """
    # The type of profile.  It could be amount, price, or quantity.
    type: String  = None
 
    # The calculation frequency, daily or monthly. 
    frequency: String  = None
 
    # The number of intervals in the profile data.
    numberInterval: Integer  = None
 
    # The unit of measure applied to the value attribute of the profile data.
    unitOfMeasure: String  = None
 
    billDeterminant: Optional[BillDeterminant] = None
 
    chargeProfileDatas: List[ChargeProfileData] = []
 
    passThroughBill: Optional[PassThroughBill] = None
     