#######################################################
# 
# ChargeProfileData.py
# Python implementation of the Class ChargeProfileData
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:15
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Integer import Integer
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC61970.Base.Domain.Float import Float

@dataclass
class ChargeProfileData:
    """Model of various charges associated with an energy profile to support billing
    and settlement
    """
    # The sequence number of the profile.
    sequence: int  = None
 
    # The date and time of an interval.
    timeStamp: DateTime  = None
 
    # The value of an interval given a profile type (amount, price, or quantity),
    # subject to the UOM. 
    value: float  = None
     