#######################################################
# 
# ExPostLoss.py
# Python implementation of the Class ExPostLoss
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:14
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC62325.MarketOperations.MarketPlan.MarketFactors import MarketFactors

@dataclass
class ExPostLoss(MarketFactors):
    """Model of ex-post calcultion of MW losses.
    """
    pass
