#######################################################
# 
# Instructions.py
# Python implementation of the Class Instructions
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:28
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC62325.MarketOperations.MktDomain.YesNo import YesNo
from TC57CIM.IEC62325.MarketOperations.MktDomain.MQSInstructionSource import MQSInstructionSource
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC62325.MarketOperations.MktDomain.AutomaticDispInstTypeCommitment import AutomaticDispInstTypeCommitment
from TC57CIM.IEC61970.Base.Domain.Integer import Integer
from TC57CIM.IEC62325.MarketOperations.MktDomain.MQSCHGType import MQSCHGType
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC62325.MarketOperations.MarketSystem.MarketResults.InstructionClearing import InstructionClearing
from TC57CIM.IEC62325.MarketCommon.RegisteredResource import RegisteredResource

@dataclass
class Instructions:
    """Provides the necessary information (on a resource basis) to capture the
    Startup/Shutdown instruction results. This information is relevant to the DA
    Market (RUC only) as well as the RT Market (HASP, Pre-dispatch, and Interval).
    """
    bindingDOT: Float  = None
 
    bindingInstruction: YesNo  = None
 
    # Total cost associated with changing the status of the resource.
    instructionCost: Float  = None
 
    # instruction source for market quality results (INS, ACT)
    instructionSource: MQSInstructionSource  = None
 
    # Time the resource should be at Pmin (for start ups).
    # 
    # Time the resource is off line.
    instructionStartTime: DateTime  = None
 
    # Indicator of either a Start-Up or a Shut-Down.
    instructionType: AutomaticDispInstTypeCommitment  = None
 
    # Manually Blocked Indicator (Yes/No). The instruction has been blocked by an
    # Operator.
    manuallyBlocked: YesNo  = None
 
    # Minimum start up time required to bring the unit online (minutes).
    # 
    # SCUC commitment period start-up time. Calculated start up time based on the
    # StartUpTimeCurve provided with the Bid.
    # 
    # This is a combination of StartUp time bid and Unit down time.
    # 
    # Units is minutes
    minStatusChangeTime: Integer  = None
 
    updateTimeStamp: DateTime  = None
 
    updateType: MQSCHGType  = None
 
    updateUser: String  = None
 
    InstructionClearings: List[InstructionClearing] = []
 
    RegisteredResource: Optional[RegisteredResource] = None
     