#######################################################
# 
# LoadFollowingOperatorInput.py
# Python implementation of the Class LoadFollowingOperatorInput
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:35
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC62325.MarketOperations.MktDomain.MQSCHGType import MQSCHGType
from TC57CIM.IEC62325.MarketCommon.RegisteredResource import RegisteredResource

@dataclass
class LoadFollowingOperatorInput:
    """Model of load following capabilities that are entered by operators on a
    temporary basis.  Related to Registered Resources in Metered Subsystems
    """
    # Time the data entry was performed
    dataEntryTimeStamp: DateTime  = None
 
    # temporarily manually entered LFU capacity.
    tempLoadFollowingUpManualCap: Float  = None
 
    # temporarily manually entered LFD capacity
    tempLoadFollowingDownManualCap: Float  = None
 
    updateUser: String  = None
 
    updateTimeStamp: DateTime  = None
 
    updateType: MQSCHGType  = None
 
    RegisteredResource: Optional[RegisteredResource] = None
     