#######################################################
# 
# MitigatedBid.py
# Python implementation of the Class MitigatedBid
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:46
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC62325.MarketOperations.ParticipantInterfaces.Bid import Bid
from TC57CIM.IEC62325.MarketOperations.MarketSystem.MarketResults.MitigatedBidClearing import MitigatedBidClearing

@dataclass
class MitigatedBid(IdentifiedObject):
    """Mitigated bid results posted for a given settlement period.
    """
    Bid: Optional[Bid] = None
 
    MitigatedBidClearings: List[MitigatedBidClearing] = []
     