#######################################################
# 
# MPMTestResults.py
# Python implementation of the Class MPMTestResults
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:50
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC62325.MarketOperations.MktDomain.MPMTestOutcome import MPMTestOutcome
from TC57CIM.IEC61970.Base.Domain.PerCent import PerCent

@dataclass
class MPMTestResults:
    """Provides the outcome and margin percent (as appropriate) result data for the
    MPM tests.  There are relationships to Zone for Designated Congestion Area
    Tests, CurveSchedData for bid segment tests, to the SubControlArea for the
    system wide level tests, and Pnodes for the LMPM impact tests.
    """
    # The results of the test. For the Price, Impact, and Conduct tests, typical
    # values are NA, Pass, Fail, Disable, or Skip. 
    outcome: MPMTestOutcome  = None
 
    # Used to show the Margin % result of the Impact test
    marginPercent: PerCent  = None
     