#######################################################
# 
# PnodeResults.py
# Python implementation of the Class PnodeResults
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:12
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC62325.MarketOperations.MktDomain.MQSCHGType import MQSCHGType

@dataclass
class PnodeResults:
    """Provides the total price, the cost component, the loss component, and the
    congestion component for Pnodes for the forward and real time markets. There
    are several prices produced based on the run type (MPM, RUC, Pricing, or
    Scheduling/Dispatch).
    """
    # Locational Marginal Price (LMP) ($/MWh)
    marginalClearingPrice: Float  = None
 
    # Cost component of Locational Marginal Pricing (LMP) in monetary units per MW.
    costLMP: Float  = None
 
    # Loss component of Location Marginal Price (LMP) in monetary units per MW.
    lossLMP: Float  = None
 
    # Congestion component of Location Marginal Price (LMP) in monetary units per MW.
    congestLMP: Float  = None
 
    # total MW schedule at the pnode
    scheduledMW: Float  = None
 
    updateUser: String  = None
 
    updateTimeStamp: DateTime  = None
 
    updateType: MQSCHGType  = None
     