#######################################################
# 
# PnodeClearing.py
# Python implementation of the Class PnodeClearing
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:09
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC62325.MarketOperations.MarketSystem.MarketResults.PnodeResults import PnodeResults
from TC57CIM.IEC62325.MarketOperations.MarketPlan.MarketFactors import MarketFactors

@dataclass
class PnodeClearing(MarketFactors):
    """Pricing node clearing results posted for a given settlement period.
    """
    PnodeResultss: List[PnodeResults] = []
     