#######################################################
# 
# ResourceClearing.py
# Python implementation of the Class ResourceClearing
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:43
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC62325.MarketOperations.MarketSystem.MarketResults.ResourceDispatchResults import ResourceDispatchResults
from TC57CIM.IEC62325.MarketOperations.MarketSystem.MarketResults.ResourceLoadFollowingInst import ResourceLoadFollowingInst
from TC57CIM.IEC62325.MarketOperations.MarketPlan.MarketFactors import MarketFactors

@dataclass
class ResourceClearing(MarketFactors):
    """Model of market results, including cleaing result of resources. Associated with
    ResourceDispatchResults.
    """
    resourceDispatchResultss: List[ResourceDispatchResults] = []
 
    resourceLoadFollowingInsts: List[ResourceLoadFollowingInst] = []
     