#######################################################
# 
# ResourceLoadFollowingInst.py
# Python implementation of the Class ResourceLoadFollowingInst
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:36
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC61970.Base.Domain.Float import Float

@dataclass
class ResourceLoadFollowingInst:
    """Model of market clearing results for resources that bid to follow load
    """
    # Unique instruction id per instruction, assigned by the SC and provided to ADS.
    # ADS passes through.
    instructionID: String  = None
 
    # The start of the time interval for which requirement is defined.
    intervalStartTime: DateTime  = None
 
    # weighted average for RTPD and RTCD and same for RTID
    calcLoadFollowingMW: Float  = None
 
    dispWindowLowLimt: Float  = None
 
    dispWindowHighLimt: Float  = None
     