#######################################################
# 
# ResourceAwardInstruction.py
# Python implementation of the Class ResourceAwardInstruction
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:30
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC62325.MarketOperations.MktDomain.YesNo import YesNo
from TC57CIM.IEC61970.Base.Domain.Boolean import Boolean
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC62325.MarketOperations.MktDomain.MQSCHGType import MQSCHGType
from TC57CIM.IEC62325.MarketOperations.MarketSystem.MarketResults.SelfScheduleBreakdown import SelfScheduleBreakdown
from TC57CIM.IEC62325.MarketCommon.RegisteredResource import RegisteredResource

@dataclass
class ResourceAwardInstruction:
    """Model of market results, instruction for resource.  Contains details of award
    as attributes
    """
    # For DA Energy: Not Applicable;
    # 
    # For DA AS: DA AS market award;
    # 
    # For RT Energy: Not Applicable;
    # 
    # For RT AS: RT AS market award (excluding DA AS market or self-proviison awards)
    awardMW: Float  = None
 
    # For DA Energy: Total Schedule = DA market schedule + DA self-schedule award;
    # 
    # 
    # For DA AS: DA Ancillary Service Awards = DA AS market award + DA AS self-
    # provision award;
    # 
    # For RT Energy: Total Schedule = RT market schedule + RT self-schedule award;
    # 
    # 
    # For RT AS: RT Ancillary Service Awards = RT AS self-provision award + RT AS
    # market award + DA AS market award + DA AS self-provision award;
    clearedMW: Float  = None
 
    # Marginal Price ($/MW) for the commodity (Regulation Up, Regulation Down,
    # Spinning Reserve, or Non-spinning reserve) for pricing run.
    clearedPrice: Float  = None
 
    # Congestion component of Location Marginal Price (LMP) in monetary units per MW.
    congestLMP: Float  = None
 
    # Cost component of Locational Marginal Pricing (LMP) in monetary units per MW.
    costLMP: Float  = None
 
    # The tier2 mw added by dispatcher action
    # Market results of the synchronized reserve market
    dispatcherAddedMW: Float  = None
 
    # Unit max output for dispatch; bid in economic maximum
    economicMax: Float  = None
 
    # Unit min output for dispatch; bid in economic minimum
    economicMin: Float  = None
 
    # Effective Regulation Down Limit (MW)
    effRegulationDownLimit: Float  = None
 
    # Effective Regulation Up Limit 
    effRegulationUpLimit: Float  = None
 
    # Locational marginal price value
    lmp: Float  = None
 
    # Loss component of Location Marginal Price (LMP) in monetary units per MW.
    lossLMP: Float  = None
 
    # Indicates if an award was manually blocked (Y/N). Valid for Spinning and Non-
    # spinning.
    manuallyBlocked: YesNo  = None
 
    # Indicator (Yes / No) that this resource set the price for this dispatch /
    # schedule.
    marginalResourceIndicator: YesNo  = None
 
    # Identifes if the unit was set to must run by the market participant responsible
    # for bidding in the unit
    mustRunInd: Boolean  = None
 
    # Unit no-load cost in case of energy commodity
    noLoadCost: Float  = None
 
    # Optimal Bid cost
    optimalBidCost: Float  = None
 
    # Optimal Bid production payment based on LMP
    optimalBidPay: Float  = None
 
    # Optimal Bid production margin
    optimalMargin: Float  = None
 
    # Time the manual data entry occured.
    overrideTimeStamp: DateTime  = None
 
    # Provides the ability for the grid operator to override items, such as spin
    # capacity requirements, prior to running the algorithm. This value is market
    # product based (spin, non-spin, reg up, reg down, or RUC).
    overrideValue: Float  = None
 
    # For DA Energy: DA total self-schedule award;
    # For DA AS: DA AS self-provision award;
    # For RT Energy: RT total self-schedule award;
    # For RT AS: RT AS self-provision award (excluding DA AS market or self-provision
    # awards)
    selfSchedMW: Float  = None
 
    # Unit start up cost in case of energy commodity
    startUpCost: Float  = None
 
    # In or out status of resource
    status: String  = None
 
    # Total bid revenue (startup_cost + no_load_cost + bid_pay)
    totalRevenue: Float  = None
 
    updateTimeStamp: DateTime  = None
 
    updateType: MQSCHGType  = None
 
    updateUser: String  = None
 
    SelfScheduleBreakdowns: List[SelfScheduleBreakdown] = []
 
    RegisteredResource: Optional[RegisteredResource] = None
     