#######################################################
# 
# Settlement.py
# Python implementation of the Class Settlement
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:39
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC61968.Common.Document import Document

@dataclass
class Settlement(Document):
    """Specifies a settlement run.
    """
    # The trade date on which the settlement is run. 
    tradeDate: DateTime  = None
     