#######################################################
# 
# CRRSegment.py
# Python implementation of the Class CRRSegment
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:28
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Money import Money
from TC57CIM.IEC61970.Base.Domain.DateTime import DateTime
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

@dataclass
class CRRSegment(IdentifiedObject):
    """CRRSegment represents a segment of a CRR in a particular time frame.
    
      The segment class contains CRR kind, type, quantity, hedger type, time of use
    flag, and segment period.
    """
    # Dollar amount = quantity x clearingPrice
    amount: Money  = None
 
    # Clearing price of a CRR
    clearingPrice: Money  = None
 
    # segment end date time
    endDateTime: DateTime  = None
 
    # The MW amount associated with the CRR
    quantity: float  = None
 
    # segment start date time
    startDateTime: DateTime  = None
     