#######################################################
# 
# GroundingImpedance.py
# Python implementation of the Class GroundingImpedance
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:19
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Reactance import Reactance
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.Wires.EarthFaultCompensator import EarthFaultCompensator

@dataclass
class GroundingImpedance(EarthFaultCompensator):
    """A fixed impedance device used for grounding.
    """
    # Reactance of device.
    x: Reactance  = None
     