#######################################################
# 
# Ground.py
# Python implementation of the Class Ground
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:29
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.Core.ConductingEquipment import ConductingEquipment

@dataclass
class Ground(ConductingEquipment):
    """A point where the system is grounded used for connecting conducting equipment
    to ground. The power system model can have any number of grounds.
    """
    pass
