#######################################################
# 
# Line.py
# Python implementation of the Class Line
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:33
# Original author: andre
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.Core.EquipmentContainer import EquipmentContainer
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.Core.SubGeographicalRegion import SubGeographicalRegion

@dataclass
class Line(EquipmentContainer):
    """Contains equipment beyond a substation belonging to a power transmission line.
    """
    # The sub-geographical region of the line.
    SubGeographicalRegion: Optional[SubGeographicalRegion] = None
     