#######################################################
# 
# PhaseTapChangerTablePoint.py
# Python implementation of the Class PhaseTapChangerTablePoint
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:07
# Original author: Jean-Luc
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.AngleDegrees import AngleDegrees
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.Wires.TapChangerTablePoint import TapChangerTablePoint
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.Wires.PhaseTapChangerTable import PhaseTapChangerTable

@dataclass
class PhaseTapChangerTablePoint(TapChangerTablePoint):
    """Describes each tap step in the phase tap changer tabular curve.
    """
    # The angle difference in degrees.
    angle: AngleDegrees  = None
 
    # The table of this point.
    PhaseTapChangerTable: Optional[PhaseTapChangerTable] = None
     