#######################################################
# 
# PhaseTapChangerTabular.py
# Python implementation of the Class PhaseTapChangerTabular
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:19
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.Wires.PhaseTapChanger import PhaseTapChanger
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.Wires.PhaseTapChangerTable import PhaseTapChangerTable

@dataclass
class PhaseTapChangerTabular(PhaseTapChanger):
    # The phase tap changer table for this phase tap changer.
    phaseTapChangerTable: Optional[PhaseTapChangerTable] = None
     