#######################################################
# 
# RatioTapChangerTable.py
# Python implementation of the Class RatioTapChangerTable
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:26
# Original author: Jean-Luc
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.Core.IdentifiedObject import IdentifiedObject

@dataclass
class RatioTapChangerTable(IdentifiedObject):
    """Describes a curve for how the voltage magnitude and impedance varies with the
    tap step.
    """
    pass
