#######################################################
# 
# SwitchSchedule.py
# Python implementation of the Class SwitchSchedule
# Generated by Enterprise Architect
# Created on:      21-May-2025 11:00:03
# Original author: Jean-Luc
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.LoadModel.SeasonDayTypeSchedule import SeasonDayTypeSchedule
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.Wires.Switch import Switch

@dataclass
class SwitchSchedule(SeasonDayTypeSchedule):
    """A schedule of switch positions.  If RegularTimePoint.value1 is 0, the switch is
    open.  If 1, the switch is closed.
    """
    # A Switch can be associated with SwitchSchedules.
    switch: Optional[Switch] = None
     