#######################################################
# 
# UnderexcLimX1.py
# Python implementation of the Class UnderexcLimX1
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:51:15
# Original author: pcha006
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.PU import PU
from TC57CIM.IEC61970.Base.Domain.Seconds import Seconds
from TC57CIM.IEC61970.Dynamics.StandardModels.UnderexcitationLimiterDynamics.UnderexcitationLimiterDynamics import UnderexcitationLimiterDynamics

@dataclass
class UnderexcLimX1(UnderexcitationLimiterDynamics):
    """<font color="#0f0f0f">Allis-Chalmers minimum excitation limiter.</font>
    """
    # Differential gain (Kf2).
    kf2: PU  = None
 
    # Differential time constant (Tf2) (>0).
    tf2: Seconds  = None
 
    # Minimum excitation limit gain (Km).
    km: PU  = None
 
    # Minimum excitation limit time constant (Tm).
    tm: Seconds  = None
 
    # Minimum excitation limit value (MELMAX).
    melmax: PU  = None
 
    # Minimum excitation limit slope (K) (>0).
    k: PU  = None
     