#######################################################
# 
# DCSwitch.py
# Python implementation of the Class DCSwitch
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:29
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.DC.DCConductingEquipment import DCConductingEquipment

@dataclass
class DCSwitch(DCConductingEquipment):
    """A switch within the DC system.
    """
    pass
