#######################################################
# 
# PerLengthDCLineParameter.py
# Python implementation of the Class PerLengthDCLineParameter
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:13
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.CapacitancePerLength import CapacitancePerLength
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.InductancePerLength import InductancePerLength
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.ResistancePerLength import ResistancePerLength
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.DC.DCLineSegment import DCLineSegment

@dataclass
class PerLengthDCLineParameter:
    # Capacitance per unit of length of the DC line segment; significant for cables
    # only.
    capacitance: CapacitancePerLength  = None
 
    # Inductance per unit of length of the DC line segment.
    inductance: InductancePerLength  = None
 
    # Resistance per length of the DC line segment.
    resistance: ResistancePerLength  = None
 
    # All line segments described by this set of per-length parameters.
    dCLineSegments: List[DCLineSegment] = []
     