#######################################################
# 
# MaintenanceLocation.py
# Python implementation of the Class MaintenanceLocation
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:38
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61968.Work.WorkLocation import WorkLocation

@dataclass
class MaintenanceLocation(WorkLocation):
    """Location where to perform maintenance work.
    """
    # The names of streets at the nearest intersection to work area.
    nearestIntersection: String  = None
 
    # (if applicable) Name, identifier, or description of the subdivision in which
    # work is to occur.
    subdivision: String  = None
 
    # (if applicable) Name, identifier, or description of the lot in which work is to
    # occur.
    lot: String  = None
 
    # (if applicable) Name, identifier, or description of the block in which work is
    # to occur.
    block: String  = None
     