#######################################################
# 
# Tool.py
# Python implementation of the Class Tool
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:59
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Date import Date
from TC57CIM.IEC61968.Work.WorkAsset import WorkAsset

@dataclass
class Tool(WorkAsset):
    """Tool asset.
    """
    # (if applicable) Date the tool was last calibrated.
    lastCalibrationDate: Date  = None
     