#######################################################
# 
# VehicleUsageKind.py
# Python implementation of the Class VehicleUsageKind
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:51:18
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class VehicleUsageKind(Enum):
    """Usage of a vehicle.
    """
    crew = auto()
    user = auto()
    contractor = auto()
    other = auto()