#######################################################
# 
# WorkStatusKind.py
# Python implementation of the Class WorkStatusKind
# Generated by Enterprise Architect
# Created on:      21-May-2025 11:00:40
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class WorkStatusKind(Enum):
    """Kind of status, specific to work.
    """
    # Work approval is pending.
    waitingOnApproval = auto()
    # Work has been approved.
    approved = auto()
    # Work has been canceled.
    cancelled = auto()
    # Work needs to be scheduled.
    waitingToBeScheduled = auto()
    # Work has been scheduled.
    scheduled = auto()
    # Work has been waiting on material.
    waitingOnMaterial = auto()
    # Work is in progress.
    inProgress = auto()
    # Work has been completed, i.e., crew can leave the work location and is
    # available for another work.
    completed = auto()
    # Work has been closed (typically by a person responsible for work management)
    # and is ready for billing.
    closed = auto()
    # Crew has been dispatched.
    dispatched = auto()
    # Crew is 'en route'.
    enroute = auto()
    # Crew is on the site.
    onSite = auto()