#######################################################
# 
# SynchronousMachineEquivalentCircuit.py
# Python implementation of the Class SynchronousMachineEquivalentCircuit
# Generated by Enterprise Architect
# Created on:      21-May-2025 11:00:04
# Original author: ppbr003
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.PU import PU
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.SynchronousMachineDynamics.SynchronousMachineDetailed import SynchronousMachineDetailed

@dataclass
class SynchronousMachineEquivalentCircuit(SynchronousMachineDetailed):
    """The electrical equations for all variations of the synchronous models are based
    on the SynchronousEquivalentCircuit diagram for the direct and quadrature axes.
    
      <b>Equations for conversion between Equivalent Circuit and Time Constant
    Reactance forms:</b>
      <b>Xd</b> = <b>Xad</b> + <b>Xl</b>
      <b>X’d</b> = <b>Xl</b> + <b>Xad</b> * <b>Xfd</b> / (<b>Xad</b> + <b>Xfd</b>)
      <b>X”d</b> = <b>Xl</b> + <b>Xad</b> * <b>Xfd </b>* <b>X1d</b> / (<b>Xad</b> *
    <b>Xfd</b> + <b>Xad</b> * <b>X1d</b> + <b>Xfd</b> * <b>X1d</b>)
      <b>Xq</b> = <b>Xaq</b> + <b>Xl</b>
      <b>X’q</b> = <b>Xl</b> + <b>Xaq</b> * <b>X1q</b> / (<b>Xaq</b>+ <b>X1q</b>)
      <b>X”q</b> = <b>Xl</b> + <b>Xaq</b> *<b> X1q</b>* <b>X2q</b> / (<b>Xaq</b> *
    <b>X1q</b> + <b>Xaq</b> * <b>X2q</b> + <b>X1q</b> * <b>X2q</b>)
      <b>T’do</b> = (<b>Xad</b> + <b>Xfd</b>) / (<b>omega</b><b><sub>0</sub></b> *
    <b>Rfd</b>)
      <b>T”do</b> = (<b>Xad</b> * <b>Xfd</b> + <b>Xad</b> * <b>X1d</b> + <b>Xfd</b>
    * <b>X1d</b>) / (<b>omega</b><b><sub>0</sub></b> * <b>R1d</b> * (<b>Xad</b> +
    <b>Xfd</b>)
      <b>T’qo</b> = (<b>Xaq</b> + <b>X1q</b>) / (<b>omega</b><b><sub>0</sub></b> *
    <b>R1q</b>)
      <b>T”qo</b> = (<b>Xaq</b> * <b>X1q</b> + <b>Xaq</b> * <b>X2q</b> + <b>X1q</b>
    * <b>X2q</b>)/ (<b>omega</b><b><sub>0</sub></b> * <b>R2q</b> * (<b>Xaq</b> +
    <b>X1q</b>)
      <b>
      </b>Same equations using CIM attributes from
    SynchronousMachineTimeConstantReactance class on left of = sign and
    SynchronousMachineEquivalentCircuit class on right (except as noted):
      xDirectSync = xad + RotatingMachineDynamics.statorLeakageReactance
      xDirectTrans = RotatingMachineDynamics.statorLeakageReactance + xad * xfd /
    (xad + xfd)
      xDirectSubtrans = RotatingMachineDynamics.statorLeakageReactance + xad * xfd
    * x1d / (xad * xfd + xad * x1d + xfd * x1d)
      xQuadSync = xaq + RotatingMachineDynamics.statorLeakageReactance
      xQuadTrans = RotatingMachineDynamics.statorLeakageReactance + xaq * x1q /
    (xaq+ x1q)
      xQuadSubtrans = RotatingMachineDynamics.statorLeakageReactance + xaq * x1q*
    x2q / (xaq * x1q + xaq * x2q + x1q * x2q)
      tpdo = (xad + xfd) / (2*pi*nominal frequency * rfd)
      tppdo = (xad * xfd + xad * x1d + xfd * x1d) / (2*pi*nominal frequency * r1d *
    (xad + xfd)
      tpqo = (xaq + x1q) / (2*pi*nominal frequency * r1q)
      tppqo = (xaq * x1q + xaq * x2q + x1q * x2q)/ (2*pi*nominal frequency * r2q *
    (xaq + x1q).
    
      Are only valid for a simplified model where "Canay" reactance is zero.
    """
    # D-axis mutual reactance.
    xad: PU  = None
 
    # Field winding resistance.
    rfd: PU  = None
 
    # Field winding leakage reactance.
    xfd: PU  = None
 
    # D-axis damper 1 winding resistance.
    r1d: PU  = None
 
    # D-axis damper 1 winding leakage reactance.
    x1d: PU  = None
 
    # Differential mutual (“Canay”) reactance.
    xf1d: PU  = None
 
    # Q-axis mutual reactance.
    xaq: PU  = None
 
    # Q-axis damper 1 winding resistance.
    r1q: PU  = None
 
    # Q-axis damper 1 winding leakage reactance.
    x1q: PU  = None
 
    # Q-axis damper 2 winding resistance.
    r2q: PU  = None
 
    # Q-axis damper 2 winding leakage reactance.
    x2q: PU  = None
     