#######################################################
# 
# DCBaseTerminal.py
# Python implementation of the Class DCBaseTerminal
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:34
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.TopologyProfile.DC.DCTopologicalNode import DCTopologicalNode
from ENTSOE.CommonGridModelExchangeStandard.TopologyProfile.Core.ACDCTerminal import ACDCTerminal

@dataclass
class DCBaseTerminal(ACDCTerminal):
    """An electrical connection point at a piece of DC conducting equipment. DC
    terminals are connected at one physical DC node that may have multiple DC
    terminals connected. A DC node is similar to an AC connectivity node. The model
    enforces that DC connections are distinct from AC connections.
    """
    # See association end TopologicalNode.Terminal.
    dCTopologicalNode: Optional[DCTopologicalNode] = None
     