#######################################################
# 
# ActivePowerChangeRate.py
# Python implementation of the Class ActivePowerChangeRate
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:37:50
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier

@dataclass
class ActivePowerChangeRate:
    """Rate of change of active power per time.
    """
    value: Float  = None
 
    unit: UnitSymbol =  UnitSymbol.W
 
    multiplier: UnitMultiplier  = None
 
    denominatorUnit: UnitSymbol =  UnitSymbol.s
 
    denominatorMultiplier: UnitMultiplier =  UnitMultiplier.none
     