#######################################################
# 
# ActivePowerPerFrequency.py
# Python implementation of the Class ActivePowerPerFrequency
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:37:50
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from TC57CIM.IEC61970.Base.Domain.Float import Float

@dataclass
class ActivePowerPerFrequency:
    """Active power variation with frequency.
    """
    denominatorMultiplier: UnitMultiplier  = None
 
    denominatorUnit: UnitSymbol =  UnitSymbol.Hz
 
    multiplier: UnitMultiplier  = None
 
    unit: UnitSymbol =  UnitSymbol.W
 
    value: Float  = None
     