#######################################################
# 
# AngleDegrees.py
# Python implementation of the Class AngleDegrees
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:37:54
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier

@dataclass
class AngleDegrees:
    """Measurement of angle in degrees.
    """
    value: Float  = None
 
    unit: UnitSymbol =  UnitSymbol.deg
 
    multiplier: UnitMultiplier =  UnitMultiplier.none
     