#######################################################
# 
# Area.py
# Python implementation of the Class Area
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:02
# Original author: SELAOST1
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier

@dataclass
class Area:
    """Area.
    """
    value: float  = None
 
    unit: UnitSymbol =  UnitSymbol.m2
 
    multiplier: UnitMultiplier  = None
     