#######################################################
# 
# CapacitancePerLength.py
# Python implementation of the Class CapacitancePerLength
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:06
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier

@dataclass
class CapacitancePerLength:
    """Capacitance per unit of length.
    """
    value: Float  = None
 
    unit: UnitSymbol =  UnitSymbol.F
 
    multiplier: UnitMultiplier =  UnitMultiplier.none
 
    denominatorUnit: UnitSymbol =  UnitSymbol.m
 
    denominatorMultiplier: UnitMultiplier =  UnitMultiplier.none
     