#######################################################
# 
# CostPerEnergyUnit.py
# Python implementation of the Class CostPerEnergyUnit
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:26
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Domain.Currency import Currency
from TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol

@dataclass
class CostPerEnergyUnit:
    """Cost, in units of currency, per quantity of electrical energy generated.
    """
    value: float  = None
 
    unit: Currency  = None
 
    multiplier: UnitMultiplier  = None
 
    denominatorUnit: UnitSymbol =  UnitSymbol.Wh
 
    denominatorMultiplier: UnitMultiplier =  UnitMultiplier.none
     