#######################################################
# 
# DateInterval.py
# Python implementation of the Class DateInterval
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:33
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Date import Date

@dataclass
class DateInterval:
    """Interval between two dates.
    """
    # Start date of this interval.
    start: str  = None
 
    # End date of this interval.
    end: str  = None
     