#######################################################
# 
# DecimalQuantity.py
# Python implementation of the Class DecimalQuantity
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:30
# Original author: selaost1
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Decimal import Decimal
from TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier
from TC57CIM.IEC61970.Base.Domain.Currency import Currency

@dataclass
class DecimalQuantity:
    value: Decimal  = None
 
    unit: UnitSymbol  = None
 
    multiplier: UnitMultiplier  = None
 
    # Quantity with decimal value and associated unit or currency information.
    currency: Currency  = None
     