#######################################################
# 
# Displacement.py
# Python implementation of the Class Displacement
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:44
# Original author: LOO
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier

@dataclass
class Displacement:
    """Unit of displacement relative a reference position, hence can be negative.
    """
    value: float  = None
 
    unit: UnitSymbol =  UnitSymbol.m
 
    multiplier: UnitMultiplier =  UnitMultiplier.none
     