#######################################################
# 
# Integer.py
# Python implementation of the Class Integer
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:39
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

@dataclass
class Integer:
    """An integer number. The range is unspecified and not limited.
    """
    pass
