#######################################################
# 
# PU.py
# Python implementation of the Class PU
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:20
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier

@dataclass
class PU:
    """Per Unit - a positive or negative value referred to a defined base. Values
    typically range from -10 to +10.
    """
    value: Float  = None
 
    unit: UnitSymbol =  UnitSymbol.none
 
    multiplier: UnitMultiplier =  UnitMultiplier.none
     