#######################################################
# 
# Seconds.py
# Python implementation of the Class Seconds
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:41
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier

@dataclass
class Seconds:
    """Time, in seconds.
    """
    # Time, in seconds
    value: Float  = None
 
    unit: UnitSymbol =  UnitSymbol.s
 
    multiplier: UnitMultiplier =  UnitMultiplier.none
     