#######################################################
# 
# StringQuantity.py
# Python implementation of the Class StringQuantity
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:50
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier

@dataclass
class StringQuantity:
    """Quantity with string value (when it is not important whether it is an integral
    or a floating point number) and associated unit information.
    """
    value: String  = None
 
    unit: UnitSymbol  = None
 
    multiplier: UnitMultiplier  = None
     