#######################################################
# 
# VoltagePerReactivePower.py
# Python implementation of the Class VoltagePerReactivePower
# Generated by Enterprise Architect
# Created on:      21-May-2025 11:00:27
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.Base.Domain.UnitSymbol import UnitSymbol
from TC57CIM.IEC61970.Base.Domain.UnitMultiplier import UnitMultiplier

@dataclass
class VoltagePerReactivePower:
    """Voltage variation with reactive power.
    """
    value: float  = None
 
    unit: UnitSymbol =  UnitSymbol.V
 
    multiplier: UnitMultiplier  = None
 
    denominatorUnit: UnitSymbol =  UnitSymbol.VAr
 
    denominatorMultiplier: UnitMultiplier  = None
     