#######################################################
# 
# LimitScalingLimit.py
# Python implementation of the Class LimitScalingLimit
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:43
# Original author: kdemaree
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.PerCent import PerCent
from TC57CIM.IEC61970.InfIEC61970.InfOperationalLimits.LimitDependency import LimitDependency
from TC57CIM.IEC61970.Base.OperationalLimits.OperationalLimit import OperationalLimit

@dataclass
class LimitScalingLimit(LimitDependency):
    """Specifies an operational  limit is calculated by scaling another operational
    limit.
    """
    # The associated source limit is scaled by this value to compute the limit of the
    # dependency model.
    limitScalingPercent: PerCent  = None
 
    operationalLimit: Optional[OperationalLimit] = None
     