#######################################################
# 
# OperatonalLimitTypeScaling.py
# Python implementation of the Class OperatonalLimitTypeScaling
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:58
# Original author: kdemaree
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.PerCent import PerCent
from TC57CIM.IEC61970.Base.OperationalLimits.OperationalLimitType import OperationalLimitType

@dataclass
class OperatonalLimitTypeScaling:
    """One operational limit type scales values of another operational limit type when
    under the same operational limit set.    This applies to any operational limit
    assigned to the target operational limit type and without other limit
    dependency models.
    """
    # The percentage scaling of the source limit to compute the target limit.  Applys
    # to operational limits within an operaitonal limit set when both source and
    # target operational limit types exist.
    scalingPercent: PerCent  = None
 
    OperationalLimitType: Optional[OperationalLimitType] = None
 
    OperationalLimitType: Optional[OperationalLimitType] = None
     