#######################################################
# 
# ScheduledCurrentLimitValue.py
# Python implementation of the Class ScheduledCurrentLimitValue
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:50:39
# Original author: kdemaree
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.CurrentFlow import CurrentFlow
from TC57CIM.IEC61970.InfIEC61970.InfOperationalLimits.ScheduledLimitValue import ScheduledLimitValue

@dataclass
class ScheduledCurrentLimitValue(ScheduledLimitValue):
    """A current limit that is scheduled.
    """
    # The current flow limit value applicable at the scheduled time.
    value: CurrentFlow  = None
     