#######################################################
# 
# TemperaturePolynomialLimit.py
# Python implementation of the Class TemperaturePolynomialLimit
# Generated by Enterprise Architect
# Created on:      21-May-2025 11:00:09
# Original author: akamath
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Float import Float
from TC57CIM.IEC61970.InfIEC61970.InfOperationalLimits.EnvironmentalDependentLimit import EnvironmentalDependentLimit

@dataclass
class TemperaturePolynomialLimit(EnvironmentalDependentLimit):
    """This describes the coefficients of a polynomial function that has temperature
    as input and calculates limit values as output.
    """
    # The polinomial coefficent of power 0.
    coefficient0: float  = None
 
    # The polinomial coefficent of power 1.
    coefficient1: float  = None
 
    # The polinomial coefficent of power 2.
    coefficient2: float  = None
 
    # The polinomial coefficent of power 3.
    coefficient3: float  = None
 
    # The polinomial coefficent of power 4.
    coefficient4: float  = None
     