#######################################################
# 
# TemperatureDependentLimitPoint.py
# Python implementation of the Class TemperatureDependentLimitPoint
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:56
# Original author: kdemaree
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.PerCent import PerCent
from TC57CIM.IEC61970.Base.Domain.Temperature import Temperature

@dataclass
class TemperatureDependentLimitPoint:
    """A point on a table of limit verses temperature.
    """
    # The scaling of the operational limit in percent.
    limitPercent: PerCent  = None
 
    # The temperature of the table point.
    temperature: Temperature  = None
     