#######################################################
# 
# WeatherStation.py
# Python implementation of the Class WeatherStation
# Generated by Enterprise Architect
# Created on:      21-May-2025 11:00:29
# Original author: akamath
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Core.PowerSystemResource import PowerSystemResource

@dataclass
class WeatherStation(PowerSystemResource):
    """This represents a source of ambient temperature.
    """
    pass
