#######################################################
# 
# DayType.py
# Python implementation of the Class DayType
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:25
# Original author: andre
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.Core.IdentifiedObject import IdentifiedObject

@dataclass
class DayType(IdentifiedObject):
    """Group of similar days.   For example it could be used to represent weekdays,
    weekend, or holidays.
    """
    pass
