#######################################################
# 
# LoadArea.py
# Python implementation of the Class LoadArea
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:38
# Original author: Jean-Luc
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.LoadModel.SubLoadArea import SubLoadArea
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.LoadModel.EnergyArea import EnergyArea

@dataclass
class LoadArea(EnergyArea):
    """The class is the root or first level in a hierarchical structure for grouping
    of loads for the purpose of load flow load scaling.
    """
    # The SubLoadAreas in the LoadArea.
    subLoadAreas: List[SubLoadArea] = []
     