#######################################################
# 
# SubLoadArea.py
# Python implementation of the Class SubLoadArea
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:59
# Original author: andre
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.LoadModel.EnergyArea import EnergyArea
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.LoadModel.LoadGroup import LoadGroup
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.LoadModel.LoadArea import LoadArea

@dataclass
class SubLoadArea(EnergyArea):
    """The class is the second level in a hierarchical structure for grouping of loads
    for the purpose of load flow load scaling.
    """
    # The Loadgroups in the SubLoadArea.
    loadGroups: List[LoadGroup] = []
 
    # The LoadArea where the SubLoadArea belongs.
    loadArea: Optional[LoadArea] = None
     