#######################################################
# 
# EquipmentFault.py
# Python implementation of the Class EquipmentFault
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:45
# Original author: kdemaree
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Core.Terminal import Terminal
from TC57CIM.IEC61970.Base.Faults.Fault import Fault

@dataclass
class EquipmentFault(Fault):
    """A fault applied at the terminal, external to the equipment. This class is not
    used to specify faults internal to the equipment.
    """
    # The terminal connecting to the bus to which the fault is applied.
    Terminal: Optional[Terminal] = None
     