#######################################################
# 
# CoordinateSystem.py
# Python implementation of the Class CoordinateSystem
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:17
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject

@dataclass
class CoordinateSystem(IdentifiedObject):
    """Coordinate reference system.
    """
    # A Uniform Resource Name (URN) for the coordinate reference system (crs) used to
    # define 'Location.PositionPoints'.
    # An example would be the European Petroleum Survey Group (EPSG) code for a
    # coordinate reference system, defined in URN under the Open Geospatial
    # Consortium (OGC) namespace as: urn:ogc:def:uom:EPSG::XXXX, where XXXX is an
    # EPSG code (a full list of codes can be found at the EPSG Registry web site http:
    # //www.epsg-registry.org/). To define the coordinate system as being WGS84
    # (latitude, longitude) using an EPSG OGC, this attribute would be urn:ogc:def:
    # uom:EPSG::4236.
    # A profile should limit this code to a set of allowed URNs agreed to by all
    # sending and receiving parties.
    crsUrn: String  = None
     