#######################################################
# 
# Crew.py
# Python implementation of the Class Crew
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:18
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61968.Common.Status import Status
from TC57CIM.IEC61968.Common.CrewMember import CrewMember
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC61968.Common.CrewType import CrewType

@dataclass
class Crew(IdentifiedObject):
    """Group of people with specific skills, tools, and vehicles.
    """
    # Status of this crew.
    status: Status  = None
 
    # All members of this crew.
    crewMembers: List[CrewMember] = []
 
    # Type of this crew.
    crewType: Optional[CrewType] = None
     