#######################################################
# 
# ElectronicAddress.py
# Python implementation of the Class ElectronicAddress
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:47
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String

@dataclass
class ElectronicAddress:
    """Electronic address information.
    """
    # Address on local area network.
    lan: str  = None
 
    # MAC (Media Access Control) address.
    mac: str  = None
 
    # Primary email address.
    email1: str  = None
 
    # Alternate email address.
    email2: str  = None
 
    # World wide web address.
    web: str  = None
 
    # Radio address.
    radio: str  = None
 
    # User ID needed to log in, which can be for an individual person, an
    # organisation, a location, etc.
    userID: str  = None
 
    # Password needed to log in.
    password: str  = None
     