#######################################################
# 
# Location.py
# Python implementation of the Class Location
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:48
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String
from TC57CIM.IEC61968.Common.StreetAddress import StreetAddress
from TC57CIM.IEC61968.Common.TelephoneNumber import TelephoneNumber
from TC57CIM.IEC61968.Common.ElectronicAddress import ElectronicAddress
from TC57CIM.IEC61968.Common.Status import Status
from TC57CIM.IEC61970.Base.Meas.Measurement import Measurement
from TC57CIM.IEC61968.Common.PositionPoint import PositionPoint
from TC57CIM.IEC61970.Base.Core.PowerSystemResource import PowerSystemResource
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC61968.Common.CoordinateSystem import CoordinateSystem
from TC57CIM.IEC61968.Common.ConfigurationEvent import ConfigurationEvent

@dataclass
class Location(IdentifiedObject):
    """The place, scene, or point of something where someone or something has been, is,
    and/or will be at a given moment in time. It can be defined with one or more
    postition points (coordinates) in a given coordinate system.
    """
    # Classification by utility's corporate standards and practices, relative to the
    # location itself (e.g., geographical, functional accounting, etc., not a given
    # property that happens to exist at that location).
    type: str  = None
 
    # Main address of the location.
    mainAddress: StreetAddress  = None
 
    # Secondary address of the location. For example, PO Box address may have
    # different ZIP code than that in the 'mainAddress'.
    secondaryAddress: StreetAddress  = None
 
    # Phone number.
    phone1: TelephoneNumber  = None
 
    # Additional phone number.
    phone2: TelephoneNumber  = None
 
    # Electronic address.
    electronicAddress: ElectronicAddress  = None
 
    # (if applicable) Reference to geographical information source, often external to
    # the utility.
    geoInfoReference: str  = None
 
    # (if applicable) Direction that allows field crews to quickly find a given asset.
    # For a given location, such as a street address, this is the relative direction
    # in which to find the asset. For example, a streetlight may be located at the
    # 'NW' (northwest) corner of the customer's site, or a usage point may be located
    # on the second floor of an apartment building.
    direction: str  = None
 
    # Status of this location.
    status: Status  = None
 
    measurements: List[Measurement] = []
 
    # Sequence of position points describing this location, expressed in coordinate
    # system 'Location.CoordinateSystem'.
    positionPoints: List[PositionPoint] = []
 
    # All power system resources at this location.
    powerSystemResources: List[PowerSystemResource] = []
 
    # Coordinate system used to describe position points of this location.
    coordinateSystem: Optional[CoordinateSystem] = None
 
    # All configuration events created for this location.
    configurationEvents: List[ConfigurationEvent] = []
     