#######################################################
# 
# OrganisationRole.py
# Python implementation of the Class OrganisationRole
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:09
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Core.IdentifiedObject import IdentifiedObject
from TC57CIM.IEC61968.Common.Organisation import Organisation
from TC57CIM.IEC61968.Common.ConfigurationEvent import ConfigurationEvent

@dataclass
class OrganisationRole(IdentifiedObject):
    """Identifies a way in which an organisation may participate in the utility
    enterprise (e.g., customer, manufacturer, etc).
    """
    # Organisation having this role.
    organisation: Optional[Organisation] = None
 
    # All configuration events created for this organisation role.
    configurationEvents: List[ConfigurationEvent] = []
     