#######################################################
# 
# Priority.py
# Python implementation of the Class Priority
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:25
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.Integer import Integer
from TC57CIM.IEC61970.Base.Domain.String import String

@dataclass
class Priority:
    """Priority definition.
    """
    # Priority level; usually, lower number means high priority, but the details are
    # provided in 'type'.
    rank: int  = None
 
    # Type describing 'rank'; e.g., high, emergency, etc.
    type: str  = None
 
    # Justification for 'rank'.
    justification: str  = None
     