#######################################################
# 
# TelephoneNumber.py
# Python implementation of the Class TelephoneNumber
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:55
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String

@dataclass
class TelephoneNumber:
    """Telephone number.
    """
    # Country code.
    countryCode: String  = None
 
    # Area or region code.
    areaCode: String  = None
 
    # (if applicable) City code.
    cityCode: String  = None
 
    # Main (local) part of this telephone number.
    localNumber: String  = None
 
    # (if applicable) Extension for this telephone number.
    extension: String  = None
     