#######################################################
# 
# TownDetail.py
# Python implementation of the Class TownDetail
# Generated by Enterprise Architect
# Created on:      21-May-2025 11:00:13
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from TC57CIM.IEC61970.Base.Domain.String import String

@dataclass
class TownDetail:
    """Town details, in the context of address.
    """
    # Town code.
    code: str  = None
 
    # Town section. For example, it is common for there to be 36 sections per
    # township.
    section: str  = None
 
    # Town name.
    name: str  = None
 
    # Name of the state or province.
    stateOrProvince: str  = None
 
    # Name of the country.
    country: str  = None
     