#######################################################
# 
# Accumulator.py
# Python implementation of the Class Accumulator
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:47:43
# Original author: Jean-Luc
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.Meas.Measurement import Measurement

@dataclass
class Accumulator(Measurement):
    """Accumulator represents an accumulated (counted) Measurement, e.g. an energy
    value.
    """
    pass
