#######################################################
# 
# AnalogValue.py
# Python implementation of the Class AnalogValue
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:37:53
# Original author: Jean-Luc
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Simple_Float import Simple_Float
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.Meas.MeasurementValue import MeasurementValue
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.Meas.Analog import Analog

@dataclass
class AnalogValue(MeasurementValue):
    """AnalogValue represents an analog MeasurementValue.
    """
    # The value to supervise.
    value: Simple_Float  = None
 
    # The values connected to this measurement.
    Analog: Optional[Analog] = None
     