#######################################################
# 
# DiscreteValue.py
# Python implementation of the Class DiscreteValue
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:34
# Original author: Jean-Luc
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Integer import Integer
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.Meas.MeasurementValue import MeasurementValue
from ENTSOE.CommonGridModelExchangeStandard.EquipmentProfile.Meas.Discrete import Discrete

@dataclass
class DiscreteValue(MeasurementValue):
    """DiscreteValue represents a discrete MeasurementValue.
    """
    # The value to supervise.
    value: Integer  = None
 
    # The values connected to this measurement.
    discrete: Optional[Discrete] = None
     