#######################################################
# 
# BidCalculationBasis.py
# Python implementation of the Class BidCalculationBasis
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:01
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class BidCalculationBasis(Enum):
    """The basis used to calculate the bid price curve for an energy default bid.
    """
    # Based on prices paid at particular pricing location.
    LMP_BASED = auto()
    # Based on unit generation characteristics and a cost of fuel.
    COST_BASED = auto()
    # An amount negotiated with the designated Independent Entity.
    NEGOTIATED = auto()