#######################################################
# 
# BidType.py
# Python implementation of the Class BidType
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:03
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class BidType(Enum):
    """For example:
      DEFAULT_ENERGY_BID
      DEFAULT_STARTUP_BID
      DEFAULT_MINIMUM_LOAD_BID
    """
    DEFAULT_ENERGY_BID = auto()
    DEFAULT_STARTUP_BID = auto()
    DEFAULT_MINIMUM_LOAD_BID = auto()