#######################################################
# 
# CommitmentType.py
# Python implementation of the Class CommitmentType
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:48:08
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class CommitmentType(Enum):
    """For example:
      SELF - Self commitment
      ISO - New commitment for this market period
      UC - Existing commitment that was a hold over from a previous market.
    """
    SELF = auto()
    ISO = auto()
    UC = auto()