#######################################################
# 
# ConstraintRampType.py
# Python implementation of the Class ConstraintRampType
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:15
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class ConstraintRampType(Enum):
    """Constraint Ramp type
    """
    FAST = auto()
    SLOW = auto()