#######################################################
# 
# DispatchResponseType.py
# Python implementation of the Class DispatchResponseType
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:57:44
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class DispatchResponseType(Enum):
    """For example:
      NON_RESPONSE
      ACCEPT
      DECLINE
      PARTIAL.
    """
    NON_RESPONSE = auto()
    ACCEPT = auto()
    DECLINE = auto()
    PARTIAL = auto()