#######################################################
# 
# EnergyPriceIndexType.py
# Python implementation of the Class EnergyPriceIndexType
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:41
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class EnergyPriceIndexType(Enum):
    """For example:
      WHOLESALE
      RETAIL
      BOTH
    """
    WHOLESALE = auto()
    RETAIL = auto()
    BOTH = auto()