#######################################################
# 
# InterTieDirection.py
# Python implementation of the Class InterTieDirection
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:58:40
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class InterTieDirection(Enum):
    """Direction of an intertie.
    """
    # Export.
    E = auto()
    # Import.
    I = auto()