#######################################################
# 
# LoadForecastType.py
# Python implementation of the Class LoadForecastType
# Generated by Enterprise Architect
# Created on:      21-May-2025 09:49:39
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class LoadForecastType(Enum):
    """Load forecast zone types.
    """
    # Load forecast zone.
    LFZ = auto()
    # Metered sub system zone.
    LZMS = auto()