#######################################################
# 
# MktInvoiceLineItemKind.py
# Python implementation of the Class MktInvoiceLineItemKind
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:48
# Original author: T. Kostic
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class MktInvoiceLineItemKind(Enum):
    """Kind of invoice line item.
    """
    initial = auto()
    recalculation = auto()
    other = auto()