#######################################################
# 
# MQSCHGType.py
# Python implementation of the Class MQSCHGType
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:02
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class MQSCHGType(Enum):
    """For example:
      ADD - add
      CHG - change
    """
    ADD = auto()
    CHG = auto()