#######################################################
# 
# MQSInstructionSource.py
# Python implementation of the Class MQSInstructionSource
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:02
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class MQSInstructionSource(Enum):
    """Valid values, for example:
      INS - Instruction from RTM
      ACT - Actual instruction after the fact
    """
    INS = auto()
    ACT = auto()