#######################################################
# 
# OnOff.py
# Python implementation of the Class OnOff
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:39:56
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class OnOff(Enum):
    """ON
      OFF
    """
    ON = auto()
    OFF = auto()