#######################################################
# 
# ResourceLimitIndicator.py
# Python implementation of the Class ResourceLimitIndicator
# Generated by Enterprise Architect
# Created on:      21-May-2025 10:59:43
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class ResourceLimitIndicator(Enum):
    """Locational AS Flags indicating whether the Upper or Lower Bound limit of the AS
    regional procurment is binding
    """
    UPPER = auto()
    LOWER = auto()