#######################################################
# 
# ResourceAssnType.py
# Python implementation of the Class ResourceAssnType
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:30
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto

class ResourceAssnType(Enum):
    """For example:
      Asset Owner Sink designator for use by CRR
      Asset Owner Source designator for use by CRR
      Reliability Must Run
      Scheduling Coordinator
      Load Serving Entity
    """
    CSNK = auto()
    CSRC = auto()
    RMR = auto()
    SC = auto()
    LSE = auto()