from __future__ import annotations
from typing import List, Optional, Any, TYPE_CHECKING
from dataclasses import dataclass, field
from enum import Enum, auto
if TYPE_CHECKING:          from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.PU import PU     
if TYPE_CHECKING:          from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Simple_Float import Simple_Float     
if TYPE_CHECKING:          from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Seconds import Seconds     
from ENTSOE.CommonGridModelExchangeStandard.DynamicsProfile.StandardModels.TurbineGovernorDynamics.TurbineGovernorDynamics import TurbineGovernorDynamics

@dataclass
class GovSteamFV4(TurbineGovernorDynamics):
    """Detailed electro-hydraulic governor for steam unit.
    """
    # Frequency bias (reciprocal of droop) (Kf1).  Typical Value = 20.
    kf1_: PU  = None
 
    # Frequency control (reciprocal of droop) (Kf3).  Typical Value = 20.
    kf3_: PU  = None
 
    # Maximum positive power error (Lps).  Typical Value = 0.03.
    lps_: PU  = None
 
    # Maximum negative power error (Lpi).  Typical Value = -0.15.
    lpi_: PU  = None
 
    # Upper limit for frequency correction (MX<sub>EF</sub>).  Typical Value = 0.05.
    mxef_: PU  = None
 
    # Lower limit for frequency correction (MN<sub>EF</sub>).  Typical Value = -0.05.
    mnef_: PU  = None
 
    # Maximum value of regulator set-point (Crmx).  Typical Value = 1.2.
    crmx_: PU  = None
 
    # Minimum value of regulator set-point (Crmn).  Typical Value = 0.
    crmn_: PU  = None
 
    # Proportional gain of electro-hydraulic regulator (Kpt).  Typical Value = 0.3.
    kpt_: PU  = None
 
    # Integral gain of electro-hydraulic regulator (Kit).  Typical Value = 0.04.
    kit_: PU  = None
 
    # Maximum value of integral regulator (Rvgmx).  Typical Value = 1.2.
    rvgmx_: PU  = None
 
    # Minimum value of integral regulator (Rvgmn).  Typical Value = 0.
    rvgmn_: PU  = None
 
    # Maximum regulator gate opening velocity (Svmx).  Typical Value = 0.0333.
    svmx_: Simple_Float  = None
 
    # Maximum regulator gate closing velocity (Svmn).  Typical Value = -0.0333.
    svmn_: Simple_Float  = None
 
    # Maximum valve opening (Srmx).  Typical Value = 1.1.
    srmx_: PU  = None
 
    # Minimum valve opening (Srmn).  Typical Value = 0.
    srmn_: PU  = None
 
    # Proportional gain of pressure feedback regulator (Kpp).  Typical Value = 1.
    kpp_: PU  = None
 
    # Integral gain of pressure feedback regulator (Kip).  Typical Value = 0.5.
    kip_: PU  = None
 
    # Maximum value of integral regulator (Rsmimx).  Typical Value = 1.1.
    rsmimx_: PU  = None
 
    # Minimum value of integral regulator (Rsmimn).  Typical Value = 0.
    rsmimn_: PU  = None
 
    # First gain coefficient of  intercept valves characteristic (Kmp1).  Typical
    # Value = 0.5.
    kmp1_: PU  = None
 
    # Second gain coefficient of intercept valves characteristic (Kmp2).  Typical
    # Value = 3.5.
    kmp2_: PU  = None
 
    # Intercept valves characteristic discontinuity point (Srsmp).  Typical Value = 0.
    # 43.
    srsmp_: PU  = None
 
    # Control valves rate opening time (Ta).  Typical Value = 0.8.
    ta_: Seconds  = None
 
    # Control valves rate closing time (Tc).  Typical Value = 0.5.
    tc_: Seconds  = None
 
    # Control valves servo time constant (Ty).  Typical Value = 0.1.
    ty_: Seconds  = None
 
    # Maximum control valve position (Yhpmx).  Typical Value = 1.1.
    yhpmx_: PU  = None
 
    # Minimum control valve position (Yhpmn).  Typical Value = 0.
    yhpmn_: PU  = None
 
    # Intercept valves rate opening time (Tam).  Typical Value = 0.8.
    tam_: Seconds  = None
 
    # Intercept valves rate closing time (Tcm).  Typical Value = 0.5.
    tcm_: Seconds  = None
 
    # Maximum intercept valve position (Ympmx).  Typical Value = 1.1.
    ympmx_: PU  = None
 
    # Minimum intercept valve position (Ympmn).  Typical Value = 0.
    ympmn_: PU  = None
 
    # Coefficient of linearized equations of turbine (Stodola formulation) (Y).
    # Typical Value = 0.13.
    y_: PU  = None
 
    # High pressure (HP) time constant of the turbine (Thp).  Typical Value = 0.15.
    thp_: Seconds  = None
 
    # Reheater  time constant of the turbine (Trh).  Typical Value = 10.
    trh_: Seconds  = None
 
    # Low pressure (LP) time constant of the turbine (Tmp).  Typical Value = 0.4.
    tmp_: Seconds  = None
 
    # Fraction  of total turbine output generated by HP part (Khp).  Typical Value =
    # 0.35.
    khp_: PU  = None
 
    # First value of pressure set point static characteristic (Pr1).  Typical Value =
    # 0.2.
    pr1_: PU  = None
 
    # Second value of pressure set point static characteristic, corresponding to Ps0
    # = 1.0 PU (Pr2).  Typical Value = 0.75.
    pr2_: PU  = None
 
    # Minimum value of pressure set point static characteristic (Psmn).  Typical
    # Value = 1.
    psmn_: PU  = None
 
    # Proportional gain of pressure regulator (Kpc).  Typical Value = 0.5.
    kpc_: PU  = None
 
    # Integral gain of pressure regulator (Kic).  Typical Value = 0.0033.
    kic_: PU  = None
 
    # Derivative gain of pressure regulator (Kdc).  Typical Value = 1.
    kdc_: PU  = None
 
    # Derivative time constant of pressure regulator (Tdc).  Typical Value = 90.
    tdc_: Seconds  = None
 
    # Maximum value of pressure regulator output (Cpsmx).  Typical Value = 1.
    cpsmx_: PU  = None
 
    # Minimum value of pressure regulator output (Cpsmn).  Typical Value = -1.
    cpsmn_: PU  = None
 
    # Maximum variation of fuel flow (Krc).  Typical Value = 0.05.
    krc_: PU  = None
 
    # Time constant of fuel regulation (Tf1).  Typical Value = 10.
    tf1_: Seconds  = None
 
    # Time constant of steam chest (Tf2).  Typical Value = 10.
    tf2_: Seconds  = None
 
    # Boiler time constant (Tv).  Typical Value = 60.
    tv_: Seconds  = None
 
    # Pressure loss due to flow friction in the boiler tubes (Ksh).  Typical Value =
    # 0.08.
    ksh_: PU  = None
     