#######################################################
# 
# DCTopologicalNode.py
# Python implementation of the Class DCTopologicalNode
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:38:30
# Original author: civanov
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.StateVariablesProfile.Core.IdentifiedObject import IdentifiedObject

@dataclass
class DCTopologicalNode(IdentifiedObject):
    """DC bus.
    """
    pass
