#######################################################
# 
# SvVoltage.py
# Python implementation of the Class SvVoltage
# Generated by Enterprise Architect
# Created on:      20-May-2025 17:40:49
# Original author: andre
# 
#######################################################
from typing import List, Optional, Any
from dataclasses import dataclass
from enum import Enum, auto
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.AngleDegrees import AngleDegrees
from ENTSOE.CommonGridModelExchangeStandard.DomainProfile.Voltage import Voltage
from ENTSOE.CommonGridModelExchangeStandard.StateVariablesProfile.Topology.TopologicalNode import TopologicalNode

@dataclass
class SvVoltage:
    """State variable for voltage.
    """
    # The voltage angle of the topological node complex voltage with respect to
    # system reference.
    angle: AngleDegrees  = None
 
    # The voltage magnitude of the topological node.
    v: Voltage  = None
 
    # The state voltage associated with the topological node.
    TopologicalNode: Optional[TopologicalNode] = None
     